TERMUX_PKG_HOMEPAGE=https://sourceforge.net/projects/gpg-crypter/
TERMUX_PKG_DESCRIPTION="A graphical front-end to GnuPG(GPG) using the GTK3 toolkit and libgpgme"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.4.1
TERMUX_PKG_REVISION=24
TERMUX_PKG_SRCURL=https://downloads.sourceforge.net/gpg-crypter/gpg-crypter-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=1f7e2b27bf4a27ecbb07bce9cd40d1c08477a3bd065ba7d1a75d1732e4bdc023
TERMUX_PKG_DEPENDS="glib, gpgme, gtk3, pinentry-gtk"
TERMUX_PKG_RM_AFTER_INSTALL="lib/locale"
