diff -uNr wireless_tools.30/Makefile wireless_tools.30.mod2/Makefile
--- wireless_tools.30/Makefile	2009-11-24 20:53:40.000000000 +0200
+++ wireless_tools.30.mod2/Makefile	2017-10-17 11:55:09.020967925 +0300
@@ -5,11 +5,11 @@
 ## Installation directory. By default, go in /usr/local.
 ## Distributions should probably use /, but they probably know better...
 ifndef PREFIX
-  PREFIX = /usr/local
+  PREFIX = /data/data/com.termux/files/usr
 endif
 
 ## Compiler to use (modify this for cross compile).
-CC = gcc
+CC ?= clang
 ## Other tools you need to modify for cross compile (static lib only).
 AR = ar
 RANLIB = ranlib
@@ -73,10 +73,10 @@
 DYNAMIC_LINK= libiw.so
 
 # Install directories
-INSTALL_DIR= $(PREFIX)/sbin
+INSTALL_DIR= $(PREFIX)/bin
 INSTALL_LIB= $(PREFIX)/lib
 INSTALL_INC= $(PREFIX)/include
-INSTALL_MAN= $(PREFIX)/man
+INSTALL_MAN= $(PREFIX)/share/man
 
 # Various commands
 RM = rm -f
@@ -205,6 +205,7 @@
 
 clean::
 	$(RM_CMD) 
+	$(RM) $(PROGS)
 
 realclean::
 	$(RM_CMD) 
