TERMUX_PKG_HOMEPAGE=https://gitlab.xfce.org/xfce/xfce4-dev-tools
TERMUX_PKG_DESCRIPTION="A collection of tools and macros for Xfce developers"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
_MAJOR_VERSION=4.17
TERMUX_PKG_VERSION=${_MAJOR_VERSION}.1
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/xfce/xfce4-dev-tools/${_MAJOR_VERSION}/xfce4-dev-tools-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=e9af0efc1acfe443cf513e7f82621f81ef62b50e2bf241096a41b90489ef4f9f
TERMUX_PKG_DEPENDS="glib"
