TERMUX_SUBPKG_DESCRIPTION="Wheels for Python 'ensurepip'."
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_DEPEND_ON_PARENT=true
TERMUX_SUBPKG_INCLUDE="
lib/python${_MAJOR_VERSION}/ensurepip/_bundled/
"
