TERMUX_PKG_HOMEPAGE=http://www.muchsync.org/
TERMUX_PKG_DESCRIPTION="Synchronize notmuch mail across machines"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=6
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=http://www.muchsync.org/src/muchsync-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0b3de3b4d885edb9f887a07dcbc8b596e7fef2038c61e682cfa55a13fa4ce9e8
TERMUX_PKG_DEPENDS="libc++, libsqlite, libxapian, notmuch, openssl"
