TERMUX_PKG_HOMEPAGE=https://www.gnupg.org/related_software/gpgme/
TERMUX_PKG_DESCRIPTION="C++ bindings for GPGME"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.2.0"
TERMUX_PKG_SRCURL="https://www.gnupg.org/ftp/gcrypt/gpgmepp/gpgmepp-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=6651c5f7f801543d5b676719df9fec8053b0a6f5aba40b98ca0d2bee11136f30
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="gpgme, libc++, libgpg-error"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$TERMUX__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$TERMUX__PREFIX__INCLUDE_SUBDIR
"
