TERMUX_PKG_HOMEPAGE=https://www.gnupg.org/related_software/gpgme/
TERMUX_PKG_DESCRIPTION="C++ bindings for GPGME"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.0.0"
TERMUX_PKG_SRCURL="https://www.gnupg.org/ftp/gcrypt/gpgmepp/gpgmepp-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=d4796049c06708a26f3096f748ef095347e1a3c1e570561701fe952c3f565382
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="gpgme, libc++, libgpg-error"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$TERMUX__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$TERMUX__PREFIX__INCLUDE_SUBDIR
"
