TERMUX_PKG_HOMEPAGE="https://github.com/alteholz/mdns-scan"
TERMUX_PKG_DESCRIPTION="A tool for scanning for mDNS/DNS-SD services published on the local network"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.5
TERMUX_PKG_SRCURL=https://github.com/alteholz/mdns-scan/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=fa830d91b993d15f8a463c8dd68f7106f0dded87928bec36074de934c2c52f73
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="DESTDIR=${TERMUX_PREFIX}/../"
TERMUX_PKG_MAKE_INSTALL_TARGET="DESTDIR=${TERMUX_PREFIX}/../ install"
