TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/libsigsegv/
TERMUX_PKG_DESCRIPTION="GNU libsigsegv is a library for handling page faults in user mode"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.14
TERMUX_PKG_REVISION=0
TERMUX_PKG_SRCURL=https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=cdac3941803364cf81a908499beb79c200ead60b6b5b40cad124fd1e06caa295
TERMUX_PKG_BREAKS="libsigsegv-dev"
TERMUX_PKG_REPLACES="libsigsegv-dev"
