TERMUX_PKG_HOMEPAGE=https://github.com/libpinyin/ibus-libpinyin
TERMUX_PKG_DESCRIPTION="Intelligent Pinyin engine based on libpinyin for IBus"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.16.6
TERMUX_PKG_SRCURL=https://github.com/libpinyin/ibus-libpinyin/releases/download/v$TERMUX_PKG_VERSION/ibus-libpinyin-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=99f7b44bcff606bc4dfa3535bccf42384616a8ee834ac65459e7ac9e3c79be37
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ibus, libpinyin, libopencc, libsqlite, lua51, libdb"
