TERMUX_PKG_HOMEPAGE=https://www.gaia-gis.it/fossil/freexl
TERMUX_PKG_DESCRIPTION="Library to extract valid data from within an Excel (.xls) spreadsheet"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.0.6
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://www.gaia-gis.it/gaia-sins/freexl-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=3de8b57a3d130cb2881ea52d3aa9ce1feedb1b57b7daa4eb37f751404f90fc22
TERMUX_PKG_DEPENDS="libiconv"
TERMUX_PKG_GROUPS="science"
