TERMUX_PKG_HOMEPAGE=https://www.gaia-gis.it/fossil/freexl
TERMUX_PKG_DESCRIPTION="Library to extract valid data from within an Excel (.xls) spreadsheet"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.0.0"
TERMUX_PKG_SRCURL=https://www.gaia-gis.it/gaia-sins/freexl-sources/freexl-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=176705f1de58ab7c1eebbf5c6de46ab76fcd8b856508dbd28f5648f7c6e1a7f0
TERMUX_PKG_DEPENDS="libiconv, libminizip, libexpat"
TERMUX_PKG_GROUPS="science"
