TERMUX_PKG_HOMEPAGE=https://www.nongnu.org/lzip/
TERMUX_PKG_DESCRIPTION="Lossless data compressor similar to gzip and bzip2"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.23
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://download.savannah.gnu.org/releases/lzip/lzip-${TERMUX_PKG_VERSION}.tar.lz
TERMUX_PKG_SHA256=ea02b9e6fb25d0e1a1d3ef4fdeb6ab26b931f1ece66fa1cee2983c95215e930a
TERMUX_PKG_DEPENDS="libc++"
