/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Apr  8, 2018
 *			* <u0_a62@localhost>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.10.1\n"
	"                  Configured on: 2018-04-08\n"
	"                  Configured by: Ninja\n"
	"                    Host system: Linux-4.4.62-android-x86\n"
	"              Uname information: Linux\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: /data/data/com.termux/files/usr\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: \n"
	"              Debugging Symbols: \n"
	"                        Asserts: \n"
	"                      Profiling: \n"
	"             Optimization Level: \n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: \n"
	"  Statically Linked Executables: OFF\n"
	"                        LDFLAGS: \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: m;dl\n"
	"                       Archiver: /data/data/com.termux/files/usr/bin/ar\n"
	"                         Ranlib: /data/data/com.termux/files/usr/bin/ranlib\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: yes\n"
	"                     C Compiler: /data/data/com.termux/files/usr/bin/cc 6.0.0\n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"                         CFLAGS: \n"
	"                      H5_CFLAGS: \n"
	"                      AM_CFLAGS: \n"
	"               Shared C Library: YES\n"
	"               Static C Library: YES\n"
	"\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler:  \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"         Shared Fortran Library: YES\n"
	"         Static Fortran Library: YES\n"
	"\n"
	"                            C++: ON\n"
	"                   C++ Compiler: /data/data/com.termux/files/usr/bin/c++ 6.0.0\n"
	"                      C++ Flags: \n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: YES\n"
	"             Static C++ Library: YES\n"
	"\n"
	"                            JAVA: OFF\n"
	"                   JAVA Compiler:  \n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: OFF\n"
	"             High-level library: ON\n"
	"                   Threadsafety: OFF\n"
	"            Default API mapping: v110\n"
	" With deprecated public symbols: ON\n"
	"         I/O filters (external): \n"
	"                            MPE: \n"
	"                     Direct VFD: \n"
	"                        dmalloc: \n"
	" Packages w/ extra debug output: \n"
	"                    API Tracing: OFF\n"
	"           Using memory checker: OFF\n"
	"Memory allocation sanity checks: OFF\n"
	"            Metadata trace file: \n"
	"         Function Stack Tracing: OFF\n"
	"      Strict File Format Checks: OFF\n"
	"   Optimization Instrumentation: \n"
;

