TERMUX_PKG_HOMEPAGE=https://github.com/RichiH/vcsh
TERMUX_PKG_DESCRIPTION="config manager based on Git"
TERMUX_PKG_VERSION='1.20151229'
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/RichiH/vcsh/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_FOLDERNAME=vcsh-${TERMUX_PKG_VERSION}
TERMUX_PKG_BUILD_IN_SRC=yes
TERMUX_PKG_DEPENDS="git"
TERMUX_PKG_PLATFORM_INDEPENDENT=yes
TERMUX_PKG_EXTRA_MAKE_ARGS="PREFIX=$TERMUX_PREFIX all="
TERMUX_PKG_SHA256=ae069506b0490287aefa582ab4e6af1c7ebc4dca743b17d91e0c8d0327d7a3fa
