TERMUX_PKG_HOMEPAGE="https://lib.rs/cavif"
TERMUX_PKG_DESCRIPTION="Encoder/converter for AVIF images. Based on rav1e and avif-serialize."
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.3.1-win
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/kornelski/cavif-rs/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0f76ae20081d2031881d51871dd5b66cf5c0bec441a22c605f5bbba7dc55c8a8
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
