TERMUX_PKG_HOMEPAGE="https://github.com/alex-sector/dns2tcp"
TERMUX_PKG_DESCRIPTION="dns2tcp is a tool for relaying TCP connections over DNS"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Marlin Sööse <marlin.soose@laro.se>"
TERMUX_PKG_VERSION=0.5.2
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/alex-sector/dns2tcp/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=4f6e0ed0f5a1aa079a4d377c6d2b16da8ddcffae7d1ddad1280c3e209ada410c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC="true"
