TERMUX_PKG_HOMEPAGE="https://github.com/haskell/primitive"
TERMUX_PKG_DESCRIPTION="Primitive memory-related operations"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.7.3.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/primitive-${TERMUX_PKG_VERSION}/primitive-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="3c0cfda67f1ee6f7f65108ad6f973b5bbb35ddba34b3c87746a7448f787501dc"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
