TERMUX_PKG_HOMEPAGE="https://github.com/haskell/primitive"
TERMUX_PKG_DESCRIPTION="Primitive memory-related operations"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.7.4.0
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/primitive-${TERMUX_PKG_VERSION}/primitive-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=5b2d6dc2812eb2f6a115f05fcbe3e723d3aeff7894b012c617e075130581add5
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
