TERMUX_SUBPKG_INCLUDE="lib/xorg/protocol.txt"
TERMUX_SUBPKG_DESCRIPTION="X.Org protocol.txt file"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_REPLACES="xorg-server-xvfb (<< 1.20.11-8)"
TERMUX_SUBPKG_BREAKS="xorg-server-xvfb (<< 1.20.11-8)"
