TERMUX_PKG_HOMEPAGE="https://github.com/haskell/HTTP"
TERMUX_PKG_DESCRIPTION="A library for client-side HTTP"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=4000.4.1
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/HTTP-${TERMUX_PKG_VERSION}/HTTP-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=df31d8efec775124dab856d7177ddcba31be9f9e0836ebdab03d94392f2dd453
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-network-uri, haskell-network"
