TERMUX_PKG_HOMEPAGE=https://pngquant.org
TERMUX_PKG_DESCRIPTION="PNG image optimising utility"
TERMUX_PKG_VERSION=2.11.4
TERMUX_PKG_SRCURL=https://github.com/pornel/pngquant/archive/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=c45816daccf63e0910fdd31033f489fd153603082eea5ce7f28f62c000384446
TERMUX_PKG_DEPENDS="libpng"
TERMUX_PKG_MAINTAINER="Vishal Biswas @vishalbiswas"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--disable-sse"

termux_step_post_extract_package () {
	local LIBIMAGEQUANT_SRC_FOLDER=libimagequant-$TERMUX_PKG_VERSION
	termux_download \
		https://github.com/ImageOptim/libimagequant/archive/$TERMUX_PKG_VERSION.tar.gz \
		$TERMUX_PKG_CACHEDIR/$LIBIMAGEQUANT_SRC_FOLDER.tar.gz \
		a6b7552cc6161c8092638e9d5c889b4344264ca5d0d12211fafdcb03b93bc943

	tar -xf $TERMUX_PKG_CACHEDIR/$LIBIMAGEQUANT_SRC_FOLDER.tar.gz -C $TERMUX_PKG_SRCDIR
	rmdir $TERMUX_PKG_SRCDIR/lib
	mv $TERMUX_PKG_SRCDIR/$LIBIMAGEQUANT_SRC_FOLDER $TERMUX_PKG_SRCDIR/lib
}
