TERMUX_PKG_HOMEPAGE=
TERMUX_PKG_DESCRIPTION="Image editing and resizing (PNG)"
TERMUX_PKG_VERSION=
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=
TERMUX_PKG_DEPENDS="libpng"
TERMUX_PKG_RM_AFTER_INSTALL="bin/pngquant"
