TERMUX_PKG_HOMEPAGE=https://unqlite.org/
TERMUX_PKG_DESCRIPTION="Transactional embedded database engine"
TERMUX_PKG_LICENSE="BSD 2-Clause, Sleepycat"
TERMUX_PKG_LICENSE_FILE="LICENSE, src/jx9_license.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.2.1
TERMUX_PKG_SRCURL=https://github.com/symisc/unqlite/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=3cd5f638cdea014af4879d9ba4f088c92f5cf885051c5ced3dde1ef8a62fac9c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_NO_STATICSPLIT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
