diff -uNr fio-fio-3.37/Makefile fio-fio-3.37.mod/Makefile
--- fio-fio-3.37/Makefile	2024-03-27 05:13:51.000000000 +0800
+++ fio-fio-3.37.mod/Makefile	2024-07-18 11:55:40.302184569 +0800
@@ -325,6 +325,7 @@
 	@$(SHELL) $(SRCDIR)/FIO-VERSION-GEN
 -include FIO-VERSION-FILE
 
+FIO_VERSION = fio-@VERSION@
 override CFLAGS := -DFIO_VERSION='"$(FIO_VERSION)"' $(FIO_CFLAGS) $(CFLAGS)
 
 $(foreach eng,$(ENGINES),$(eval $(call engine_template,$(eng))))
