#!/data/data/com.termux/files/usr/bin/sh
set -e
PREFIX="/data/data/com.termux/files/usr"

gtk-query-immodules-2.0 --update-cache || true
for i in $(find "${PREFIX}/share/icons" -type f -iname index.theme); do
    gtk-update-icon-cache --force --quiet $(dirname "${i}") || true
done
unset i

## Usually, glib and gdk-pixbuf should have own triggers
## but in Termux they don't have.
glib-compile-schemas "${PREFIX}/share/glib-2.0/schemas" || true
gdk-pixbuf-query-loaders --update-cache || true

if [ "${1}" = "triggered" ]; then
    exit 0
fi
