TERMUX_PKG_HOMEPAGE="https://xorg.freedesktop.org/"
TERMUX_PKG_DESCRIPTION="Primitive command line interface to RandR extension"
TERMUX_PKG_LICENSE="HPND"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.4"
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/xrandr-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=2cafccb2aaf2491a4068676117a0d4f90ab307724b96fffc54cd1da953779400
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libx11, libxrandr"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros, xorgproto"
