TERMUX_PKG_HOMEPAGE=https://swig.org
TERMUX_PKG_DESCRIPTION="Generate scripting interfaces to C/C++ code"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_LICENSE_FILE="LICENSE, LICENSE-GPL, LICENSE-UNIVERSITIES, COPYRIGHT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.4.0"
TERMUX_PKG_SRCURL=https://downloads.sourceforge.net/swig/swig-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=c3f8e5dcd68c18aa19847b33b0a1bb92f07e904c53ae9cf5ae4ff8727a72927e
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, pcre2, zlib"
# fatal error: 'pcre2.h' file not found
TERMUX_PKG_BUILD_DEPENDS="pcre2"
TERMUX_PKG_BUILD_IN_SRC=true
