TERMUX_PKG_HOMEPAGE=https://www.tcsh.org
TERMUX_PKG_DESCRIPTION="TENEX C Shell, an enhanced version of Berkeley csh"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=6.24.04
TERMUX_PKG_SRCURL=https://github.com/tcsh-org/tcsh/archive/TCSH${TERMUX_PKG_VERSION//./_}.tar.gz
TERMUX_PKG_SHA256=e34f6c2422c76b42c2695c0bbdd8f7b106ec5c726c99a6beaf9faa992aecb4e6
TERMUX_PKG_BUILD_DEPENDS="libcrypt, ncurses"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--enable-nls --disable-nls-catalogs"
