TERMUX_SUBPKG_INCLUDE="
bin/toe
bin/tput
bin/clear
bin/tset
bin/tabs
bin/infocmp
bin/reset
bin/tic
share/man/man1/toe.1.gz
share/man/man1/tput.1.gz
share/man/man1/clear.1.gz
share/man/man1/tset.1.gz
share/man/man1/tabs.1.gz
share/man/man1/infocmp.1.gz
share/man/man1/reset.1.gz
share/man/man1/tic.1.gz
"
TERMUX_SUBPKG_DESCRIPTION="Tools for working with terminals"
