TERMUX_PKG_HOMEPAGE=https://github.com/AngelJumbo/sssnake
TERMUX_PKG_DESCRIPTION="cli snake game that plays itself"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.3.2
TERMUX_PKG_SRCURL=https://github.com/AngelJumbo/sssnake/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ffd5f012ed664d4d72df03af858c8984c60985ef680b760bb3f37d4948f2a3c0
TERMUX_PKG_DEPENDS="ncurses"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_GROUPS="games"
