TERMUX_SUBPKG_DESCRIPTION="Platform-independent data for tvheadend"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_INCLUDE="share/tvheadend/"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_BREAKS="tvheadend (<< 4.2.8-9)"
TERMUX_SUBPKG_REPLACES="tvheadend (<< 4.2.8-9)"
