#!/data/data/com.termux/files/usr/bin/sh

if [ ! -e "/data/data/com.termux/files/usr/lib/fonts" ]; then
    if [ -d "/system/fonts" ]; then
        ln -sf /system/fonts /data/data/com.termux/files/usr/lib/fonts
    fi
fi
