TERMUX_SUBPKG_DESCRIPTION="Classes for QML and JavaScript languages"
TERMUX_SUBPKG_DEPENDS="qt5-base"
TERMUX_SUBPKG_BREAKS="qt5-declarative-dev"
TERMUX_SUBPKG_REPLACES="qt5-declarative-dev"

TERMUX_SUBPKG_INCLUDE="
bin/qml
bin/qmlcachegen
bin/qmleasing
bin/qmlimportscanner
bin/qmllint
bin/qmlmin
bin/qmlplugindump
bin/qmlprofiler
bin/qmlscene
bin/qmltestrunner
include/qt/QtPacketProtocol
include/qt/QtQml
include/qt/QtQmlDebug
include/qt/QtQuick
include/qt/QtQuickParticles
include/qt/QtQuickTest
include/qt/QtQuickWidgets
lib/cmake/Qt5Qml
lib/cmake/Qt5Quick
lib/cmake/Qt5QuickCompiler
lib/cmake/Qt5QuickTest
lib/cmake/Qt5QuickWidgets
lib/libQt5PacketProtocol.a
lib/libQt5PacketProtocol.prl
lib/libQt5Qml.prl
lib/libQt5Qml.so
lib/libQt5Qml.so.*
lib/libQt5QmlDebug.a
lib/libQt5QmlDebug.prl
lib/libQt5QmlDevTools.a
lib/libQt5QmlDevTools.prl
lib/libQt5Quick.prl
lib/libQt5Quick.so
lib/libQt5Quick.so.*
lib/libQt5QuickParticles.prl
lib/libQt5QuickParticles.so
lib/libQt5QuickParticles.so.*
lib/libQt5QuickTest.prl
lib/libQt5QuickTest.so
lib/libQt5QuickTest.so.*
lib/libQt5QuickWidgets.prl
lib/libQt5QuickWidgets.so
lib/libQt5QuickWidgets.so.*
lib/pkgconfig/Qt5Qml.pc
lib/pkgconfig/Qt5Quick.pc
lib/pkgconfig/Qt5QuickTest.pc
lib/pkgconfig/Qt5QuickWidgets.pc
lib/qt/mkspecs/features/qmlcache.prf
lib/qt/mkspecs/features/qtquickcompiler.prf
lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri
lib/qt/mkspecs/modules/qt_lib_qml.pri
lib/qt/mkspecs/modules/qt_lib_qml_private.pri
lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri
lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri
lib/qt/mkspecs/modules/qt_lib_qmltest.pri
lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri
lib/qt/mkspecs/modules/qt_lib_quick.pri
lib/qt/mkspecs/modules/qt_lib_quick_private.pri
lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri
lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri
lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri
lib/qt/qml
libexec/qt/qmltooling
"
