TERMUX_SUBPKG_INCLUDE="
lib/libQt5PacketProtocol.a
lib/libQt5Qml.so
lib/libQt5Qml.so.5
lib/libQt5Qml.so.5.11
lib/libQt5Qml.so.5.11.2
lib/libQt5QmlDebug.a
lib/libQt5QmlDevTools.a
lib/libQt5Quick.so
lib/libQt5Quick.so.5
lib/libQt5Quick.so.5.11
lib/libQt5Quick.so.5.11.2
lib/libQt5QuickParticles.so
lib/libQt5QuickParticles.so.5
lib/libQt5QuickParticles.so.5.11
lib/libQt5QuickParticles.so.5.11.2
lib/libQt5QuickTest.so
lib/libQt5QuickTest.so.5
lib/libQt5QuickTest.so.5.11
lib/libQt5QuickTest.so.5.11.2
lib/libQt5QuickWidgets.so
lib/libQt5QuickWidgets.so.5
lib/libQt5QuickWidgets.so.5.11
lib/libQt5QuickWidgets.so.5.11.2
libexec/qt/qmltooling
lib/qt/qml
"

TERMUX_SUBPKG_DEPENDS="qt5-base"
TERMUX_SUBPKG_DESCRIPTION="Classes for QML and JavaScript languages"
