TERMUX_SUBPKG_INCLUDE="share/help/"
TERMUX_SUBPKG_DESCRIPTION="Gnumeric help files"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_BREAKS="gnumeric (<< 1.12.53)"
TERMUX_SUBPKG_REPLACES="gnumeric (<< 1.12.53)"
