TERMUX_PKG_HOMEPAGE=https://sourceforge.net/projects/opencore-amr
TERMUX_PKG_DESCRIPTION="Open source implementation of the Adaptive Multi Rate (AMR) speech codec"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="William Goodspeed @goodspeed34"
TERMUX_PKG_VERSION=0.1.6
TERMUX_PKG_SRCURL=https://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-${TERMUX_PKG_VERSION}.tar.gz/download
TERMUX_PKG_SHA256=483eb4061088e2b34b358e47540b5d495a96cd468e361050fae615b1809dc4a1
TERMUX_PKG_BREAKS="libopencore-amr-dev"
TERMUX_PKG_REPLACES="libopencore-amr-dev"
