TERMUX_PKG_HOMEPAGE=https://icculus.org/physfs/
TERMUX_PKG_DESCRIPTION="A portable, flexible file i/o abstraction"
TERMUX_PKG_LICENSE="ZLIB"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.2.0
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://github.com/icculus/physfs/archive/refs/tags/release-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=1991500eaeb8d5325e3a8361847ff3bf8e03ec89252b7915e1f25b3f8ab5d560
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DPHYSFS_BUILD_STATIC=OFF
-DPHYSFS_BUILD_TEST=OFF
"
