TERMUX_SUBPKG_DESCRIPTION="Platform-independent data for lyx"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_INCLUDE="share/lyx/"
TERMUX_SUBPKG_BREAKS="lyx (<< 2.3.7)"
TERMUX_SUBPKG_REPLACES="lyx (<< 2.3.7)"
