TERMUX_PKG_HOMEPAGE=https://icecast.org/
TERMUX_PKG_DESCRIPTION="Library which can be used to write a source client like ices."
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.4.6
TERMUX_PKG_SRCURL=https://downloads.xiph.org/releases/libshout/libshout-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=39cbd4f0efdfddc9755d88217e47f8f2d7108fa767f9d58a2ba26a16d8f7c910
TERMUX_PKG_DEPENDS="libogg, libvorbis, libxml2, openssl"
TERMUX_PKG_BUILD_IN_SRC=true
