TERMUX_PKG_HOMEPAGE=https://github.com/mapbox/protozero
TERMUX_PKG_DESCRIPTION="Minimalistic protocol buffer decoder and encoder in C++"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE.md"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.7.0
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/mapbox/protozero/archive/v${TERMUX_PKG_VERSION}.zip
TERMUX_PKG_SHA256=b1dc381cdf75bc6531f1fee13c76a72bae432660984b3316f104c74c355766fd
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DPYBIND11_FINDPYTHON=OFF"
