TERMUX_PKG_HOMEPAGE=https://github.com/mapbox/protozero
TERMUX_PKG_DESCRIPTION="Minimalistic protocol buffer decoder and encoder in C++"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE.md"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.8.0
TERMUX_PKG_SRCURL=https://github.com/mapbox/protozero/archive/v${TERMUX_PKG_VERSION}.zip
TERMUX_PKG_SHA256=1f9616bbe55e8cd8dac93f37f0573a2e8eed5fb419632cd8057630f800f41c0b
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DPYBIND11_FINDPYTHON=OFF"
