TERMUX_PKG_HOMEPAGE=https://github.com/seccomp/libseccomp
TERMUX_PKG_DESCRIPTION="Enhanced seccomp library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"
TERMUX_PKG_VERSION=2.4.2
TERMUX_PKG_SRCURL=https://github.com/seccomp/libseccomp/releases/download/v${TERMUX_PKG_VERSION}/libseccomp-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=b54f27b53884caacc932e75e6b44304ac83586e2abe7a83eca6daecc5440585b
TERMUX_PKG_BREAKS="libseccomp-dev"
TERMUX_PKG_REPLACES="libseccomp-dev"
