TERMUX_PKG_HOMEPAGE=https://github.com/seccomp/libseccomp
TERMUX_PKG_DESCRIPTION="Enhanced seccomp library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"
TERMUX_PKG_VERSION=2.4.3
TERMUX_PKG_SRCURL=https://github.com/seccomp/libseccomp/releases/download/v${TERMUX_PKG_VERSION}/libseccomp-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=cf15d1421997fac45b936515af61d209c4fd788af11005d212b3d0fd71e7991d
TERMUX_PKG_BREAKS="libseccomp-dev"
TERMUX_PKG_REPLACES="libseccomp-dev"
