TERMUX_PKG_HOMEPAGE=https://maturin.rs/
TERMUX_PKG_DESCRIPTION="Build and publish Rust crates (pyo3, cffi, uniffi bindings) as Python packages"
TERMUX_PKG_LICENSE="Apache-2.0, MIT"
TERMUX_PKG_MAINTAINER="Gouranga Das Samrat <gouranga.das.khulna@gmail.com>"
TERMUX_PKG_VERSION="1.15.0"
TERMUX_PKG_SRCURL="https://github.com/PyO3/maturin/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=623111bddb2d7f6f4ba2e64038f91f8b673bd6f95dd6fcbaf334b7af7789b48d
TERMUX_PKG_DEPENDS="python, rust"
TERMUX_PKG_RECOMMENDS="python-pip"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_pre_configure() {
	termux_setup_rust

	export _CARGO_FEATURES="cli-completion,scaffolding,upload,sbom,rustls"
}

termux_step_make() {
	cargo build \
		--jobs "${TERMUX_PKG_MAKE_PROCESSES}" \
		--target "${CARGO_TARGET_NAME}" \
		--release \
		--no-default-features \
		--features "${_CARGO_FEATURES}"
}

termux_step_make_install() {
	install -Dm700 -t "${TERMUX_PREFIX}/bin" \
		"target/${CARGO_TARGET_NAME}/release/maturin"
}

termux_step_post_make_install() {
	# Shell completions, generated by a host build of maturin.
	mkdir -p "${TERMUX_PREFIX}/share/bash-completion/completions"
	mkdir -p "${TERMUX_PREFIX}/share/elvish/lib"
	mkdir -p "${TERMUX_PREFIX}/share/fish/vendor_completions.d"
	mkdir -p "${TERMUX_PREFIX}/share/zsh/site-functions"
	(
		unset CC CXX CFLAGS CXXFLAGS CPPFLAGS LDFLAGS AR AS CPP LD RANLIB READELF STRIP
		cargo run --no-default-features --features "${_CARGO_FEATURES}" -- completions bash > "${TERMUX_PREFIX}/share/bash-completion/completions/${TERMUX_PKG_NAME}"
		cargo run --no-default-features --features "${_CARGO_FEATURES}" -- completions elvish > "${TERMUX_PREFIX}/share/elvish/lib/${TERMUX_PKG_NAME}.elv"
		cargo run --no-default-features --features "${_CARGO_FEATURES}" -- completions fish > "${TERMUX_PREFIX}/share/fish/vendor_completions.d/${TERMUX_PKG_NAME}.fish"
		cargo run --no-default-features --features "${_CARGO_FEATURES}" -- completions zsh > "${TERMUX_PREFIX}/share/zsh/site-functions/_${TERMUX_PKG_NAME}"
	)
}
