TERMUX_SUBPKG_INCLUDE="share/help/"
TERMUX_SUBPKG_DESCRIPTION="Evince help files"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_BREAKS="evince (<< 44.3)"
TERMUX_SUBPKG_REPLACES="evince (<< 44.3)"
