TERMUX_PKG_HOMEPAGE=https://www.netfilter.org/projects/libmnl/
TERMUX_PKG_DESCRIPTION="a minimalistic user-space library oriented to Netlink developers"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.0.5
TERMUX_PKG_REVISION=0
TERMUX_PKG_SRCURL=https://netfilter.org/projects/libmnl/files/libmnl-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=274b9b919ef3152bfb3da3a13c950dd60d6e2bcd54230ffeca298d03b40d0525
TERMUX_PKG_BREAKS="libmnl-dev"
TERMUX_PKG_REPLACES="libmnl-dev"
