diff -u -r ../checkinstall-1.6.2/Makefile ./Makefile
--- ../checkinstall-1.6.2/Makefile	2008-11-11 21:43:53.000000000 -0500
+++ ./Makefile	2016-10-28 16:14:22.403691119 -0400
@@ -1,7 +1,7 @@
 # $Id: Makefile,v 1.6.2.1 2008/11/09 07:48:18 izto Exp $
 
 # Where to install.
-PREFIX=/usr/local
+PREFIX?=/usr/local
 BINDIR=$(PREFIX)/sbin
 LCDIR=$(PREFIX)/lib/checkinstall/locale
 CONFDIR=$(PREFIX)/lib/checkinstall
