TERMUX_PKG_HOMEPAGE=https://github.com/folkertvanheusden/HTTPing
TERMUX_PKG_DESCRIPTION="ping-like program for http-requests"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.6"
TERMUX_PKG_SRCURL=https://github.com/folkertvanheusden/HTTPing/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=d332fc5436bcf8290bcb4fe75b7019b90facfb64264dc3c7bc3407da27c18d77
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="fftw, libandroid-support, ncurses, openssl"
