TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="X11 font encoding library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Leonid Pliushch <leonid.pliushch@gmail.com>"
TERMUX_PKG_VERSION=1.1.4
TERMUX_PKG_REVISION=20
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libfontenc-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=2cfcce810ddd48f2e5dc658d28c1808e86dcf303eaff16728b9aa3dbc0092079
TERMUX_PKG_DEPENDS="zlib"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
