TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="X11 font encoding library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.1.7
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/lib/libfontenc-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=c0d36991faee06551ddbaf5d99266e97becdc05edfae87a833c3ff7bf73cfec2
TERMUX_PKG_DEPENDS="zlib"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
