--- ./Makefile.orig	2018-01-26 00:05:41.000000000 +0300
+++ ./Makefile	2021-02-05 11:28:47.890049844 +0300
@@ -10,7 +10,6 @@
 
 # Internal flags so one can safely override CFLAGS, CPPFLAGS and LDFLAGS
 INTFLAGS = -std=c99 -I $(SRCDIR)/crypto/tc
-LIBS = -lpthread
 
 ifeq ($(OPENSSL),1)
 LIBS += -lcrypto
