TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/assoc"
TERMUX_PKG_DESCRIPTION="swap and assoc: Symmetric and Semigroupy Bifunctors"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.0.2"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/assoc-${TERMUX_PKG_VERSION}/assoc-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="d8988dc6e8718c7a3456515b769c9336aeeec730cf86fc5175247969ff8f144f"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-tagged, haskell-bifunctors"
