TERMUX_PKG_HOMEPAGE=https://github.com/AyatanaIndicators/libayatana-indicator
TERMUX_PKG_DESCRIPTION="Ayatana Indicators Shared Library"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.9.4"
TERMUX_PKG_SRCURL=https://github.com/AyatanaIndicators/libayatana-indicator/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a18d3c682e29afd77db24366f8475b26bda22b0e16ff569a2ec71cd6eb4eac95
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="ayatana-ido, gdk-pixbuf, glib, gtk3"
