# Config file taken from the official Quick Start docs:
# https://git.deuxfleurs.fr/Deuxfleurs/garage/src/commit/582b168b6a985108c68aca45effae1d73203d6c3/doc/book/quick-start/_index.md?display=source#L65-L91

metadata_dir = "@TERMUX_PREFIX@/var/lib/garage/meta"
data_dir = "@TERMUX_PREFIX@/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "@GARAGE_RPC_SECRET@"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "@GARAGE_ADMIN_TOKEN@"
metrics_token = "@GARAGE_METRICS_TOKEN@"
