TERMUX_PKG_HOMEPAGE=https://mate-desktop.org/
TERMUX_PKG_DESCRIPTION="Set of backgrounds packaged with the MATE desktop"
TERMUX_PKG_LICENSE="GPL-2.0-or-later"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.28.0"
TERMUX_PKG_SRCURL="https://github.com/mate-desktop/mate-backgrounds/releases/download/v$TERMUX_PKG_VERSION/mate-backgrounds-$TERMUX_PKG_VERSION.tar.xz"
TERMUX_PKG_SHA256=50d1afd02486bd07ac22a5a6b6efa3031148f0d48a82e488d909ad57003a6943
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="mate-common"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
