TERMUX_PKG_HOMEPAGE=https://gitlab.com/jallbrit/cbonsai
TERMUX_PKG_DESCRIPTION="Grow bonsai trees in your terminal"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.4.2"
TERMUX_PKG_SRCURL=https://gitlab.com/jallbrit/cbonsai/-/archive/v${TERMUX_PKG_VERSION}/cbonsai-v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=75cf844940e5ef825a74f2d5b1551fe81883551b600fecd00748c6aa325f5ab0
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="ncurses, ncurses-ui-libs"
TERMUX_PKG_BUILD_IN_SRC=true
