TERMUX_PKG_HOMEPAGE=https://github.com/yhirose/cpp-httplib
TERMUX_PKG_DESCRIPTION="C++ HTTP/HTTPS server and client library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.14.1"
TERMUX_PKG_SRCURL="https://github.com/yhirose/cpp-httplib/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=2d4fb5544da643e5d0a82585555d8b7502b4137eb321a4abbb075e21d2f00e96
TERMUX_PKG_DEPENDS="brotli, libc++, openssl, zlib"
TERMUX_PKG_BUILD_DEPENDS="python"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DHTTPLIB_COMPILE=ON
-DBUILD_SHARED_LIBS=ON
"
