TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/guile/
TERMUX_PKG_DESCRIPTION="Guile is the official extension language of the GNU system."
TERMUX_PKG_LICENSE="LGPL-3.0 or later"
TERMUX_PKG_VERSION=2.2.4
TERMUX_PKG_REVISION=1
TERMUX_PKG_SHA256=33b904c0bf4e48e156f3fb1d0e6b0392033bd610c6c9d9a0410c6e0ea96a3e5c
TERMUX_PKG_SRCURL=https://ftp.gnu.org/gnu/guile/guile-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_DEPENDS="libffi libunistring libtool libgc libgmp"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS=""
