TERMUX_PKG_HOMEPAGE=https://www.blosc.org
TERMUX_PKG_DESCRIPTION="A blocking, shuffling and loss-less compression library"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_LICENSE_FILE="\
LICENSES/BITSHUFFLE.txt
LICENSES/FASTLZ.txt
LICENSES/LZ4.txt
LICENSES/ZLIB.txt
LICENSES/ZSTD.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.2.1"
TERMUX_PKG_SRCURL=https://github.com/Blosc/c-blosc2/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=945cc68d47ba2817279b5d64c0f9b5edce6849a52ac1a46ba8c3ecaedce35769
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="liblz4, zlib, zstd"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_STATIC=OFF
-DCMAKE_INSTALL_LIBDIR=$TERMUX__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$TERMUX__PREFIX__INCLUDE_SUBDIR
-DDEACTIVATE_LZ4=OFF
-DDEACTIVATE_ZLIB=OFF
-DDEACTIVATE_ZSTD=OFF
-DPREFER_EXTERNAL_LZ4=ON
-DPREFER_EXTERNAL_ZLIB=ON
-DPREFER_EXTERNAL_ZSTD=ON
"
