TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/tagged"
TERMUX_PKG_DESCRIPTION="Haskell 98 phantom types to avoid unsafely passing dummy arguments"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.8.6.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/tagged-${TERMUX_PKG_VERSION}/tagged-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="f5e0fcf95f0bb4aa63f428f2c01955a41ea1a42cfcf39145ed631f59a9616c02"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
