#!/data/data/com.termux/files/usr/bin/sh
set -e
PREFIX="/data/data/com.termux/files/usr"

if [ -d "${PREFIX}/lib/gtk-2.0/2.10.0" ]; then
    rm -f "${PREFIX}/lib/gtk-2.0/2.10.0/immodules.cache"
    rmdir -p --ignore-fail-on-non-empty "${PREFIX}/lib/gtk-2.0/2.10.0"
fi
