TERMUX_PKG_HOMEPAGE=https://github.com/Microsoft/GSL
TERMUX_PKG_DESCRIPTION="Guidelines Support Library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="5.0.0"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL="https://github.com/microsoft/GSL/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=e646da6ac00a885cfae33dc935e52bb42bd1d05e41b8437cbc25ca3d74930f35
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="googletest"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DGSL_CXX_STANDARD=23
"
