TERMUX_PKG_HOMEPAGE=https://github.com/Microsoft/GSL
TERMUX_PKG_DESCRIPTION="Guidelines Support Library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.2.1"
TERMUX_PKG_SRCURL="https://github.com/microsoft/GSL/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=d959f1cb8bbb9c94f033ae5db60eaf5f416be1baa744493c32585adca066fe1f
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="googletest"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DGSL_CXX_STANDARD=23
"
