#!/data/data/com.termux/files/usr/bin/sh
set -e
PREFIX="/data/data/com.termux/files/usr"

if [ "${1}" = "triggered" ]; then
	if [ -x "${PREFIX}/bin/update-mime-database" ]; then
		update-mime-database "${PREFIX}/share/mime"
	fi
	exit 0
fi

if [ -x "${PREFIX}/bin/update-mime-database" ]; then
	update-mime-database "${PREFIX}/share/mime"
fi
