TERMUX_PKG_HOMEPAGE=http://www.vorbis.com/
TERMUX_PKG_DESCRIPTION="Library for using the Ogg Vorbis compressed audio format"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_VERSION=1.3.6
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=http://downloads.xiph.org/releases/vorbis/libvorbis-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=af00bb5a784e7c9e69f56823de4637c350643deedaf333d0fa86ecdba6fcb415
TERMUX_PKG_DEPENDS="libogg"
TERMUX_PKG_BREAKS="libvorbis-dev"
TERMUX_PKG_REPLACES="libvorbis-dev"
