TERMUX_PKG_HOMEPAGE="https://bindfs.org/"
TERMUX_PKG_DESCRIPTION="A FUSE filesystem for mirroring a directory to another directory."
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.17.4
TERMUX_PKG_SRCURL="https://bindfs.org/downloads/bindfs-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=6fd4af9ba2ec2bdb603ef8eea2a9d12db2e5fe9cbe52b8640b415734a59f3dcc
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libfuse2"
