TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/zlib"
TERMUX_PKG_DESCRIPTION="Compression and decompression in the gzip and zlib formats"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.6.3.0
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/zlib-${TERMUX_PKG_VERSION}/zlib-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=9eaa989ad4534438b5beb51c1d3a4c8f6a088fdff0b259a5394fbf39aaee04da
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
