TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/zlib"
TERMUX_PKG_DESCRIPTION="Compression and decompression in the gzip and zlib formats"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.6.2.3"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/zlib-${TERMUX_PKG_VERSION}/zlib-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="807f6bddf9cb3c517ce5757d991dde3c7e319953a22c86ee03d74534bd5abc88"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
