TERMUX_PKG_HOMEPAGE=https://www.freedesktop.org/wiki/Software/libspectre/
TERMUX_PKG_DESCRIPTION="A small library for rendering Postscript documents"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.2.9
TERMUX_PKG_SRCURL=https://libspectre.freedesktop.org/releases/libspectre-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=49ae9c52b5af81b405455c19fe24089d701761da2c45d22164a99576ceedfbed
TERMUX_PKG_DEPENDS="ghostscript"
TERMUX_PKG_BUILD_IN_SRC=true
