TERMUX_PKG_HOMEPAGE=https://panotools.sourceforge.net/
TERMUX_PKG_DESCRIPTION="Part of the Panorama Tools by Helmut Dersch"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.9.23"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://downloads.sourceforge.net/panotools/libpano13-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=e7c076d37a14c39434962115e47ddbe18452ca3de5ce40e2aaefa7cf5815ea28
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libjpeg-turbo, libpng, libtiff, zlib"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$TERMUX__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$TERMUX__PREFIX__INCLUDE_SUBDIR
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
