TERMUX_PKG_HOMEPAGE=https://panotools.sourceforge.net/
TERMUX_PKG_DESCRIPTION="Part of the Panorama Tools by Helmut Dersch"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.9.22"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://downloads.sourceforge.net/panotools/libpano13-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=affc6830cdbe71c28d2731dcbf8dea2acda6d9ffd4609c6dbf3ba0c68440a8e3
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libjpeg-turbo, libpng, libtiff, zlib"
