TERMUX_PKG_HOMEPAGE=https://github.com/seccomp/libseccomp
TERMUX_PKG_DESCRIPTION="Enhanced seccomp library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.5.5"
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://github.com/seccomp/libseccomp/releases/download/v${TERMUX_PKG_VERSION}/libseccomp-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=248a2c8a4d9b9858aa6baf52712c34afefcf9c9e94b76dce02c1c9aa25fb3375
TERMUX_PKG_BREAKS="libseccomp-dev"
TERMUX_PKG_REPLACES="libseccomp-dev"
