TERMUX_SUBPKG_DESCRIPTION="EGL header files"
TERMUX_SUBPKG_DEPEND_ON_PARENT=no
TERMUX_SUBPKG_BREAKS="ndk-sysroot (<< 25b-3)"
TERMUX_SUBPKG_REPLACES="ndk-sysroot (<< 25b-3)"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_INCLUDE="
include/EGL
"
