TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="X server resource database utility"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="COPYING"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.2.3
TERMUX_PKG_SRCURL=https://www.x.org/archive/individual/app/xrdb-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=c88f560243278c896ce4fc92ae5a45a2b505a316ffa427fe55b02e5d5914c4e4
TERMUX_PKG_DEPENDS="libx11, libxmu"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--with-cpp=/usr/bin/cpp"
