TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/base-compat"
TERMUX_PKG_DESCRIPTION="A compatibility layer for base"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.12.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base-compat-${TERMUX_PKG_VERSION}/base-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="fb683cb4041b88cab1d0849f70ebd26b342c734a9ef6f75233c1602d53a015fd"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
