TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/base-compat"
TERMUX_PKG_DESCRIPTION="A compatibility layer for base"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.12.2
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base-compat-${TERMUX_PKG_VERSION}/base-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=a62adc883a5ac436f80e4ae02c3c56111cf1007492f267c291139a668d2150bd
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
