TERMUX_PKG_HOMEPAGE=https://github.com/FedoraQt/adwaita-qt
TERMUX_PKG_DESCRIPTION="A style to bend Qt applications to look like they belong into GNOME Shell"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
TERMUX_PKG_VERSION=1.4.1
TERMUX_PKG_SRCURL="https://github.com/FedoraQt/adwaita-qt/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=834f2caaf031306b63b31ad6fec489482feda35e9aa260f205cbb976cde97b1d
TERMUX_PKG_DEPENDS="qt5-qtbase, qt5-qtx11extras, qt5-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
