TERMUX_PKG_HOMEPAGE=https://docs.xfce.org/apps/xfce4-taskmanager/start
TERMUX_PKG_DESCRIPTION="Easy to use task manager"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
_MAJOR_VERSION=1.5
TERMUX_PKG_VERSION=${_MAJOR_VERSION}.4
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/apps/xfce4-taskmanager/${_MAJOR_VERSION}/xfce4-taskmanager-$TERMUX_PKG_VERSION.tar.bz2
TERMUX_PKG_SHA256=25b13e890d14ce453ece19eb6201b4a9a4f3e3b324b947db9047ce79cc3ae62a
TERMUX_PKG_DEPENDS="gdk-pixbuf, glib, gtk3, libcairo, libwnck, libx11, libxfce4ui, libxfce4util, libxmu, xfconf"
