TERMUX_PKG_HOMEPAGE=https://github.com/KhronosGroup/OpenCL-CLHPP
TERMUX_PKG_DESCRIPTION="Khronos OpenCL C++ Headers"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2024.05.08"
TERMUX_PKG_SRCURL=https://github.com/KhronosGroup/OpenCL-CLHPP/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=22921fd23ca72a21ac5592861d64e7ea53cd8a705fccd73905911f8489519a0b
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="opencl-headers"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTS=OFF
"
