TERMUX_PKG_HOMEPAGE=https://mosquitto.org/
TERMUX_PKG_DESCRIPTION="MQTT library"
TERMUX_PKG_LICENSE="EPL-1.0"
TERMUX_PKG_MAINTAINER="Nathaniel Wesley Filardo @nwf"
TERMUX_PKG_VERSION=2.0.11
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://mosquitto.org/files/source/mosquitto-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=7b36a7198bce85cf31b132f5c6ee36dcf5dadf86fb768501eb1e11ce95d4f78a
TERMUX_PKG_DEPENDS="c-ares, libc++, libcap, libwebsockets, openssl, json-c"
TERMUX_PKG_BREAKS="libmosquitto-dev"
TERMUX_PKG_REPLACES="libmosquitto-dev"
TERMUX_PKG_EXTRA_MAKE_ARGS="
WITH_BUNDLED_DEPS=yes
WITH_THREADING=yes
WITH_TLS_PSK=no
WITH_WEBSOCKETS=yes
WITH_SRV=yes
WITH_CJSON=yes
"
TERMUX_PKG_SERVICE_SCRIPT=("mosquitto" 'exec mosquitto 2>&1')
