TERMUX_PKG_HOMEPAGE=https://en.wikipedia.org/wiki/Cowsay
TERMUX_PKG_DESCRIPTION="Program which generates ASCII pictures of a cow with a message"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.7.0
TERMUX_PKG_SRCURL=https://github.com/cowsay-org/cowsay/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=af13a93f1559ea435403cf11eaa6c46be5bf03ac165a4acb471c66a4976167e0
TERMUX_PKG_DEPENDS="perl"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_BUILD_IN_SRC=true
