TERMUX_PKG_HOMEPAGE=https://www.gap-system.org/
TERMUX_PKG_DESCRIPTION="GAP is a system for computational discrete algebra, with particular emphasis on Computational Group Theory"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_VERSION=4.10.0
TERMUX_PKG_REVISION=1
TERMUX_PKG_SHA256=314b8d949c0bb01ef8bee199b29571d42714df660aba0d76ded254f58295904f
TERMUX_PKG_SRCURL=https://www.gap-system.org/pub/gap/gap-${TERMUX_PKG_VERSION:0:4}/tar.gz/gap-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_DEPENDS="readline, libgmp"
TERMUX_PKG_BREAKS="gap-dev"
TERMUX_PKG_REPLACES="gap-dev"
