TERMUX_PKG_HOMEPAGE=https://www.xiph.org/oggz/
TERMUX_PKG_DESCRIPTION="Command and library to inspect, tweak, edit and validate Ogg files"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.1.2"
TERMUX_PKG_SRCURL=https://downloads.xiph.org/releases/liboggz/liboggz-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=c97e4fba7954a9faf79ddcf406992c6f7bb0214e96d4957a07a2fda0265e5ab2
TERMUX_PKG_DEPENDS="libogg"
TERMUX_PKG_BREAKS="liboggz-dev"
TERMUX_PKG_REPLACES="liboggz-dev"
