--- a/Makefile	2015-12-31 19:42:10.000000000 +0000
+++ b/Makefile	2018-01-11 19:43:11.319604821 +0000
@@ -2,1 +2,1 @@
-PREFIX		= /usr/local
+PREFIX     ?= /usr/local
#@@ -13,5 +13,5 @@
#-PREFIX:=$(DESTDIR)$(PREFIX) $(MAKE) -C $(SRC) install
#+PREFIX=$(DESTDIR)$(PREFIX) $(MAKE) -C $(SRC) install
