diff --git a/Makefile b/Makefile
index fd413a0..88e2617 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ export VERSION := $(shell ./determineVersion.sh)
 #export PREFIX := /usr
 export PREFIX ?= /usr/local

-all: decpcap_test test nethogs
+all: decpcap_test nethogs

 .PHONY: tgz release check install install_lib install_dev uninstall uninstall_lib nethogs libnethogs decpcap_test test clean all
 tgz: clean
