TERMUX_PKG_HOMEPAGE=https://github.com/Doom-Utils/deutex/
TERMUX_PKG_DESCRIPTION="WAD composer for Doom, Heretic, Hexen, and Strife"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=5.1.2
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://github.com/Doom-Utils/deutex/releases/download/v$TERMUX_PKG_VERSION/deutex-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=e42edb738a11e7e6a7ed274adbe0ee6f514fd97ae61e497c8f9258a03ae143e6
TERMUX_PKG_DEPENDS="libpng, zlib"
