// vim:ft=aptconf
APT::Install-Recommends "0";
APT::Clean-Installed "0";
Dir::Cache "@TERMUX_PREFIX@/glibc/var/cache/apt";
Dir::Etc::sourcelist "@TERMUX_PREFIX@/etc/apt/glibc.sources";
Dir::Etc::sourceparts "";
Dir::State "@TERMUX_PREFIX@/glibc/var/lib/apt";
Dir::State::status "@TERMUX_PREFIX@/glibc/var/lib/dpkg/status";
DPkg::options {
"--admindir";
"@TERMUX_PREFIX@/glibc/var/lib/dpkg";
;
}

