TERMUX_PKG_HOMEPAGE=https://github.com/jarun/nnn
TERMUX_PKG_DESCRIPTION="Free, fast, friendly file browser"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=4.0
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/jarun/nnn/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a219ec8fad3dd0512aadae5840176f3265188c4c22da3b17b133bac602b40754
TERMUX_PKG_DEPENDS="debianutils, file, findutils, readline, wget, libandroid-support"
TERMUX_PKG_BUILD_IN_SRC=true
