TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/stow/
TERMUX_PKG_DESCRIPTION="Tool for managing the installation of multiple software packages into a single directory"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.4.0"
TERMUX_PKG_SRCURL=https://fossies.org/linux/misc/stow-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=6fed67cf64deab6d3d9151a43e2c06c95cdfca6a88fab7d416f46a648b1d761d
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="perl"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
