TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/stow/
TERMUX_PKG_DESCRIPTION="Tool for managing the installation of multiple software packages into a single directory"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.4.1"
TERMUX_PKG_SRCURL=https://ftp.gnu.org/gnu/stow/stow-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=2a671e75fc207303bfe86a9a7223169c7669df0a8108ebdf1a7fe8cd2b88780b
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="perl"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
