TERMUX_PKG_HOMEPAGE="https://github.com/haskell/network"
TERMUX_PKG_DESCRIPTION="Low-level networking interface"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="3.1.2.7"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/network-${TERMUX_PKG_VERSION}/network-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="7f7620fef1a1af3d3d6747f510e73223a5c600e7d7fd9ace073d1222bdc63d85"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
