TERMUX_PKG_HOMEPAGE=https://ccache.samba.org
TERMUX_PKG_DESCRIPTION="Compiler cache for fast recompilation of C/C++ code"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Vishal Biswas @vishalbiswas"
TERMUX_PKG_VERSION=3.6
TERMUX_PKG_REVISION=1
TERMUX_PKG_SHA256=a6b129576328fcefad00cb72035bc87bc98b6a76aec0f4b59bed76d67a399b1f
TERMUX_PKG_SRCURL=https://www.samba.org/ftp/ccache/ccache-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_DEPENDS="zlib"
