TERMUX_PKG_HOMEPAGE=https://docs.xfce.org/panel-plugins/xfce4-clipman-plugin/start
TERMUX_PKG_DESCRIPTION="Clipman is a clipboard manager for Xfce"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.6.2
TERMUX_PKG_REVISION=5
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/panel-plugins/xfce4-clipman-plugin/1.6/xfce4-clipman-plugin-$TERMUX_PKG_VERSION.tar.bz2
TERMUX_PKG_SHA256=ab8a5fe6f68fb1789190e498243a1d1385de3f64e984f470cbd3d1eb779399b8
TERMUX_PKG_DEPENDS="atk, gdk-pixbuf, glib, gtk3, harfbuzz, libcairo, libice, libqrencode, libsm, libx11, libxfce4ui, libxfce4util, libxtst, pango, xfce4-panel, xfconf"
