TERMUX_PKG_HOMEPAGE="https://github.com/haskell-hvr/uuid"
TERMUX_PKG_DESCRIPTION="Type definitions for Universally Unique Identifiers"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.0.5"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/uuid-types-${TERMUX_PKG_VERSION}/uuid-types-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="ad68b89b7a64c07dd5c250a11be2033ee929318ff51ec7b4e4b54e1b4deba7dd"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-random, haskell-hashable"
