TERMUX_SUBPKG_INCLUDE="$_jvm_dir/src.zip"
TERMUX_SUBPKG_DEPENDS="openjdk-9-jre-headless"
TERMUX_SUBPKG_DESCRIPTION="OpenJDK Development Kit (JDK) source files"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
