TERMUX_PKG_HOMEPAGE="https://codemadness.org/sfeed-simple-feed-parser.html"
TERMUX_PKG_DESCRIPTION="Shell-script/crontab oriented feed aggregator and parser utility (curses-based reader included)"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.7
TERMUX_PKG_SRCURL="https://codemadness.org/releases/sfeed/sfeed-$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=c5189452a2ed6d8c16ae9025b19f1eff859b01f47a85062e69737757322555ac
TERMUX_PKG_DEPENDS="ncurses"
TERMUX_PKG_RECOMMENDS="curl"
TERMUX_PKG_SUGGESTS="lynx, termux-tools"
TERMUX_PKG_BUILD_IN_SRC=true
