TERMUX_PKG_HOMEPAGE=https://www.kokkonen.net/tjko/projects.html
TERMUX_PKG_DESCRIPTION="JPEG optimizer that recompresses image files to a smaller size, without losing any information"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.4"
TERMUX_PKG_SRCURL=https://github.com/tjko/jpegoptim/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=8fc7537f722d533ea8b45966ab80c83e3342d088d5a690fdadfb05b7c9cba47f
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libjpeg-turbo"
TERMUX_PKG_BUILD_IN_SRC=true
