TERMUX_PKG_HOMEPAGE=https://www.kokkonen.net/tjko/projects.html
TERMUX_PKG_DESCRIPTION="JPEG optimizer that recompresses image files to a smaller size, without losing any information"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.1"
TERMUX_PKG_SRCURL=https://github.com/tjko/jpegoptim/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=07c71dc83802f84227b2dc2cb50fbd154b0a8a270538342163cd1a9b27def22c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libjpeg-turbo"
TERMUX_PKG_BUILD_IN_SRC=true
