TERMUX_PKG_HOMEPAGE=https://github.com/libsdl-org/SDL_image
TERMUX_PKG_DESCRIPTION="A simple library to load images of various formats as SDL surfaces (version 3)"
TERMUX_PKG_LICENSE="ZLIB"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.4.2"
TERMUX_PKG_SRCURL="https://github.com/libsdl-org/SDL_image/releases/download/release-${TERMUX_PKG_VERSION}/SDL3_image-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=82fdb88cf1a9cbdc1c77797aaa3292e6d22ce12586be718c8ea43530df1536b4
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libavif, libjpeg-turbo, libjxl, libpng, libtiff, libwebp, sdl3"

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DSDL3IMAGE_VENDORED=OFF
-DSDL3IMAGE_SAMPLES=OFF
-DSDL3IMAGE_TESTS=OFF
-DSDL3IMAGE_JPG_SHARED=OFF
-DSDL3IMAGE_PNG_SHARED=OFF
-DSDL3IMAGE_WEBP_SHARED=OFF
-DSDL3IMAGE_TIFF_SHARED=OFF
-DSDL3IMAGE_JXL_SHARED=OFF
-DSDL3IMAGE_AVIF_SHARED=OFF
"

