TERMUX_PKG_HOMEPAGE=https://github.com/lxqt/lxqt
TERMUX_PKG_DESCRIPTION="A metapackage that installs all parts of the LXQt desktop environment"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.3"
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_DEPENDS="lximage-qt, lxqt-about, lxqt-archiver, lxqt-config, lxqt-globalkeys, lxqt-notificationd, lxqt-openssh-askpass, lxqt-panel, lxqt-powermanagement, lxqt-qtplugin, lxqt-runner, lxqt-session, lxqt-themes, obconf-qt, pavucontrol-qt, pcmanfm-qt, qterminal"
TERMUX_PKG_RECOMMENDS="kvantum"
TERMUX_PKG_SUGGESTS="papirus-icon-theme"
TERMUX_PKG_METAPACKAGE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
