TERMUX_PKG_HOMEPAGE="https://www.haskell.org/cabal/"
TERMUX_PKG_DESCRIPTION="A library for working with .cabal files"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=3.8.1.0
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/Cabal-syntax-${TERMUX_PKG_VERSION}/Cabal-syntax-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=07e8ddb19fe01781485f1522b6afc22aba680b0ab28ebe6bbfb84a2dd698ce0f
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-cabal"
