TERMUX_PKG_HOMEPAGE="http://www.haskell.org/cabal/"
TERMUX_PKG_DESCRIPTION="A library for working with .cabal files"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="3.6.0.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/Cabal-syntax-${TERMUX_PKG_VERSION}/Cabal-syntax-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="ca25e5fc601397565fa857f1aa477740fac7f43d659e77c4d9b1485dca239251"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-cabal"
