TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/comonad/"
TERMUX_PKG_DESCRIPTION="Comonads"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="5.0.8"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/comonad-${TERMUX_PKG_VERSION}/comonad-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="ef6cdf2cc292cc43ee6aa96c581b235fdea8ab44a0bffb24dc79ae2b2ef33d13"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-tagged, haskell-distributive, haskell-transformers-compat, haskell-indexed-traversable"
