TERMUX_PKG_HOMEPAGE=https://dotnet.microsoft.com/en-us/
TERMUX_PKG_DESCRIPTION="A metapackage for NETStandard.Library 2.1 Targeting Pack"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@truboxl"
TERMUX_PKG_VERSION="9.0"
TERMUX_PKG_DEPENDS="netstandard-targeting-pack-2.1-9.0 | netstandard-targeting-pack-2.1-8.0"
TERMUX_PKG_ANTI_BUILD_DEPENDS="netstandard-targeting-pack-2.1-9.0, netstandard-targeting-pack-2.1-8.0"
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_METAPACKAGE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_BLACKLISTED_ARCHES="arm"
