TERMUX_PKG_HOMEPAGE=https://github.com/eja/eja
TERMUX_PKG_DESCRIPTION="eja micro web server"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="18.4.19"
TERMUX_PKG_SRCURL=https://github.com/eja/eja/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=3cccd82430d5b555d1d83f05840749be65b2763221f48fff1ed666bb063099e6
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_MAKE_ARGS="DESTDIR=${TERMUX_PREFIX} EJA_PATH=${TERMUX_PREFIX} EJA_PATH_BIN=${TERMUX_PREFIX}/bin EJA_PATH_LIB=${TERMUX_PREFIX}/lib prefix=/"
TERMUX_PKG_BUILD_IN_SRC=true
