TERMUX_PKG_HOMEPAGE="https://www.indilib.org"
TERMUX_PKG_DESCRIPTION="Astronomical instrumentation control"
TERMUX_PKG_LICENSE="GPL-2.0-or-later"
TERMUX_PKG_MAINTAINER="3ls-it <3ls-it@pm.me>"
TERMUX_PKG_VERSION="2.2.4.2"
TERMUX_PKG_SRCURL="https://github.com/indilib/indi/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=025bf3d5e4edebae86851d3a5d66ba4596a2c3a49f861f7c49d99b421dadf102
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="cfitsio, curl, fftw, gsl, iconv, libc++, libev, libjpeg-turbo, libnova, libnpth, libusb, libxisf, zlib"
