TERMUX_PKG_HOMEPAGE=https://github.com/luvit/luv
TERMUX_PKG_DESCRIPTION="Bare libuv bindings for lua"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.32.0-0"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/luvit/luv/releases/download/$TERMUX_PKG_VERSION/luv-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=25a34b2aecf02d1fd32352c855577dcecd20c756dee9eb7ebecd206bf1de26d3
TERMUX_PKG_DEPENDS="liblua53, libuv"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_MODULE=OFF
-DBUILD_SHARED_LIBS=ON
-DLUA_BUILD_TYPE=System
-DLUA_INCLUDE_DIR=$TERMUX_PREFIX/include/lua5.3
-DLUA_PACKAGE_DIR=$TERMUX_PREFIX/lib/lua/5.3
-DWITH_LUA_ENGINE=Lua
-DWITH_SHARED_LIBUV=ON
"

termux_step_pre_configure() {
	export LDFLAGS+=" -L$TERMUX_PREFIX/lib/lua/5.3"
}
