/* THIS FILE WAS GENERATED BY 'ppmdcfont' from a ppmfont file. */

#include "ppmdfont.h"

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_33[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 2 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 7 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_34[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 243 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 249 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 10, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 243 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 249 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_35[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 1, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 7, 240 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 253 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 253 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 3 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_36[26] = {
  {/* glyphCommand */ CMD_MOVEPEN, 254, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 13 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 2, 240 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 13 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 7, 247 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_37[31] = {
  {/* glyphCommand */ CMD_MOVEPEN, 9, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 252, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 5, 2 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 2 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_38[34] = {
  {/* glyphCommand */ CMD_MOVEPEN, 10, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 246, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 246, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 7 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_39[7] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 250 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_40[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 4, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 242 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 11 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 14 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_41[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 252, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 242 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 11 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 14 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_42[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 6 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 251, 253 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 3 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 5, 253 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 3 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_43[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 247, 0 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 0 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_44[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 10 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 12 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 13 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_45[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 247, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 0 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_46[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_47[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 9, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_48[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 255, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 244 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_49[4] = {
  {/* glyphCommand */ CMD_MOVEPEN, 252, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_50[14] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_51[15] = {
  {/* glyphCommand */ CMD_MOVEPEN, 251, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 5 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_52[6] = {
  {/* glyphCommand */ CMD_MOVEPEN, 3, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 2 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 3, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_53[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 5, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 5 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_54[23] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 2 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_55[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 7, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 244 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_56[29] = {
  {/* glyphCommand */ CMD_MOVEPEN, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_57[23] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_58[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 251 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 7 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_59[14] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 251 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 1, 8 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 10 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 12 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 13 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_60[3] = {
  {/* glyphCommand */ CMD_MOVEPEN, 8, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_61[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 247, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 253 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 247, 3 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 3 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_62[3] = {
  {/* glyphCommand */ CMD_MOVEPEN, 248, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_63[20] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 2 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 7 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_64[55] = {
  {/* glyphCommand */ CMD_MOVEPEN, 5, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 1 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 255, 249 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 4 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 5, 249 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 11, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 11, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 9, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 246, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 246, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 6 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 249 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 4 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_65[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 251, 2 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 2 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_66[23] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 254 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_67[18] = {
  {/* glyphCommand */ CMD_MOVEPEN, 8, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 4 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_68[15] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_69[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 254 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 9 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_70[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 254 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_71[22] = {
  {/* glyphCommand */ CMD_MOVEPEN, 8, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 1 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 3, 1 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 1 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_72[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 7, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 254 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_73[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_74[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 4, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 2 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_75[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 7, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 2 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 254, 253 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_76[3] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_77[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 248, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 248, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 8, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 8, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_78[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 7, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_79[21] = {
  {/* glyphCommand */ CMD_MOVEPEN, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_80[13] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 255 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_81[24] = {
  {/* glyphCommand */ CMD_MOVEPEN, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 1, 5 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 11 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_82[16] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 254 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_83[20] = {
  {/* glyphCommand */ CMD_MOVEPEN, 7, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_84[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 244 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_85[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 244 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_86[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 248, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 8, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_87[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 246, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 10, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_88[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 7, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_89[6] = {
  {/* glyphCommand */ CMD_MOVEPEN, 248, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 8, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 254 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_90[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 7, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 244 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 249, 9 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_91[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 253, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 254, 240 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 253, 240 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 240 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 253, 16 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_92[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 9, 16 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 247, 240 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_93[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 2, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 3, 240 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 252, 240 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 240 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 252, 16 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_94[7] = {
  {/* glyphCommand */ CMD_MOVEPEN, 248, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 2 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 248, 2 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 2 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_95[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 20, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_96[7] = {
  {/* glyphCommand */ CMD_MOVEPEN, 1, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 248 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_97[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_98[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_99[14] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_100[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_101[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_102[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 5, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 253, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 251 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_103[22] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 11 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 14 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 15 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 16 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 16 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 15 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_104[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 251, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 251, 255 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_105[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 255, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 243 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_106[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 243 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 244 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 1, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 12 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 15 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 16 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_107[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 251, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 5, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 5 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 255, 1 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_108[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_109[18] = {
  {/* glyphCommand */ CMD_MOVEPEN, 245, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 245, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 245, 255 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 248, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 255 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 8, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 10, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 11, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 11, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_110[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 251, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 251, 255 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_111[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_112[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 250, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_113[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 16 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 254 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_114[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 253, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 253, 1 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 251 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_115[17] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 6 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_116[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 253, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 251 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_117[10] = {
  {/* glyphCommand */ CMD_MOVEPEN, 251, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 5 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_118[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_119[11] = {
  {/* glyphCommand */ CMD_MOVEPEN, 248, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 8, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 4, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_120[5] = {
  {/* glyphCommand */ CMD_MOVEPEN, 251, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_121[9] = {
  {/* glyphCommand */ CMD_MOVEPEN, 250, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 13 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 252, 15 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 250, 16 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 249, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_122[8] = {
  {/* glyphCommand */ CMD_MOVEPEN, 6, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 251, 9 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 251, 251 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 251 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 251, 9 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 6, 9 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_123[39] = {
  {/* glyphCommand */ CMD_MOVEPEN, 2, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 241 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 242 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 255 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 241 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 243 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 253, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 11 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 13 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 15 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 255, 1 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 10 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 12 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 14 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 15 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_124[2] = {
  {/* glyphCommand */ CMD_MOVEPEN, 0, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_125[39] = {
  {/* glyphCommand */ CMD_MOVEPEN, 254, 240 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 241 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 242 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 244 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 246 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 249 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 255 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 0, 241 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 243 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 245 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 247 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 248 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 250 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 4 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 6 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 9 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 11 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 13 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 15 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 1, 1 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 3 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 255, 5 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 7 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 8 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 10 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 2, 12 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 14 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 15 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 254, 16 }
};

struct ppmd_glyphCommand const ppmd_standardfont_glyphTable_cmd_126[23] = {
  {/* glyphCommand */ CMD_MOVEPEN, 2, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 0, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 251 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 252 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 11, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 13, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 15, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 17, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 18, 254 }
  ,
  {/* glyphCommand */ CMD_MOVEPEN, 2, 0 }
  ,
  {/* glyphCommand */ CMD_NOOP, 0, 0 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 1, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 3, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 5, 253 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 7, 254 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 11, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 13, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 15, 2 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 17, 1 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 18, 255 }
  ,
  {/* glyphCommand */ CMD_DRAWLINE, 18, 252 }
};

struct ppmd_glyph const ppmd_standardfont_glyphTable[95] = {
  { /* glyph */
    { /* header */ 0, 0, 21}
    ,
    NULL
  }
  ,
  { /* glyph */
    { /* header */ 8, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_33
  }
  ,
  { /* glyph */
    { /* header */ 17, 253, 15}
    ,
    ppmd_standardfont_glyphTable_cmd_34
  }
  ,
  { /* glyph */
    { /* header */ 11, 246, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_35
  }
  ,
  { /* glyph */
    { /* header */ 26, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_36
  }
  ,
  { /* glyph */
    { /* header */ 31, 244, 12}
    ,
    ppmd_standardfont_glyphTable_cmd_37
  }
  ,
  { /* glyph */
    { /* header */ 34, 243, 13}
    ,
    ppmd_standardfont_glyphTable_cmd_38
  }
  ,
  { /* glyph */
    { /* header */ 7, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_39
  }
  ,
  { /* glyph */
    { /* header */ 10, 249, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_40
  }
  ,
  { /* glyph */
    { /* header */ 10, 249, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_41
  }
  ,
  { /* glyph */
    { /* header */ 8, 248, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_42
  }
  ,
  { /* glyph */
    { /* header */ 5, 243, 13}
    ,
    ppmd_standardfont_glyphTable_cmd_43
  }
  ,
  { /* glyph */
    { /* header */ 8, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_44
  }
  ,
  { /* glyph */
    { /* header */ 2, 243, 13}
    ,
    ppmd_standardfont_glyphTable_cmd_45
  }
  ,
  { /* glyph */
    { /* header */ 5, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_46
  }
  ,
  { /* glyph */
    { /* header */ 2, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_47
  }
  ,
  { /* glyph */
    { /* header */ 17, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_48
  }
  ,
  { /* glyph */
    { /* header */ 4, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_49
  }
  ,
  { /* glyph */
    { /* header */ 14, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_50
  }
  ,
  { /* glyph */
    { /* header */ 15, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_51
  }
  ,
  { /* glyph */
    { /* header */ 6, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_52
  }
  ,
  { /* glyph */
    { /* header */ 17, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_53
  }
  ,
  { /* glyph */
    { /* header */ 23, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_54
  }
  ,
  { /* glyph */
    { /* header */ 5, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_55
  }
  ,
  { /* glyph */
    { /* header */ 29, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_56
  }
  ,
  { /* glyph */
    { /* header */ 23, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_57
  }
  ,
  { /* glyph */
    { /* header */ 11, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_58
  }
  ,
  { /* glyph */
    { /* header */ 14, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_59
  }
  ,
  { /* glyph */
    { /* header */ 3, 244, 12}
    ,
    ppmd_standardfont_glyphTable_cmd_60
  }
  ,
  { /* glyph */
    { /* header */ 5, 243, 13}
    ,
    ppmd_standardfont_glyphTable_cmd_61
  }
  ,
  { /* glyph */
    { /* header */ 3, 244, 12}
    ,
    ppmd_standardfont_glyphTable_cmd_62
  }
  ,
  { /* glyph */
    { /* header */ 20, 247, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_63
  }
  ,
  { /* glyph */
    { /* header */ 55, 243, 14}
    ,
    ppmd_standardfont_glyphTable_cmd_64
  }
  ,
  { /* glyph */
    { /* header */ 8, 247, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_65
  }
  ,
  { /* glyph */
    { /* header */ 23, 245, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_66
  }
  ,
  { /* glyph */
    { /* header */ 18, 246, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_67
  }
  ,
  { /* glyph */
    { /* header */ 15, 245, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_68
  }
  ,
  { /* glyph */
    { /* header */ 11, 246, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_69
  }
  ,
  { /* glyph */
    { /* header */ 8, 246, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_70
  }
  ,
  { /* glyph */
    { /* header */ 22, 246, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_71
  }
  ,
  { /* glyph */
    { /* header */ 8, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_72
  }
  ,
  { /* glyph */
    { /* header */ 2, 252, 4}
    ,
    ppmd_standardfont_glyphTable_cmd_73
  }
  ,
  { /* glyph */
    { /* header */ 10, 248, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_74
  }
  ,
  { /* glyph */
    { /* header */ 8, 245, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_75
  }
  ,
  { /* glyph */
    { /* header */ 3, 246, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_76
  }
  ,
  { /* glyph */
    { /* header */ 11, 244, 12}
    ,
    ppmd_standardfont_glyphTable_cmd_77
  }
  ,
  { /* glyph */
    { /* header */ 8, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_78
  }
  ,
  { /* glyph */
    { /* header */ 21, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_79
  }
  ,
  { /* glyph */
    { /* header */ 13, 245, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_80
  }
  ,
  { /* glyph */
    { /* header */ 24, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_81
  }
  ,
  { /* glyph */
    { /* header */ 16, 245, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_82
  }
  ,
  { /* glyph */
    { /* header */ 20, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_83
  }
  ,
  { /* glyph */
    { /* header */ 5, 248, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_84
  }
  ,
  { /* glyph */
    { /* header */ 10, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_85
  }
  ,
  { /* glyph */
    { /* header */ 5, 247, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_86
  }
  ,
  { /* glyph */
    { /* header */ 11, 244, 12}
    ,
    ppmd_standardfont_glyphTable_cmd_87
  }
  ,
  { /* glyph */
    { /* header */ 5, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_88
  }
  ,
  { /* glyph */
    { /* header */ 6, 247, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_89
  }
  ,
  { /* glyph */
    { /* header */ 8, 246, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_90
  }
  ,
  { /* glyph */
    { /* header */ 11, 249, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_91
  }
  ,
  { /* glyph */
    { /* header */ 2, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_92
  }
  ,
  { /* glyph */
    { /* header */ 11, 249, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_93
  }
  ,
  { /* glyph */
    { /* header */ 7, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_94
  }
  ,
  { /* glyph */
    { /* header */ 2, 253, 22}
    ,
    ppmd_standardfont_glyphTable_cmd_95
  }
  ,
  { /* glyph */
    { /* header */ 7, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_96
  }
  ,
  { /* glyph */
    { /* header */ 17, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_97
  }
  ,
  { /* glyph */
    { /* header */ 17, 246, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_98
  }
  ,
  { /* glyph */
    { /* header */ 14, 247, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_99
  }
  ,
  { /* glyph */
    { /* header */ 17, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_100
  }
  ,
  { /* glyph */
    { /* header */ 17, 247, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_101
  }
  ,
  { /* glyph */
    { /* header */ 8, 251, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_102
  }
  ,
  { /* glyph */
    { /* header */ 22, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_103
  }
  ,
  { /* glyph */
    { /* header */ 10, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_104
  }
  ,
  { /* glyph */
    { /* header */ 8, 252, 4}
    ,
    ppmd_standardfont_glyphTable_cmd_105
  }
  ,
  { /* glyph */
    { /* header */ 11, 251, 5}
    ,
    ppmd_standardfont_glyphTable_cmd_106
  }
  ,
  { /* glyph */
    { /* header */ 8, 247, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_107
  }
  ,
  { /* glyph */
    { /* header */ 2, 252, 4}
    ,
    ppmd_standardfont_glyphTable_cmd_108
  }
  ,
  { /* glyph */
    { /* header */ 18, 241, 15}
    ,
    ppmd_standardfont_glyphTable_cmd_109
  }
  ,
  { /* glyph */
    { /* header */ 10, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_110
  }
  ,
  { /* glyph */
    { /* header */ 17, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_111
  }
  ,
  { /* glyph */
    { /* header */ 17, 246, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_112
  }
  ,
  { /* glyph */
    { /* header */ 17, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_113
  }
  ,
  { /* glyph */
    { /* header */ 8, 249, 6}
    ,
    ppmd_standardfont_glyphTable_cmd_114
  }
  ,
  { /* glyph */
    { /* header */ 17, 248, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_115
  }
  ,
  { /* glyph */
    { /* header */ 8, 251, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_116
  }
  ,
  { /* glyph */
    { /* header */ 10, 247, 10}
    ,
    ppmd_standardfont_glyphTable_cmd_117
  }
  ,
  { /* glyph */
    { /* header */ 5, 248, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_118
  }
  ,
  { /* glyph */
    { /* header */ 11, 245, 11}
    ,
    ppmd_standardfont_glyphTable_cmd_119
  }
  ,
  { /* glyph */
    { /* header */ 5, 248, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_120
  }
  ,
  { /* glyph */
    { /* header */ 9, 248, 8}
    ,
    ppmd_standardfont_glyphTable_cmd_121
  }
  ,
  { /* glyph */
    { /* header */ 8, 248, 9}
    ,
    ppmd_standardfont_glyphTable_cmd_122
  }
  ,
  { /* glyph */
    { /* header */ 39, 249, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_123
  }
  ,
  { /* glyph */
    { /* header */ 2, 252, 4}
    ,
    ppmd_standardfont_glyphTable_cmd_124
  }
  ,
  { /* glyph */
    { /* header */ 39, 249, 7}
    ,
    ppmd_standardfont_glyphTable_cmd_125
  }
  ,
  { /* glyph */
    { /* header */ 23, 255, 21}
    ,
    ppmd_standardfont_glyphTable_cmd_126
  }
};


struct ppmd_font const ppmd_standardfont = {
  {/* .header */
    {'p','p','m','d','f','o','n','t'},
    0x01,
    95,
    32
  }
  ,
  /* .glyphTable: */ ppmd_standardfont_glyphTable
};
