TERMUX_PKG_HOMEPAGE=https://github.com/DaveGamble/cJSON
TERMUX_PKG_DESCRIPTION="Ultralightweight JSON parser in ANSI C"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.7.19"
TERMUX_PKG_SRCURL=https://github.com/DaveGamble/cJSON/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=7fa616e3046edfa7a28a32d5f9eacfd23f92900fe1f8ccd988c1662f30454562
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DENABLE_CJSON_UTILS=ON
"
