TERMUX_PKG_HOMEPAGE=https://www.prevanders.net/dwarf.html
TERMUX_PKG_DESCRIPTION="Library for handling DWARF Debugging Information Format"
TERMUX_PKG_LICENSE="BSD 2-Clause, BSD 3-Clause, GPL-2.0-only, LGPL-2.1-only, Public Domain"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.3.1"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_SRCURL="https://github.com/davea42/libdwarf-code/releases/download/v$TERMUX_PKG_VERSION/libdwarf-$TERMUX_PKG_VERSION.tar.xz"
TERMUX_PKG_SHA256=28cf9a5d27aceff5c1f906244a4fe7ae208e41d20a6d8fc7e091c633a40b6e97
TERMUX_PKG_DEPENDS="elfutils, zlib, zstd"
