TERMUX_PKG_HOMEPAGE=https://savannah.gnu.org/projects/which/
TERMUX_PKG_DESCRIPTION="Shows the full path of (shell) commands"
TERMUX_PKG_LICENSE="GPL-2.0-or-later"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.25"
TERMUX_PKG_SRCURL="https://mirrors.kernel.org/gnu/which/which-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=1cb83e4f702e60b8211ab5ec4c2afbab1b1dec80209456a7d2faf7584ed225ea
TERMUX_PKG_CONFLICTS="debianutils (<< 5.7-1)"
TERMUX_PKG_AUTO_UPDATE=true
