TERMUX_PKG_HOMEPAGE=http://www.underbit.com/products/mad/
TERMUX_PKG_DESCRIPTION="MAD ID3 tag manipulation library"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.16.4"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL="https://codeberg.org/tenacityteam/libid3tag/archive/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=2e9058af51e5f3881c13c55a9790abb9870812cc0f5917b6f3e825c6ae9b9f39
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="zlib"
TERMUX_PKG_BREAKS="libid3tag-dev"
TERMUX_PKG_REPLACES="libid3tag-dev"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_LIBDIR=$TERMUX__PREFIX__LIB_SUBDIR
-DCMAKE_INSTALL_INCLUDEDIR=$TERMUX__PREFIX__INCLUDE_SUBDIR
"
