#!/data/data/com.termux/files/usr/bin/sh
set -e
PREFIX="/data/data/com.termux/files/usr"

if [ -d "${PREFIX}/lib/gtk-3.0/3.0.0" ]; then
    rm -f "${PREFIX}/lib/gtk-3.0/3.0.0/immodules.cache"
    rmdir -p --ignore-fail-on-non-empty "${PREFIX}/lib/gtk-3.0/3.0.0"
fi
