TERMUX_PKG_HOMEPAGE="http://clucene.sourceforge.net/"
TERMUX_PKG_DESCRIPTION="C++ port of the high-performance text search engine Lucene"
TERMUX_PKG_LICENSE="Apache-2.0, LGPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.3.3.4"
TERMUX_PKG_REVISION=8
TERMUX_PKG_SRCURL="https://downloads.sourceforge.net/clucene/clucene-core-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=ddfdc433dd8ad31b5c5819cc4404a8d2127472a3b720d3e744e8c51d79732eab
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="boost, zlib"
TERMUX_PKG_BUILD_DEPENDS="boost-headers"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DENABLE_PACKAGING=OFF
-DENABLE_ASCII_MODE=OFF
-DBUILD_CONTRIBS_LIB:BOOL=ON
"
