TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/help2man/
TERMUX_PKG_DESCRIPTION="Conversion tool to create man files."
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_VERSION=1.47.12
TERMUX_PKG_SRCURL=http://mirrors.kernel.org/gnu/help2man/help2man-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=7d0ba64cf9d16ec97cc11aafb659b55aa7bdec99072ff2aec5fcecf0fbeab160
TERMUX_PKG_DEPENDS="perl"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_BUILD_IN_SRC=true
