TERMUX_PKG_HOMEPAGE="https://github.com/haskell-unordered-containers/unordered-containers"
TERMUX_PKG_DESCRIPTION="Efficient hashing-based container types"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.2.19.1
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/unordered-containers-${TERMUX_PKG_VERSION}/unordered-containers-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=1b27bec5e0d522b27a6029ebf4c4a6d40acbc083c787008e32fb55c4b1d128d2
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-hashable"
