TERMUX_PKG_HOMEPAGE="https://github.com/haskell-unordered-containers/unordered-containers"
TERMUX_PKG_DESCRIPTION="Efficient hashing-based container types"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.2.17.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/unordered-containers-${TERMUX_PKG_VERSION}/unordered-containers-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="c49e3a6e0b6aae68c035b163e54f3521d1d65d0a3543fa46eaeddc97b4375a17"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-hashable"
