TERMUX_PKG_HOMEPAGE=https://sourceforge.net/projects/gnuski
TERMUX_PKG_DESCRIPTION="Open source clone of Skifree, the old Windows game"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Henrik Grimler @Grimler91"
TERMUX_PKG_VERSION=0.3
TERMUX_PKG_REVISION=6
TERMUX_PKG_SRCURL=https://sourceforge.net/projects/gnuski/files/gnuski/gnuski-${TERMUX_PKG_VERSION}/gnuski-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=1b629bd29dd6ad362b56055ccdb4c7ad462ff39d7a0deb915753c2096f5f959d
TERMUX_PKG_DEPENDS="ncurses"
TERMUX_PKG_BUILD_IN_SRC=true
