TERMUX_PKG_HOMEPAGE="https://gitlab.freedesktop.org/vyivel/libsfdo"
TERMUX_PKG_DESCRIPTION="A collection of libraries which implement some of the freedesktop.org specifications."
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.1.3
TERMUX_PKG_SRCURL=https://gitlab.freedesktop.org/vyivel/libsfdo/-/archive/v${TERMUX_PKG_VERSION}/libsfdo-v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=d1f2d8b5edec827fd386c22d6f9151377ec7c194dca4d293e3abad9df9974209
#TERMUX_PKG_DEPENDS=""
#TERMUX_PKG_BUILD_IN_SRC=true
