TERMUX_SUBPKG_INCLUDE="opt/openjdk/lib/src.zip"
TERMUX_SUBPKG_DESCRIPTION="Source files for openjdk-17"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_DEPEND_ON_PARENT=no
TERMUX_SUBPKG_CONFLICTS="openjdk-17 (<< 17.0-25)"
