TERMUX_PKG_HOMEPAGE=https://docs.xfce.org/panel-plugins/xfce4-places-plugin/start
TERMUX_PKG_DESCRIPTION="This plugin brings much of the functionality of GNOME Places menu to Xfce"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Yisus7u7 <yisus7u7v@gmail.com>"
TERMUX_PKG_VERSION=1.8.1
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/panel-plugins/xfce4-places-plugin/1.8/xfce4-places-plugin-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=f211219f03c9260f624370e18c79e4176c9d35a8247158e77e5d811327610ab2
TERMUX_PKG_DEPENDS="gtk3, atk, libcairo, exo, pango, libice, libsm, libnotify, harfbuzz, gdk-pixbuf, glib, libxfce4util, libxfce4ui, xfce4-panel, thunar, xfconf"
TERMUX_PKG_BUILD_IN_SRC=true
