TERMUX_PKG_HOMEPAGE=https://github.com/Tencent/rapidjson/
TERMUX_PKG_DESCRIPTION="fast JSON parser/generator for C++ with SAX/DOM style API"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.1.0
TERMUX_PKG_REVISION=4
TERMUX_PKG_SRCURL=https://github.com/Tencent/rapidjson/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=bf7ced29704a1e696fbccf2a2b4ea068e7774fa37f6d7dd4039d0787f8bed98e
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DRAPIDJSON_BUILD_EXAMPLES=OFF"
