TERMUX_PKG_HOMEPAGE="https://github.com/haskell/hackage-security"
TERMUX_PKG_DESCRIPTION="Hackage security library"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.6.2.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/hackage-security-${TERMUX_PKG_VERSION}/hackage-security-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="bf22cd16dde7d6b7130463f4d7324b64a2964d9ef3f523df97d7cb98544d64a8"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-zlib, haskell-ed25519, haskell-network-uri, haskell-lukko, haskell-network, haskell-cabal, haskell-base64-bytestring, haskell-tar, haskell-cryptohash-sha256, haskell-base16-bytestring, haskell-cabal-syntax"
