TERMUX_PKG_HOMEPAGE="https://github.com/haskell/hackage-security"
TERMUX_PKG_DESCRIPTION="Hackage security library"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.6.2.3
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/hackage-security-${TERMUX_PKG_VERSION}/hackage-security-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=52ee0576971955571d846b8e6c09638f89f4f7881f4a95173e44ccc0d856a066
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-zlib, haskell-ed25519, haskell-network-uri, haskell-lukko, haskell-network, haskell-cabal, haskell-base64-bytestring, haskell-tar, haskell-cryptohash-sha256, haskell-base16-bytestring, haskell-cabal-syntax"
