TERMUX_PKG_HOMEPAGE=https://re2c.org/
TERMUX_PKG_DESCRIPTION="Lexer generator for C, C++ and Go."
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="Yaksh Bariya <thunder-coding@termux.dev>"
TERMUX_PKG_VERSION="4.0.1"
TERMUX_PKG_SRCURL=https://github.com/skvadrik/re2c/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=f8a0192af88cedd1cf2e1f5f7859118018971b87836fcaae230da0b2ffc60af1
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
