TERMUX_PKG_HOMEPAGE=https://re2c.org/
TERMUX_PKG_DESCRIPTION="Lexer generator for C, C++ and Go."
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="Yaksh Bariya <thunder-coding@termux.dev>"
TERMUX_PKG_VERSION="3.1"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/skvadrik/re2c/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=087c44de0400fb15caafde09fd72edc7381e688a35ef505ee65e0e3d2fac688b
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
