TERMUX_PKG_HOMEPAGE=https://www.opencode.net/trialuser/qt6ct/
TERMUX_PKG_DESCRIPTION="Qt 6 Configuration Utility"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.11"
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://www.opencode.net/trialuser/qt6ct/-/archive/${TERMUX_PKG_VERSION}/qt6ct-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=32cd06cb4e801362676194ec6c3378498c81eb9484c57870fee3f7d5952ebe1f
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt6-qttools"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DPLUGINDIR=${TERMUX_PREFIX}/lib/qt6/plugins
"
