TERMUX_PKG_HOMEPAGE=https://github.com/trialuser02/qt6ct
TERMUX_PKG_DESCRIPTION="Qt 6 Configuration Utility"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.10"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://www.opencode.net/trialuser/qt6ct/-/archive/${TERMUX_PKG_VERSION}/qt6ct-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=5ba90fac7bebb87aacd0454736f5d062b12543c11df9110665877b834b63de63
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt6-qttools"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DPLUGINDIR=${TERMUX_PREFIX}/lib/qt6/plugins
"
