TERMUX_PKG_HOMEPAGE=https://github.com/CNugteren/CLBlast
TERMUX_PKG_DESCRIPTION="Tuned OpenCL BLAS"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.7.0"
TERMUX_PKG_SRCURL=https://github.com/CNugteren/CLBlast/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=cac83330a6110214f2b7efc8e46062536f40ba96122f3b2a074a51497d8ca9e7
TERMUX_PKG_DEPENDS="libc++, ocl-icd"
TERMUX_PKG_BUILD_DEPENDS="opencl-headers"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DNETLIB=ON
"
