TERMUX_PKG_HOMEPAGE=https://github.com/CNugteren/CLBlast
TERMUX_PKG_DESCRIPTION="Tuned OpenCL BLAS"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.6.2"
TERMUX_PKG_SRCURL=https://github.com/CNugteren/CLBlast/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=d7c1fb61162a6e2fa4eb6e95fafacbe22ee8460cd82371478f794f195aad267f
TERMUX_PKG_DEPENDS="libc++, ocl-icd"
TERMUX_PKG_BUILD_DEPENDS="opencl-headers"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DNETLIB=ON
"
