TERMUX_PKG_HOMEPAGE=https://github.com/CNugteren/CLBlast
TERMUX_PKG_DESCRIPTION="Tuned OpenCL BLAS"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.6.1"
TERMUX_PKG_SRCURL=https://github.com/CNugteren/CLBlast/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=e68d026108447cab53cb18d473b4363ab3958d7c8f97c522bbee1651069eec66
TERMUX_PKG_DEPENDS="libc++, ocl-icd"
TERMUX_PKG_BUILD_DEPENDS="opencl-headers"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DNETLIB=ON
"
