TERMUX_PKG_HOMEPAGE="http://github.com/phadej/edit-distance"
TERMUX_PKG_DESCRIPTION="Levenshtein and restricted Damerau-Levenshtein edit distances"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.2.2.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/edit-distance-${TERMUX_PKG_VERSION}/edit-distance-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="3e8885ee2f56ad4da940f043ae8f981ee2fe336b5e8e4ba3f7436cff4f526c4a"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-random"
