TERMUX_PKG_HOMEPAGE=https://github.com/KhronosGroup/SPIRV-LLVM-Translator
TERMUX_PKG_DESCRIPTION="SPIR-V LLVM Translator"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="22.1.3"
TERMUX_PKG_SRCURL="https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=8d3d5c31c1ff355dbbf87046f1b94cd1ab5390439a817679ec71484df74cac18
TERMUX_PKG_DEPENDS="libc++, libllvm (<< $TERMUX_LLVM_NEXT_MAJOR_VERSION)"
TERMUX_PKG_BUILD_DEPENDS="libllvm-static, spirv-headers, spirv-tools"
TERMUX_PKG_NO_STATICSPLIT=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP="22.\d+\.\d+"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBASE_LLVM_VERSION=${TERMUX_LLVM_VERSION}
-DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=${TERMUX_PREFIX}
"
