TERMUX_PKG_HOMEPAGE=https://github.com/KhronosGroup/SPIRV-LLVM-Translator
TERMUX_PKG_DESCRIPTION="SPIR-V LLVM Translator"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="21.1.4"
TERMUX_PKG_SRCURL=https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=e900c907b62f82cf541a611b33d6685f375fe3bda6f041087fcdba350ffb437d
TERMUX_PKG_DEPENDS="libc++, libllvm (<< $TERMUX_LLVM_NEXT_MAJOR_VERSION)"
TERMUX_PKG_BUILD_DEPENDS="libllvm-static, spirv-headers, spirv-tools"
TERMUX_PKG_NO_STATICSPLIT=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP="21.\d+\.\d+"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBASE_LLVM_VERSION=${TERMUX_LLVM_VERSION}
-DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=${TERMUX_PREFIX}
"
