TERMUX_PKG_HOMEPAGE=htts://github.com/tadfisher/pass-otp
TERMUX_PKG_DESCRIPTION="A pass extension for managing one-time-password (OTP) tokens"
TERMUX_PKG_MAINTAINER="Henrik Grimler @Grimler91"
TERMUX_PKG_VERSION=1.1.0
TERMUX_PKG_SRCURL=https://github.com/tadfisher/pass-otp/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=3971467475f8ed573eb860c7a44bd268d464d169dddbc0a4da89232d5beee144
TERMUX_PKG_BUILD_IN_SRC=yes
TERMUX_PKG_PLATFORM_INDEPENDENT=yes
TERMUX_PKG_DEPENDS="pass, oathtool"
TERMUX_PKG_SUGGESTS="libqrencode"
