TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/automake/
TERMUX_PKG_DESCRIPTION="Tool for automatically generating Makefile.in files"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.17
TERMUX_PKG_SRCURL=https://mirrors.kernel.org/gnu/automake/automake-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=8920c1fc411e13b90bf704ef9db6f29d540e76d232cb3b2c9f4dc4cc599bd990
TERMUX_PKG_DEPENDS="autoconf"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_GROUPS="base-devel"
