TERMUX_PKG_HOMEPAGE=http://www.nongnu.org/lzip/lzlib.html
TERMUX_PKG_DESCRIPTION="A library providing in-memory LZMA compression and decompression functions"
TERMUX_PKG_LICENSE="BSD 2-Clause, GPL-2.0"
TERMUX_PKG_LICENSE_FILE="COPYING, COPYING.GPL"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.15"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=4afab907a46d5a7d14e927a1080c3f4d7e3ca5a0f9aea81747d8fed0292377ff
TERMUX_PKG_AUTO_UPDATE=true
