TERMUX_PKG_HOMEPAGE=http://www.nongnu.org/lzip/lzlib.html
TERMUX_PKG_DESCRIPTION="A library providing in-memory LZMA compression and decompression functions"
TERMUX_PKG_LICENSE="BSD 2-Clause, GPL-2.0"
TERMUX_PKG_LICENSE_FILE="COPYING, COPYING.GPL"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.14"
TERMUX_PKG_SRCURL=https://download.savannah.gnu.org/releases/lzip/lzlib/lzlib-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=5acac8714ed4f306020bae660dddce706e5f8a795863679037da9fe6bf4dcf6f
TERMUX_PKG_AUTO_UPDATE=true
