TERMUX_SUBPKG_DESCRIPTION="Faust DSP libraries"
TERMUX_SUBPKG_DEPEND_ON_PARENT=unversioned
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_INCLUDE="
share/faust/aanl.lib
share/faust/all.lib
share/faust/analyzers.lib
share/faust/basics.lib
share/faust/compressors.lib
share/faust/delays.lib
share/faust/demos.lib
share/faust/dx7.lib
share/faust/effect.lib
share/faust/envelopes.lib
share/faust/fds.lib
share/faust/filter.lib
share/faust/filters.lib
share/faust/hoa.lib
share/faust/instruments.lib
share/faust/interpolators.lib
share/faust/math.lib
share/faust/maths.lib
share/faust/maxmsp.lib
share/faust/mi.lib
share/faust/misceffects.lib
share/faust/music.lib
share/faust/noises.lib
share/faust/oscillator.lib
share/faust/oscillators.lib
share/faust/phaflangers.lib
share/faust/physmodels.lib
share/faust/platform.lib
share/faust/quantizers.lib
share/faust/reducemaps.lib
share/faust/reverbs.lib
share/faust/routes.lib
share/faust/sf.lib
share/faust/signals.lib
share/faust/soundfiles.lib
share/faust/spats.lib
share/faust/stdfaust.lib
share/faust/synths.lib
share/faust/tonestacks.lib
share/faust/tubes.lib
share/faust/vaeffects.lib
share/faust/version.lib
share/faust/wdmodels.lib
share/faust/webaudio.lib
"
