TERMUX_PKG_HOMEPAGE="https://github.com/haskellari/integer-logarithms"
TERMUX_PKG_DESCRIPTION="Integer logarithms."
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.0.3.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/integer-logarithms-${TERMUX_PKG_VERSION}/integer-logarithms-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="9b0a9f9fab609b15cd015865721fb05f744a1bc77ae92fd133872de528bbea7f"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
