TERMUX_PKG_HOMEPAGE=http://www.grinninglizard.com/tinyxml2/
TERMUX_PKG_DESCRIPTION="A simple, small, efficient, C++ XML parser"
TERMUX_PKG_LICENSE="ZLIB"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="11.0.0"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/leethomason/tinyxml2/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=5556deb5081fb246ee92afae73efd943c889cef0cafea92b0b82422d6a18f289
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
