TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/transformers-compat/"
TERMUX_PKG_DESCRIPTION="A small compatibility shim for the transformers library"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.7.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/transformers-compat-${TERMUX_PKG_VERSION}/transformers-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="ac0b861534c14d3cfd61534f474674e3b634b8decea072ffd4d21f8b59f35080"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
