TERMUX_PKG_HOMEPAGE="https://github.com/ekmett/transformers-compat/"
TERMUX_PKG_DESCRIPTION="A small compatibility shim for the transformers library"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.7.2
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/transformers-compat-${TERMUX_PKG_VERSION}/transformers-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=b62c7304c9f3cbc9463d0739aa85cb9489f217ea092b9d625d417514fbcc9d6a
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
