TERMUX_PKG_HOMEPAGE=https://jbig2dec.com/
TERMUX_PKG_DESCRIPTION="Decoder implementation of the JBIG2 image compression format"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=0.17
TERMUX_PKG_SRCURL=https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs950/jbig2dec-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=f72bad7102638b31fa96be7492fb3d447a83d71c644cffd01f2a7ec52bd5fb72
TERMUX_PKG_DEPENDS="libpng"
TERMUX_PKG_BREAKS="jbig2dec-dev"
TERMUX_PKG_REPLACES="jbig2dec-dev"
