TERMUX_PKG_HOMEPAGE=https://github.com/scop/bash-completion
TERMUX_PKG_DESCRIPTION="Programmable completion for the bash shell"
TERMUX_PKG_VERSION=2.5
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/scop/bash-completion/releases/download/${TERMUX_PKG_VERSION}/bash-completion-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=b0b9540c65532825eca030f1241731383f89b2b65e80f3492c5dd2f0438c95cf
TERMUX_PKG_FOLDERNAME=bash-completion-${TERMUX_PKG_VERSION}
TERMUX_PKG_DEPENDS="bash"
TERMUX_PKG_PLATFORM_INDEPENDENT=yes
