TERMUX_PKG_HOMEPAGE="https://github.com/hoene/libmysofa"
TERMUX_PKG_DESCRIPTION="Reader for AES SOFA files to get better HRTFs"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.3.5"
TERMUX_PKG_SRCURL="https://github.com/hoene/libmysofa/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=f29508c335c83d8703f943ffc9ca783ac39aca84e851357f13a55af0f8143137
TERMUX_PKG_DEPENDS="zlib"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCODE_COVERAGE=OFF
-DBUILD_TESTS=OFF
"
