TERMUX_PKG_HOMEPAGE="https://github.com/hoene/libmysofa"
TERMUX_PKG_DESCRIPTION="Reader for AES SOFA files to get better HRTFs"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.3.4"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL="https://github.com/hoene/libmysofa/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=64c661f75ef39edf68bfc3a28403d2b5a0bd251d0b9f5d021ed6f7917867fb37
TERMUX_PKG_DEPENDS="zlib"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCODE_COVERAGE=OFF
-DBUILD_TESTS=OFF
"
