TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/indexed-traversable-instances"
TERMUX_PKG_DESCRIPTION="More instances of FunctorWithIndex, FoldableWithIndex, TraversableWithIndex"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.1.1.1
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/indexed-traversable-instances-${TERMUX_PKG_VERSION}/indexed-traversable-instances-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=895ee5063d59e2b58930ca6fa54885bb11f19c8b7c7ba6c7b014f9431cdcc0b0
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-vector, haskell-onetuple, haskell-tagged, haskell-indexed-traversable, haskell-unordered-containers"
