TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/indexed-traversable-instances"
TERMUX_PKG_DESCRIPTION="More instances of FunctorWithIndex, FoldableWithIndex, TraversableWithIndex"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/indexed-traversable-instances-${TERMUX_PKG_VERSION}/indexed-traversable-instances-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="100ed1023b541328b04bcec0964b9f9d5fc93285fc23a2ac6873bf8597439a44"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-vector, haskell-onetuple, haskell-tagged, haskell-indexed-traversable, haskell-unordered-containers"
