TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/random"
TERMUX_PKG_DESCRIPTION="Pseudo-random number generation"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=1.2.1.1
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/random-${TERMUX_PKG_VERSION}/random-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=3e1272f7ed6a4d7bd1712b90143ec326fee9b225789222379fea20a9c90c9b76
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-splitmix"
