TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/random"
TERMUX_PKG_DESCRIPTION="Pseudo-random number generation"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.2.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/random-${TERMUX_PKG_VERSION}/random-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="265c768fc5f2ca53cde6a87e706b4448cad474c3deece933c103f24453661457"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-splitmix"
