TERMUX_PKG_HOMEPAGE=https://github.com/fcitx/fcitx5-hangul
TERMUX_PKG_DESCRIPTION="libhangul input method support for fcitx5"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="5.1.10"
TERMUX_PKG_SRCURL="https://github.com/fcitx/fcitx5-hangul/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=e0c902c9aa2c711315d23c98adfa73e0deb080d110a1bbb829f90e3c40155b6a
TERMUX_PKG_DEPENDS="fcitx5, libc++, libhangul"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
