TERMUX_PKG_HOMEPAGE=https://github.com/fcitx/fcitx5-hangul
TERMUX_PKG_DESCRIPTION="libhangul input method support for fcitx5"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="5.1.4"
TERMUX_PKG_SRCURL="https://github.com/fcitx/fcitx5-hangul/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=49404de5de38f4b182e487e7a51a4a68fdb5b8acef531d27ba328aca552b9009
TERMUX_PKG_DEPENDS="fcitx5, libc++, libhangul"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
