TERMUX_PKG_HOMEPAGE="https://github.com/ekmett/bifunctors/"
TERMUX_PKG_DESCRIPTION="Bifunctors"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=5.5.13
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/bifunctors-${TERMUX_PKG_VERSION}/bifunctors-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=26cc27ade3796cf03bd680f98ebb7b8c0d7fd1b67c1894dc3635f734fba7dbd7
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-orphans, haskell-comonad, haskell-th-abstraction, haskell-tagged"
