TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/bifunctors/"
TERMUX_PKG_DESCRIPTION="Bifunctors"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="5.5.11"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/bifunctors-${TERMUX_PKG_VERSION}/bifunctors-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="2b6b9672faab649995cf4c885f353b6638b6daee467a9ace40a7fc773831091c"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-orphans, haskell-comonad, haskell-th-abstraction, haskell-tagged"
