TERMUX_PKG_HOMEPAGE=https://www.xfce.org/
TERMUX_PKG_DESCRIPTION="Application library for XFCE"
TERMUX_PKG_LICENSE="GPL-2.0, LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=4.17.1
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=http://archive.xfce.org/src/xfce/exo/4.17/exo-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=63babbf01e75469e065a0ff65607abc9d2231d7b0d071cb2a27dd20dad3270c6
TERMUX_PKG_DEPENDS="hicolor-icon-theme, libxfce4ui"
TERMUX_PKG_CONFLICTS="libexo"
TERMUX_PKG_REPLACES="libexo"
TERMUX_PKG_PROVIDES="libexo"
TERMUX_PKG_RM_AFTER_INSTALL="share/icons/hicolor/icon-theme.cache"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--enable-gtk-doc-html=no"