TERMUX_SUBPKG_INCLUDE="
bin/gtk4-demo
bin/gtk4-demo-application
bin/gtk4-icon-browser
bin/gtk4-node-editor
bin/gtk4-print-editor
bin/gtk4-widget-factory
share/applications/org.gtk.Demo4.desktop
share/applications/org.gtk.IconBrowser4.desktop
share/applications/org.gtk.PrintEditor4.desktop
share/applications/org.gtk.WidgetFactory4.desktop
share/applications/org.gtk.gtk4.NodeEditor.desktop
share/glib-2.0/schemas/org.gtk.Demo4.gschema.xml
share/icons/hicolor/scalable/apps/org.gtk.Demo4.svg
share/icons/hicolor/scalable/apps/org.gtk.IconBrowser4.svg
share/icons/hicolor/scalable/apps/org.gtk.PrintEditor4.Devel.svg
share/icons/hicolor/scalable/apps/org.gtk.PrintEditor4.svg
share/icons/hicolor/scalable/apps/org.gtk.WidgetFactory4.svg
share/icons/hicolor/scalable/apps/org.gtk.gtk4.NodeEditor.Devel.svg
share/icons/hicolor/scalable/apps/org.gtk.gtk4.NodeEditor.svg
share/icons/hicolor/symbolic/apps/org.gtk.Demo4-symbolic.svg
share/icons/hicolor/symbolic/apps/org.gtk.IconBrowser4-symbolic.svg
share/icons/hicolor/symbolic/apps/org.gtk.PrintEditor4-symbolic.svg
share/icons/hicolor/symbolic/apps/org.gtk.WidgetFactory4-symbolic.svg
share/icons/hicolor/symbolic/apps/org.gtk.gtk4.NodeEditor-symbolic.svg
share/metainfo/org.gtk.Demo4.appdata.xml
share/metainfo/org.gtk.IconBrowser4.appdata.xml
share/metainfo/org.gtk.PrintEditor4.appdata.xml
share/metainfo/org.gtk.WidgetFactory4.appdata.xml
share/metainfo/org.gtk.gtk4.NodeEditor.appdata.xml
"
TERMUX_SUBPKG_DESCRIPTION="gtk4 demonstration application"
