TERMUX_PKG_HOMEPAGE=https://gitlab.com/ecodis/exhale
TERMUX_PKG_DESCRIPTION="Open source xHE-AAC encoder"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="include/License.htm"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.2.1"
TERMUX_PKG_SRCURL=https://gitlab.com/ecodis/exhale/-/archive/v${TERMUX_PKG_VERSION}/exhale-v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=985c92be860845862e22000ad56573fc9b5274c6cbbbeddfd5b8a2c55e6eb2af
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DBUILD_SHARED_LIBS=ON"
