TERMUX_PKG_HOMEPAGE=https://simdutf.github.io/simdutf/
TERMUX_PKG_DESCRIPTION="Unicode validation and transcoding at billions of characters per second"
TERMUX_PKG_LICENSE="Apache-2.0, MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE-APACHE, LICENSE-MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="9.1.0"
TERMUX_PKG_SRCURL=https://github.com/simdutf/simdutf/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=24e3510a4c95a9e6eb0fb4a27eea650d13773231cbd8b564ed9670aa5484d193
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DSIMDUTF_TESTS=OFF
-DSIMDUTF_TOOLS=OFF
-DSIMDUTF_BENCHMARKS=OFF
"
