TERMUX_PKG_HOMEPAGE=https://simdutf.github.io/simdutf/
TERMUX_PKG_DESCRIPTION="Unicode validation and transcoding at billions of characters per second"
TERMUX_PKG_LICENSE="Apache-2.0, MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE-APACHE, LICENSE-MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="9.1.2"
TERMUX_PKG_SRCURL=https://github.com/simdutf/simdutf/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0992cd1bcddee10424e49d6bc3ff8da02f9abc4c48033cbb1b0b41b62c727d33
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DSIMDUTF_TESTS=OFF
-DSIMDUTF_TOOLS=OFF
-DSIMDUTF_BENCHMARKS=OFF
"
