TERMUX_PKG_HOMEPAGE="https://github.com/haskellari/time-compat"
TERMUX_PKG_DESCRIPTION="Compatibility package for time"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.9.6.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/time-compat-${TERMUX_PKG_VERSION}/time-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="ad07bb00eb9678c2136d3680752b00acc4cbc522654bb3199bf31c61ef1e6b80"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-orphans, haskell-hashable"
