TERMUX_PKG_HOMEPAGE=https://github.com/xapp-project/xapp-symbolic-icons
TERMUX_PKG_DESCRIPTION="A set of symbolic icons for Gtk applications and projects"
TERMUX_PKG_LICENSE="GPL-3.0-only, LGPL-3.0-only"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.0.8"
TERMUX_PKG_SRCURL="https://github.com/xapp-project/xapp-symbolic-icons/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=5cd9810ab9c4f002a4fd5e4557794b2e8460bf253faeef0301c3aa888c042e5c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="hicolor-icon-theme, python"
