TERMUX_PKG_HOMEPAGE=https://github.com/xapp-project/xapp-symbolic-icons
TERMUX_PKG_DESCRIPTION="A set of symbolic icons for Gtk applications and projects"
TERMUX_PKG_LICENSE="GPL-3.0-only, LGPL-3.0-only"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.0.9"
TERMUX_PKG_SRCURL="https://github.com/xapp-project/xapp-symbolic-icons/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=0ebb603eaa34f34d44bc419119595c91785caf0e29a2ad2adaa7fea9cc2e6ebb
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="hicolor-icon-theme, python"
