--- ./Makefile.in.org	2023-09-04 19:40:51.160939201 +0200
+++ ./Makefile.in	2023-09-04 19:43:20.271975033 +0200
@@ -417,7 +417,7 @@

 sanity-check:
 	@[ -f .no-advice-on-failure ] && exit 0; true
-	@v=$$(src/emacs${EXEEXT} --batch --eval \
+	@v=$$(src/bootstrap-emacs${EXEEXT} --batch --eval \
 	  '(progn (defun f (n) (if (= 0 n) 1 (* n (f (- n 1))))) (princ (f 10)))' \
 	  2> /dev/null); \
 	[ "X$$v" = "X3628800" ] && exit 0; \
@@ -471,7 +471,7 @@
 	  -e 's;\(#.*PATH_LOADSEARCH\).*$$;\1 "${standardlisppath}";' \
 	  -e 's;\(#.*PATH_REL_LOADSEARCH\).*$$;\1 "${lispdirrel}";' 	\
 	  -e 's;\(#.*PATH_SITELOADSEARCH\).*$$;\1 "${locallisppath}";' \
-	  -e 's;\(#.*PATH_DUMPLOADSEARCH\).*$$;\1 "${buildlisppath}";' \
+	  -e 's;\(#.*PATH_DUMPLOADSEARCH\).*$$;\1 "${standardlisppath}";' \
 	  -e '/^#define PATH_[^ ]*SEARCH /s/\([":]\):*/\1/g'		\
 	  -e '/^#define PATH_[^ ]*SEARCH /s/:"/"/'			\
 	  -e 's;\(#.*PATH_EXEC\).*$$;\1 "${archlibdir}";'		\
