TERMUX_PKG_HOMEPAGE=https://alembic.io
TERMUX_PKG_DESCRIPTION="A framework for sharing scene data that includes a C++ lib, a file format and client plugin"
TERMUX_PKG_LICENSE="BSD 3-Clause, BSL-1.0"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.8.10"
TERMUX_PKG_SRCURL=https://github.com/alembic/alembic/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=06c9172faf29e9fdebb7be99621ca18b32b474f8e481238a159c87d16b298553
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="imath, libc++"
