TERMUX_PKG_HOMEPAGE=https://alembic.io
TERMUX_PKG_DESCRIPTION="A framework for sharing scene data that includes a C++ lib, a file format and client plugin"
TERMUX_PKG_LICENSE="BSD 3-Clause, BSL-1.0"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.8.6
TERMUX_PKG_SRCURL=https://github.com/alembic/alembic/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=c572ebdea3a5f0ce13774dd1fceb5b5815265cd1b29d142cf8c144b03c131c8c
TERMUX_PKG_DEPENDS="imath, libc++"
