TERMUX_SUBPKG_INCLUDE="
share/xapian-core
share/man/man1/copydatabase.1
share/man/man1/xapian-compact.1
share/man/man1/xapian-metadata.1
share/man/man1/xapian-delve.1
share/man/man1/xapian-progsrv.1
share/man/man1/xapian-replicate.1
share/man/man1/xapian-tcpsrv.1
share/man/man1/quest.1
share/man/man1/xapian-check.1
share/man/man1/xapian-replicate-server.1
bin/simpleexpand
bin/xapian-metadata
bin/simpleindex
bin/quest
bin/xapian-replicate-server
bin/xapian-check
bin/xapian-tcpsrv
bin/copydatabase
bin/xapian-progsrv
bin/simplesearch
bin/xapian-compact
bin/xapian-delve
bin/xapian-replicate
"
TERMUX_SUBPKG_DESCRIPTION="Basic tools for the Xapian search engine"
