TERMUX_PKG_HOMEPAGE=https://hermesengine.dev
TERMUX_PKG_DESCRIPTION="A Javascript Engine optimized for running react native"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.12.0"
TERMUX_PKG_BUILD_DEPENDS="libicu, readline"
TERMUX_PKG_SRCURL=https://github.com/AbhiTheModder/hermes/archive/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=c62a4626614763cb9f2a22a37b1713586985e7a51937ff4eb09cb7a286e04740
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DIMPORT_HERMESC:PATH=$TERMUX_PKG_SRCDIR/ImportHermesc.cmake"
