TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/distributive/"
TERMUX_PKG_DESCRIPTION="Distributive functors -- Dual to Traversable"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.6.2.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/distributive-${TERMUX_PKG_VERSION}/distributive-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="d7351392e078f58caa46630a4b9c643e1e2e9dddee45848c5c8358e7b1316b91"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-orphans, haskell-tagged"
