TERMUX_PKG_HOMEPAGE=http://ipfs.io
TERMUX_PKG_DESCRIPTION="gx packaging built on ipfs"
TERMUX_PKG_VERSION=0.9.0
TERMUX_PKG_SHA256=498eb290a73a1d6161bc1ba50fae268a9446ad899577660aafb608ff49d58c7c
TERMUX_PKG_SRCURL=https://dist.ipfs.io/gx/v${TERMUX_PKG_VERSION}/gx_v${TERMUX_PKG_VERSION}_linux-arm.tar.gz
TERMUX_PKG_FOLDERNAME=gx
TERMUX_PKG_DEPENDS="ipfs"
TERMUX_PKG_BUILD_IN_SRC=no
TERMUX_PKG_PLATFORM_INDEPENDENT=no

termux_step_make_install () {
	mkdir -p ${TERMUX_PREFIX}/bin/
	cp gx ${TERMUX_PREFIX}/bin/
}

