name: "Package request"
description: "Request a new package"
title: "[Package]: "
labels: ["package request"]
body:
  - type: markdown
    attributes:
      value: |
        If our repositories do not provide a package that fullfill your needs, consider requesting it. Use search to check whether package has been requested previously.

        To submit a request of a new package, fill the form below. Be patient, do not expect that package will get added immediately.
  - type: textarea
    attributes:
      label: Package description
      description: A clear and concise description of what this package do and why it should be added to Termux repositories.
    validations:
      required: true
  - type: input
    attributes:
      label: Home page URL
  - type: input
    attributes:
      label: Source code URL
      placeholder: Link to Git or source archive
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Packaging policy acknowledgement
      description: Not every package could be added and do not forget that Termux is operated by limited team and hosting resources.
      options:
        - label: I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).
          required: true
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Have you tried to compile it on device?

        If it did not work then provide the error you ran into. Otherwise please share build steps and any patches that you had to apply.
