blank_issues_enabled: true
contact_links:
  - name: Want to ask questions about the project? (Matrix)
    url: https://matrix.to/#/#termux_termux:gitter.im
    about: General termux-related discussions in matrix
  - name: Want to ask questions about the project? (Discord)
    url: https://discord.gg/HXpF69X
    about: General termux-related discussions in Discord
  - name: Want to ask questions about the project? (Github)
    url: https://github.com/termux/termux-packages/discussions
    about: Join GitHub Discussions
  - name: Have coding problems? (Matrix)
    url: https://matrix.to/#/#coding:matrix.termux.club
    about: Talks about Termux coding in matrix
  - name: Want to ask about X11 packages? (Matrix)
    url: https://matrix.to/#/#x11:matrix.termux.club
    about: Talks about Termux X11 packages in matrix
  - name: Want to add new mirrors? Mirror related issues?
    url: https://github.com/termux/termux-tools/issues
    about: Visit termux-tools issues page
