blank_issues_enabled: true
contact_links:
  - name: Want to add new mirrors? Mirror related issues?
    url: https://github.com/termux/termux-tools/issues
    about: Visit termux-tools issues page
  - name: Want to ask questions about the project?
    url: https://github.com/termux/termux-packages/discussions
    about: Join GitHub Discussions
