TERMUX_PKG_HOMEPAGE="https://github.com/haskell-compat/base-orphans#readme"
TERMUX_PKG_DESCRIPTION="Backwards-compatible orphan instances for base"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.8.6"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base-orphans-${TERMUX_PKG_VERSION}/base-orphans-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="20a21c4b7adb0fd844b25e196241467406a28286b021f9b7a082ab03fa8015eb"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
