TERMUX_PKG_HOMEPAGE="https://github.com/haskell-compat/base-orphans#readme"
TERMUX_PKG_DESCRIPTION="Backwards-compatible orphan instances for base"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.8.7
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base-orphans-${TERMUX_PKG_VERSION}/base-orphans-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=888fd67f0dbe932778f5b170922ce80d0dcab1680ee98f1d6fcc362f20d9e447
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
