TERMUX_PKG_HOMEPAGE=https://www.libsdl.org/projects/SDL_ttf/
TERMUX_PKG_DESCRIPTION="Unpack and build. Run \"showfont fontfile\" to display a font using the library. "
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="COPYING.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.0.15
TERMUX_PKG_SRCURL=https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a9eceb1ad88c1f1545cd7bd28e7cbc0b2c14191d40238f531a15b01b1b22cd33
TERMUX_PKG_DEPENDS="harfbuzz, freetype, libsdl"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--disable-shared"
