TERMUX_PKG_HOMEPAGE=https://github.com/imgflo/imgflo
TERMUX_PKG_DESCRIPTION="HTTP image processing server & Flowhub.io compatible runtime"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.4.2
TERMUX_PKG_REVISION=7
TERMUX_PKG_SRCURL=https://github.com/imgflo/imgflo/archive/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=4dd5fc9d34f3cfc294fd69a14d50ed5401abeb829132f1b1ac316e28223fc393
TERMUX_PKG_DEPENDS="gegl, libsoup, zlib"
TERMUX_PKG_BUILD_IN_SRC=true
