TERMUX_PKG_HOMEPAGE=https://invisible-island.net/byacc/
TERMUX_PKG_DESCRIPTION="byacc is generally conceded to be the best yacc variant available"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="20260126"
TERMUX_PKG_SRCURL="https://invisible-island.net/archives/byacc/byacc-${TERMUX_PKG_VERSION}.tgz"
TERMUX_PKG_SHA256=b618c5fb44c2f5f048843db90f7d1b24f78f47b07913c8c7ba8c942d3eb24b00
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_BUILD_DEPENDS="groff"
TERMUX_PKG_CONFLICTS="bison"
