TERMUX_PKG_HOMEPAGE="https://neurobin.org/projects/softwares/unix/shc/"
TERMUX_PKG_DESCRIPTION="Shell script compiler"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Krishna Kanhaiya @kcubeterm"
TERMUX_PKG_VERSION=4.0.3
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://github.com/neurobin/shc/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=7d7fa6a9f5f53d607ab851d739ae3d3b99ca86e2cb1425a6cab9299f673aee16
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="clang"
