TERMUX_PKG_HOMEPAGE=https://github.com/termux/libandroid-shmem
TERMUX_PKG_DESCRIPTION="System V shared memory emulation on Android using ashmem"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.31
TERMUX_PKG_SRCURL=https://github.com/termux/libandroid-shmem/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=2422782867294c9af11136e6f3dfc1106bcfb5d59f675168353df325b5a73a6d
TERMUX_PKG_BREAKS="libandroid-shmem-dev"
TERMUX_PKG_REPLACES="libandroid-shmem-dev"
TERMUX_PKG_BUILD_IN_SRC=true
