TERMUX_PKG_HOMEPAGE=https://bitmath.org/code/mtdev/
TERMUX_PKG_DESCRIPTION="A stand-alone library which transforms all variants of kernel MT events to the slotted type B protocol"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.1.6
TERMUX_PKG_REVISION=20
TERMUX_PKG_SRCURL=https://bitmath.org/code/mtdev/mtdev-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=1325f389a2f25cd5f5a8ea4d29aad24aa7c3ec30401d679400dd79eb9c0a8dbb
TERMUX_PKG_RM_AFTER_INSTALL="bin/mtdev-test"
