TERMUX_PKG_HOMEPAGE=https://bitmath.org/code/mtdev/
TERMUX_PKG_DESCRIPTION="A stand-alone library which transforms all variants of kernel MT events to the slotted type B protocol"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.1.7"
TERMUX_PKG_SRCURL=https://bitmath.org/code/mtdev/mtdev-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a55bd02a9af4dd266c0042ec608744fff3a017577614c057da09f1f4566ea32c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_RM_AFTER_INSTALL="bin/mtdev-test"
