TERMUX_PKG_HOMEPAGE=https://bitmath.org/code/mtdev/
TERMUX_PKG_DESCRIPTION="A stand-alone library which transforms all variants of kernel MT events to the slotted type B protocol"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=1.1.5
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://bitmath.org/code/mtdev/mtdev-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a662924dd09cf538c8df66514da345e40c3cbfa880cc7262bc3b55ee46d0c1f4
TERMUX_PKG_RM_AFTER_INSTALL="bin/mtdev-test"
