TERMUX_PKG_HOMEPAGE=https://github.com/kraxarn/spotify-qt
TERMUX_PKG_DESCRIPTION="Lightweight Spotify client using Qt"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.0.0"
TERMUX_PKG_SRCURL=https://github.com/kraxarn/spotify-qt/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=358da63abf1bd0528c7b5e53aa72f2a5df265e9b0b4710cafefba0d0f633a672
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt6-qtbase-cross-tools"
