TERMUX_PKG_HOMEPAGE=https://github.com/realh/roxterm
TERMUX_PKG_DESCRIPTION="ROXTerm is a terminal emulator based on the VTE library"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@Yisus7u7"
TERMUX_PKG_VERSION="3.15.3"
TERMUX_PKG_SRCURL=https://github.com/realh/roxterm/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=ec3f7f8c6e088a8b73355da8bb70f6641a000ba681b4f49e25f74c97bad0367a
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="dbus, dbus-glib, glib, gtk3, libcairo, libvte, pango"
TERMUX_PKG_BUILD_DEPENDS="xsltproc"
TERMUX_PKG_BUILD_IN_SRC=true
