diff -uNr v-0.2.2/Makefile v-0.2.2.mod/Makefile
--- v-0.2.2/Makefile	2021-01-22 09:39:44.000000000 +0000
+++ v-0.2.2.mod/Makefile	2021-05-06 11:58:25.054252805 +0000
@@ -82,23 +82,16 @@
 	$(V) self
 endif
 else
-	$(CC) $(CFLAGS) -g -std=gnu99 -w -o $(V) $(VC)/$(VCFILE) -lm -lpthread $(LDFLAGS)
+	$(CC) $(CFLAGS) -g -std=gnu99 -w -o $(V) $(VC)/$(VCFILE) -lm $(LDFLAGS)
 ifdef ANDROID
 	chmod 755 v
 endif
 
-ifdef prod
-	$(V) -prod self
-else
-	$(V) self
-endif
-
 ifndef ANDROID
 	$(MAKE) modules
 endif
 endif
 	@echo "V has been successfully built"
-	@$(V) -version
 
 #clean: clean_tmp
 #git clean -xf
