TERMUX_PKG_HOMEPAGE="https://github.com/haskell/aeson"
TERMUX_PKG_DESCRIPTION="Fast JSON parsing and encoding"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="2.0.3.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/aeson-${TERMUX_PKG_VERSION}/aeson-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="19760a2b84764fa3cee65c63df0c80d45497e2f0c3b95d4e6dc2083b8604b325"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-semialign, haskell-dlist, haskell-attoparsec, haskell-strict, haskell-time-compat, haskell-unordered-containers, haskell-quickcheck, haskell-onetuple, haskell-tagged, haskell-th-abstraction, haskell-indexed-traversable, haskell-vector, haskell-data-fix, haskell-primitive, haskell-base-compat-batteries, haskell-scientific, haskell-uuid-types, haskell-witherable, haskell-hashable, haskell-these, haskell-text-short"
