TERMUX_PKG_HOMEPAGE="https://github.com/haskell/aeson"
TERMUX_PKG_DESCRIPTION="Fast JSON parsing and encoding"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=2.1.1.0
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/aeson-${TERMUX_PKG_VERSION}/aeson-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=a3ae978d67cd8554a6dc11d1e5a4c46280dc90bbc50f3a8787fdd2278524b6ad
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-semialign, haskell-dlist, haskell-attoparsec, haskell-strict, haskell-time-compat, haskell-unordered-containers, haskell-quickcheck, haskell-onetuple, haskell-tagged, haskell-th-abstraction, haskell-indexed-traversable, haskell-vector, haskell-data-fix, haskell-primitive, haskell-base-compat-batteries, haskell-scientific, haskell-uuid-types, haskell-witherable, haskell-hashable, haskell-these, haskell-text-short"
