TERMUX_PKG_HOMEPAGE="https://invent.kde.org/plasma/oxygen-sounds"
TERMUX_PKG_DESCRIPTION="The Oxygen Sound Theme by KDE"
TERMUX_PKG_LICENSE="LGPL-2.0-or-later"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="6.5.4"
TERMUX_PKG_SRCURL="https://download.kde.org/stable/plasma/${TERMUX_PKG_VERSION}/oxygen-sounds-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256="09587f178b70a5d16ace4937ca4a157f3bbd4a37c25415ed821510168bf9c998"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules"
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DKDE_INSTALL_QMLDIR=lib/qt6/qml
-DKDE_INSTALL_QTPLUGINDIR=lib/qt6/plugins
"
