TERMUX_SUBPKG_DESCRIPTION="units_cur Python script"
TERMUX_SUBPKG_INCLUDE="
bin/units_cur
"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_DEPENDS="python, python-pip"
TERMUX_SUBPKG_BREAKS="units (<< 2.22)"
TERMUX_SUBPKG_REPLACES="units (<< 2.22)"
TERMUX_SUBPKG_PYTHON_RUNTIME_DEPS="requests"
