TERMUX_PKG_HOMEPAGE=https://www.blosc.org
TERMUX_PKG_DESCRIPTION="A blocking, shuffling and loss-less compression library"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_LICENSE_FILE="\
LICENSES/BITSHUFFLE.txt
LICENSES/BLOSC.txt
LICENSES/FASTLZ.txt
LICENSES/LZ4.txt
LICENSES/SNAPPY.txt
LICENSES/STDINT.txt
LICENSES/ZLIB.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.21.1
TERMUX_PKG_SRCURL=https://github.com/Blosc/c-blosc/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=f387149eab24efa01c308e4cba0f59f64ccae57292ec9c794002232f7903b55b
TERMUX_PKG_DEPENDS="libsnappy, zstd"
