TERMUX_PKG_HOMEPAGE=https://github.com/kiwix/libkiwix
TERMUX_PKG_DESCRIPTION="A library that contains a lot of things used by other kiwix programs"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="13.0.0"
TERMUX_PKG_SRCURL=https://github.com/kiwix/libkiwix/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=26c5da2283505265d69dd7c6e1f1a56539acff3278bc86aaa7c44641b82a3fa8
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, libcurl, libicu, libmicrohttpd, libpugixml, libxapian, libzim, zlib"
TERMUX_PKG_BUILD_DEPENDS="googletest, kainjow-mustache"
