TERMUX_PKG_HOMEPAGE=https://github.com/kiwix/libkiwix
TERMUX_PKG_DESCRIPTION="A library that contains a lot of things used by other kiwix programs"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="14.2.0"
TERMUX_PKG_SRCURL="https://github.com/kiwix/libkiwix/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=244b69120d132de3079774ee439f9adfb7b556e88b9ef6ce5300f37dfc3737bc
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, libcurl, libicu, libmicrohttpd, libpugixml, libxapian, libzim, zlib"
TERMUX_PKG_BUILD_DEPENDS="googletest, kainjow-mustache"
