TERMUX_PKG_HOMEPAGE=https://github.com/kiwix/libkiwix
TERMUX_PKG_DESCRIPTION="A library that contains a lot of things used by other kiwix programs"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="14.0.0"
TERMUX_PKG_SRCURL=https://github.com/kiwix/libkiwix/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=dae329ebc08ff510daa50b42de71366bf063813e29bf1c09cc49335d90f32094
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, libcurl, libicu, libmicrohttpd, libpugixml, libxapian, libzim, zlib"
TERMUX_PKG_BUILD_DEPENDS="googletest, kainjow-mustache"
