TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/base-compat-batteries"
TERMUX_PKG_DESCRIPTION="base-compat with extra batteries"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.12.2
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base-compat-batteries-${TERMUX_PKG_VERSION}/base-compat-batteries-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=ede9092e07f904e0759160bf1ecd3fb7eb043bae6dc89a37c3dc94829ec5eb99
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-compat, haskell-onetuple"
