TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/base-compat-batteries"
TERMUX_PKG_DESCRIPTION="base-compat with extra batteries"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.12.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base-compat-batteries-${TERMUX_PKG_VERSION}/base-compat-batteries-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="f98f3cdd8231edb4826744904d61f7672b9b628c7072c45684d3f7f1f55d838b"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-compat, haskell-onetuple"
