TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/regex-posix"
TERMUX_PKG_DESCRIPTION="POSIX Backend for 'Text.Regex' (regex-base)"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.96.0.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/regex-posix-${TERMUX_PKG_VERSION}/regex-posix-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="c7827c391919227711e1cff0a762b1678fd8739f9c902fc183041ff34f59259c"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-regex-base"
