TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/lukko"
TERMUX_PKG_DESCRIPTION="File locking"
TERMUX_PKG_LICENSE="GPL-2.0, GPL-3.0, BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.1.3"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/lukko-${TERMUX_PKG_VERSION}/lukko-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="a80efb60cfa3dae18682c01980d76d5f7e413e191cd186992e1bf7388d48ab1f"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
