TERMUX_PKG_HOMEPAGE=https://github.com/bdwgc/libatomic_ops
TERMUX_PKG_DESCRIPTION="Provides semi-portable access to hardware-provided atomic memory update operations"
TERMUX_PKG_LICENSE="GPL-2.0, MIT"
TERMUX_PKG_LICENSE_FILE="README.md, LICENSE"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="7.10.0"
TERMUX_PKG_SRCURL=https://github.com/bdwgc/libatomic_ops/releases/download/v${TERMUX_PKG_VERSION}/libatomic_ops-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0db3ebff755db170f65e74a64ec4511812e9ee3185c232eeffeacd274190dfb0
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
