TERMUX_PKG_HOMEPAGE=https://gnome.pages.gitlab.gnome.org/blueprint-compiler/
TERMUX_PKG_DESCRIPTION="Markup language for GTK user interfaces"
TERMUX_PKG_LICENSE="LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.19.0"
TERMUX_PKG_SRCURL=https://download.gnome.org/sources/blueprint-compiler/${TERMUX_PKG_VERSION%.*}/blueprint-compiler-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=22868d1d2a5e2bd78b901d51dda1f227f3471000e83596a49d57c5f88905f71a
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="gobject-introspection, python, pygobject"
