TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="ICE authority file utility"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.0.9
TERMUX_PKG_SRCURL=https://www.x.org/archive/individual/app/iceauth-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=2cb9dfcb545683af77fb1029bea3fc52dcc8a0666f7b8b2d7373b6ed4c408c05
TERMUX_PKG_DEPENDS="libice"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
