TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/Diff"
TERMUX_PKG_DESCRIPTION="O(ND) diff algorithm in haskell."
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.4.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/Diff-${TERMUX_PKG_VERSION}/Diff-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="fd5e4aaac7219bcbb14834fb8580ebe0aae905958d0ad74f5338ea290b372670"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
