TERMUX_PKG_HOMEPAGE="https://curl.se/trurl/"
TERMUX_PKG_DESCRIPTION="trurl is a command line tool that parses and manipulates URLs"
TERMUX_PKG_LICENSE="curl"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.14"
TERMUX_PKG_SRCURL="https://github.com/curl/trurl/archive/trurl-$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=5080ce71984fc620c1d12010c70c22e8020aeeba7009afcdfce7a9ea40caa4d2
TERMUX_PKG_DEPENDS="libcurl"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+"
