TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/ocrad/ocrad.html
TERMUX_PKG_DESCRIPTION="Optical Character Recognition program based on a feature extraction method"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.28
TERMUX_PKG_SRCURL=https://mirrors.kernel.org/gnu/ocrad/ocrad-${TERMUX_PKG_VERSION}.tar.lz
TERMUX_PKG_SHA256=34ccea576dbdadaa5979e6202344c3ff68737d829ca7b66f71c8497d36bbbf2e
TERMUX_PKG_DEPENDS="libc++, libpng"
TERMUX_PKG_BREAKS="ocrad-dev"
TERMUX_PKG_REPLACES="ocrad-dev"
