TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/ocrad/ocrad.html
TERMUX_PKG_DESCRIPTION="Optical Character Recognition program based on a feature extraction method"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_VERSION=0.27
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://mirrors.kernel.org/gnu/ocrad/ocrad-${TERMUX_PKG_VERSION}.tar.lz
TERMUX_PKG_SHA256=a9bfe67e9a040907aff5640dca56392476b6a89e48e37dc94ba846c5b6733b36
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BREAKS="ocrad-dev"
TERMUX_PKG_REPLACES="ocrad-dev"
