TERMUX_PKG_HOMEPAGE=http://libpipeline.nongnu.org/
TERMUX_PKG_DESCRIPTION="C library for manipulating pipelines of subprocesses in a flexible and convenient way"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.5.6
TERMUX_PKG_REVISION=0
TERMUX_PKG_SRCURL=https://download.savannah.gnu.org/releases/libpipeline/libpipeline-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=60fbb9e7dc398528e5f3a776af57bb28ca3fe5d9f0cd8a961ac6cebfe6e9b797
TERMUX_PKG_BREAKS="libpipeline-dev"
TERMUX_PKG_REPLACES="libpipeline-dev"
