TERMUX_PKG_HOMEPAGE=http://libpipeline.nongnu.org/
TERMUX_PKG_DESCRIPTION="C library for manipulating pipelines of subprocesses in a flexible and convenient way"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.5.7
TERMUX_PKG_SRCURL=https://download.savannah.nongnu.org/releases/libpipeline/libpipeline-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=b8b45194989022a79ec1317f64a2a75b1551b2a55bea06f67704cb2a2e4690b0
TERMUX_PKG_BREAKS="libpipeline-dev"
TERMUX_PKG_REPLACES="libpipeline-dev"
