TERMUX_PKG_HOMEPAGE=http://code.kryo.se/iodine
TERMUX_PKG_DESCRIPTION="Tunnel IPv4 data through a DNS server"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.8.0
TERMUX_PKG_SRCURL=https://code.kryo.se/iodine/iodine-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=546e92cf8617f7970ea81c850b1063eb189c68c406d0c6a67e02c55e72e714c6
TERMUX_PKG_DEPENDS="net-tools, zlib"
TERMUX_PKG_EXTRA_MAKE_ARGS="prefix=$TERMUX_PREFIX"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_pre_configure() {
	CPPFLAGS+=" -DANDROID"
	CFLAGS+=" $CPPFLAGS"
	LDFLAGS+=" -lz"
}
