TERMUX_PKG_HOMEPAGE=https://github.com/plougher/squashfs-tools
TERMUX_PKG_DESCRIPTION="Tools for squashfs, a highly compressed read-only filesystem for Linux"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.6.1"
TERMUX_PKG_SRCURL="https://github.com/plougher/squashfs-tools/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=94201754b36121a9f022a190c75f718441df15402df32c2b520ca331a107511c
TERMUX_PKG_DEPENDS="liblz4, liblzma, liblzo, zlib, zstd"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="
INSTALL_PREFIX=${TERMUX_PREFIX}
INSTALL_MANPAGES_DIR=${TERMUX_PREFIX}/share/man/man1
GZIP_SUPPORT=1
LZ4_SUPPORT=1
LZMA_XZ_SUPPORT=1
LZO_SUPPORT=1
USE_PREBUILT_MANPAGES=1
XATTR_SUPPORT=1
XZ_SUPPORT=1
ZSTD_SUPPORT=1
-C squashfs-tools
"
