TERMUX_PKG_HOMEPAGE=https://github.com/lxqt/lxqt-wayland-session
TERMUX_PKG_DESCRIPTION="Files needed for the LXQt Wayland Session"
TERMUX_PKG_LICENSE="BSD 3-Clause, GPL-2.0, GPL-3.0, LGPL-2.1, MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.3.0"
TERMUX_PKG_SRCURL=https://github.com/lxqt/lxqt-wayland-session/releases/download/${TERMUX_PKG_VERSION}/lxqt-wayland-session-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=c8d4d3ad6efe61a23ae5d67ba52d0d3f024f651581e5083145fb7034aa6c8ccf
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_DEPENDS="layer-shell-qt, lxqt-session, qtxdg-tools"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_SUGGESTS="labwc, sway"
