TERMUX_PKG_HOMEPAGE="https://github.com/fumieval/witherable"
TERMUX_PKG_DESCRIPTION="filterable traversable"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.4.2"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/witherable-${TERMUX_PKG_VERSION}/witherable-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="790d2bb274283419173bd89104439860675a9410f70f21912973ecd9098b4104"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-vector, haskell-hashable, haskell-base-orphans, haskell-indexed-traversable-instances, haskell-indexed-traversable, haskell-unordered-containers"
