TERMUX_PKG_HOMEPAGE=https://github.com/max-niederman/ttyper
TERMUX_PKG_DESCRIPTION="Terminal-based typing test"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.0"
TERMUX_PKG_SRCURL=https://github.com/max-niederman/ttyper/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=7922a8f3385f61244e8712c58da1e9cdfde3cc4a210e5d6d26cda80baf53b2c1
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
