TERMUX_PKG_HOMEPAGE=https://github.com/max-niederman/ttyper
TERMUX_PKG_DESCRIPTION="Terminal-based typing test"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.2.2"
TERMUX_PKG_SRCURL=https://github.com/max-niederman/ttyper/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=de168b56dfe71ac24c91c012b2c6bbd30fa5102a15dae53a8566ec2930c6b10e
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
