TERMUX_PKG_HOMEPAGE=https://github.com/max-niederman/ttyper
TERMUX_PKG_DESCRIPTION="Terminal-based typing test"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.2.0"
TERMUX_PKG_SRCURL=https://github.com/max-niederman/ttyper/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=de1d1478c6ac4a7e18eb3b0d2b4a5ad894bed73742e1ac6d404d5da2b493d71f
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
