diff -u -r ../abuild-3.2.0/Makefile ./Makefile
--- ../abuild-3.2.0/Makefile	2018-06-22 07:24:10.000000000 +0000
+++ ./Makefile	2018-11-18 01:32:10.950452195 +0000
@@ -95,7 +95,6 @@
 	for i in $(USR_BIN_FILES); do\
 		install -m 755 $$i $(DESTDIR)/$(bindir)/$$i;\
 	done
-	chmod 4111 $(DESTDIR)/$(prefix)/bin/abuild-sudo
 	for i in adduser addgroup apk; do \
 		ln -fs abuild-sudo $(DESTDIR)/$(bindir)/abuild-$$i; \
 	done
