--- ../Makefile.orig	2018-05-15 18:08:02.956789845 +0000
+++ ./Makefile	2018-05-15 18:29:20.181951320 +0000
@@ -16,10 +16,10 @@
 ZLIB=
 
 # Support for resolving ID's by DNS (yes/no, default: detect)
-DNS=
+DNS=no
 
 # Build libpci as a shared library (yes/no; or local for testing; requires GCC)
-SHARED=no
+SHARED=yes
 
 # Use libkmod to resolve kernel modules on Linux (yes/no, default: detect)
 LIBKMOD=
@@ -32,8 +32,8 @@
 ABI_VERSION=.3
 
 # Installation directories
-PREFIX=/usr/local
-SBINDIR=$(PREFIX)/sbin
+PREFIX?=/usr/local
+SBINDIR=$(PREFIX)/bin
 SHAREDIR=$(PREFIX)/share
 IDSDIR=$(SHAREDIR)
 MANDIR:=$(shell if [ -d $(PREFIX)/share/man ] ; then echo $(PREFIX)/share/man ; else echo $(PREFIX)/man ; fi)
@@ -44,10 +44,10 @@
 # Commands
 INSTALL=install
 DIRINSTALL=install -d
-STRIP=-s
-CC=$(CROSS_COMPILE)gcc
-AR=$(CROSS_COMPILE)ar
-RANLIB=$(CROSS_COMPILE)ranlib
+STRIP=
+CC?=$(CROSS_COMPILE)gcc
+AR?=$(CROSS_COMPILE)ar
+RANLIB?=$(CROSS_COMPILE)ranlib
 
 # Base name of the library (overriden on NetBSD, which has its own libpci)
 LIBNAME=libpci
