TERMUX_PKG_HOMEPAGE=https://github.com/silnrsi/graphite
TERMUX_PKG_DESCRIPTION="Font system for multiple languages"
TERMUX_PKG_VERSION=1.3.9
TERMUX_PKG_SRCURL=https://github.com/silnrsi/graphite/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_CHECKTYPE=SHA256
TERMUX_PKG_CHECKSUM=f82f92d86a63da79eba10a37c80d943dce883bd72dbc99ebe5bdb7022d3e2391
TERMUX_PKG_FOLDERNAME=graphite-$TERMUX_PKG_VERSION
TERMUX_PKG_RM_AFTER_INSTALL="bin/gr2fonttest"
