TERMUX_PKG_HOMEPAGE=https://github.com/silnrsi/graphite
TERMUX_PKG_DESCRIPTION="Font system for multiple languages"
TERMUX_PKG_LICENSE="LGPL-2.0"
TERMUX_PKG_VERSION=1.3.13
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://github.com/silnrsi/graphite/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=2f9f609deeddfe2b193502adc8df3b0396694b799a433c36e85fd1242e654cd9
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BREAKS="libgraphite-dev"
TERMUX_PKG_REPLACES="libgraphite-dev"
TERMUX_PKG_RM_AFTER_INSTALL="bin/gr2fonttest"
