TERMUX_SUBPKG_INCLUDE="bin/ share/man/man1/"
TERMUX_SUBPKG_DESCRIPTION="Simple, extensible, embeddable programming language"
TERMUX_SUBPKG_DEPENDS="readline"
TERMUX_SUBPKG_BREAKS="lua (<< 5.3.5-6)"
TERMUX_SUBPKG_REPLACES="lua (<< 5.3.5-6)"
