TERMUX_PKG_HOMEPAGE=http://mhash.sourceforge.net/
TERMUX_PKG_DESCRIPTION="A thread-safe hash library which provides a uniform interface to hash algorithms"
TERMUX_PKG_LICENSE="LGPL-2.0"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=0.9.9.9
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://downloads.sourceforge.net/sourceforge/mhash/mhash-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=56521c52a9033779154432d0ae47ad7198914785265e1f570cee21ab248dfef0
TERMUX_PKG_BREAKS="libmhash-dev"
TERMUX_PKG_REPLACES="libmhash-dev"
TERMUX_PKG_BUILD_IN_SRC=true
