TERMUX_PKG_HOMEPAGE=https://github.com/Hackercompagnion7/devkit
TERMUX_PKG_DESCRIPTION="Automatic bootstrap system for Termux development environments"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Hackercompagnion7 @Hackercompagnion7"
TERMUX_PKG_VERSION="1.0.0"
TERMUX_PKG_SRCURL=https://github.com/Hackercompagnion7/devkit/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=65ae8d7cb1142926817a5f72c987b240f3e379876403d1e8ac4b93c70a8510c8
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="git, curl, wget, nodejs, python, clang, make, cmake, rust, pkg-config, binutils"
TERMUX_PKG_RECOMMENDS="zsh, fish"
TERMUX_PKG_SUGGESTS="diff-so-fancy"
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_make() {
        termux_setup_golang

        cd "$TERMUX_PKG_SRCDIR"

        go build \
                -trimpath \
                -mod=readonly \
                -modcacherw \
                -ldflags "\
                -X github.com/devkit/devkit/cmd.version=${TERMUX_PKG_VERSION} \
                -X github.com/devkit/devkit/cmd.commit=v${TERMUX_PKG_VERSION} \
                -X github.com/devkit/devkit/cmd.buildSource=termux \
                -X 'github.com/devkit/devkit/cmd.buildDate=$(date --date=@${SOURCE_DATE_EPOCH} -u +%Y-%m-%dT%H:%M:%SZ)' \
                " \
                -o devkit .
}

termux_step_make_install() {
        install -Dm700 "$TERMUX_PKG_SRCDIR"/devkit \
                "$TERMUX_PREFIX"/bin/devkit

        # Create devkit config directory
        mkdir -p "$TERMUX_PREFIX"/etc/devkit

        # Install default env.sh template
        cat > "$TERMUX_PREFIX"/etc/devkit/env.sh <<-EOF
                #!/bin/sh
                # devkit environment - sourced from shell RC
                # Auto-generated by devkit package installation
                export DEVKIT_HOME="\$HOME/devkit-workspace"
                export DEVKIT_PREFIX="\$PREFIX"
        EOF

        # Install default env.fish template
        cat > "$TERMUX_PREFIX"/etc/devkit/env.fish <<-EOF
                # devkit environment - sourced from fish config
                # Auto-generated by devkit package installation
                set -gx DEVKIT_HOME "\$HOME/devkit-workspace"
                set -gx DEVKIT_PREFIX "\$PREFIX"
        EOF

        # Install bash completions
        install -Dm644 /dev/null "$TERMUX_PREFIX"/share/bash-completion/completions/devkit

        # Install zsh completions
        install -Dm644 /dev/null "$TERMUX_PREFIX"/share/zsh/site-functions/_devkit

        # Install fish completions
        install -Dm644 /dev/null "$TERMUX_PREFIX"/share/fish/vendor_completions.d/devkit.fish
}

termux_step_create_debscripts() {
        cat <<-POSTINST >./postinst
                #!$TERMUX_PREFIX/bin/sh

                # Create workspace directory
                mkdir -p "\$HOME/devkit-workspace"

                # Generate default config.toml if not present
                if [ ! -f "\$PREFIX/etc/devkit/config.toml" ]; then
                        cat > "\$PREFIX/etc/devkit/config.toml" <<-CONF
                                [meta]
                                version = "$TERMUX_PKG_VERSION"
                                initialized = false
                                arch = "\$(uname -m)"

                                [paths]
                                prefix = "\$PREFIX"
                                home = "\$HOME"
                                bin_dir = "\$PREFIX/bin"
                                etc_dir = "\$PREFIX/etc"
                                workspace = "\$HOME/devkit-workspace"
                                env_file = "\$PREFIX/etc/devkit/env.sh"
                                env_fish = "\$PREFIX/etc/devkit/env.fish"
                                config_file = "\$PREFIX/etc/devkit/config.toml"

                                [shell]
                                active = ""
                                rc_files = []

                                [workspace]
                                base_dir = "\$HOME/devkit-workspace"
                        CONF
                fi

                # Inform user about next steps
                echo ""
                echo "  devkit v$TERMUX_PKG_VERSION installed successfully!"
                echo ""
                echo "  Run 'devkit init' to bootstrap your development environment."
                echo "  Run 'devkit doctor' to check system health."
                echo ""
        POSTINST
}
