TERMUX_PKG_HOMEPAGE=http://isl.gforge.inria.fr/
TERMUX_PKG_DESCRIPTION="Library for manipulating sets and relations of integer points bounded by linear constraints"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_VERSION=0.22.1
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=http://isl.gforge.inria.fr/isl-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=28658ce0f0bdb95b51fd2eb15df24211c53284f6ca2ac5e897acc3169e55b60f
TERMUX_PKG_DEPENDS="libgmp"
TERMUX_PKG_BREAKS="libisl-dev"
TERMUX_PKG_REPLACES="libisl-dev"
