TERMUX_PKG_HOMEPAGE=https://pybind11.readthedocs.io/
TERMUX_PKG_DESCRIPTION="A lightweight header-only library that exposes C++ types in Python and vice versa"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.0.4"
TERMUX_PKG_SRCURL="https://github.com/pybind/pybind11/archive/refs/tags/v${TERMUX_PKG_VERSION}/pybind11-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=74b6a2c2b4573a400cafb6ecbf60c98df300cd3d0041296b913d02b2cbbb2676
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="python"
TERMUX_PKG_BUILD_DEPENDS="boost, eigen"
TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS="setuptools"
TERMUX_PKG_CMAKE_BUILD="Unix Makefiles"
