TERMUX_PKG_HOMEPAGE=https://pybind11.readthedocs.io/
TERMUX_PKG_DESCRIPTION="A lightweight header-only library that exposes C++ types in Python and vice versa"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.0.2"
TERMUX_PKG_SRCURL="https://github.com/pybind/pybind11/archive/refs/tags/v${TERMUX_PKG_VERSION}/pybind11-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=2f20a0af0b921815e0e169ea7fec63909869323581b89d7de1553468553f6a2d
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="python"
TERMUX_PKG_BUILD_DEPENDS="boost, eigen"
TERMUX_PKG_PYTHON_COMMON_BUILD_DEPS="setuptools"
TERMUX_CMAKE_BUILD="Unix Makefiles"
