TERMUX_PKG_HOMEPAGE=https://www.music.mcgill.ca/~gary/rtmidi/
TERMUX_PKG_DESCRIPTION="A set of C++ classes that provides a common API for realtime MIDI input/output"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=6.0.0
TERMUX_PKG_SRCURL=https://github.com/thestk/rtmidi/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ef7bcda27fee6936b651c29ebe9544c74959d0b1583b716ce80a1c6fea7617f0
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_FORCE_CMAKE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DRTMIDI_API_ALSA=OFF
-DRTMIDI_API_JACK=OFF
-DRTMIDI_API_AMIDI=OFF
"
