#!/data/data/com.termux/files/usr/bin/sh

echo
echo "You can find sample configuration files and images"
echo "under \${PREFIX}/share/riscvemu directory."
echo
echo "You can visit https://bellard.org/tinyemu/readme.txt"
echo "to view documentation for riscvemu/tinyemu."
echo

exit 0
