TERMUX_PKG_HOMEPAGE="https://github.com/haskell/vector"
TERMUX_PKG_DESCRIPTION="Efficient Arrays"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.12.3.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/vector-${TERMUX_PKG_VERSION}/vector-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="fb4a53c02bd4d7fdf155c0604da9a5bb0f3b3bfce5d9960aea11c2ae235b9f35"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-primitive"
