TERMUX_PKG_HOMEPAGE="https://github.com/haskell/vector"
TERMUX_PKG_DESCRIPTION="Efficient Arrays"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.13.0.0
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/vector-${TERMUX_PKG_VERSION}/vector-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=c5d3167d15e12f52e00879ddf304a591672a74e369cc47bc5c7fa1d5a8d15b4f
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-primitive"
