TERMUX_PKG_HOMEPAGE="https://cmocka.org/"
TERMUX_PKG_DESCRIPTION="cmocka is an unit testing framework for C"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.0.0"
TERMUX_PKG_SRCURL="https://gitlab.com/cmocka/cmocka/-/archive/cmocka-${TERMUX_PKG_VERSION}/cmocka-cmocka-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=77c425c9e702a06128a03c4dc1f3fa2cb437011659db0b98f53f79a9bbe1ce8e
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
