TERMUX_PKG_HOMEPAGE="https://cmocka.org/"
TERMUX_PKG_DESCRIPTION="cmocka is an unit testing framework for C"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.1.8"
TERMUX_PKG_SRCURL="https://gitlab.com/cmocka/cmocka/-/archive/cmocka-${TERMUX_PKG_VERSION}/cmocka-cmocka-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=0994a7cd6b67c46b1cbfbb56c3b22ac379e1ac26fbe68e9cf7cea259b60e201c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
