TERMUX_PKG_HOMEPAGE=https://github.com/libsdl-org/SDL_ttf
TERMUX_PKG_DESCRIPTION="A library that allows you to use TrueType fonts in SDL applications (version 3)"
TERMUX_PKG_LICENSE="ZLIB"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.2.2"
TERMUX_PKG_SRCURL="https://github.com/libsdl-org/SDL_ttf/releases/download/release-${TERMUX_PKG_VERSION}/SDL3_ttf-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=63547d58d0185c833213885b635a2c0548201cc8f301e6587c0be1a67e1e045d
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="freetype, harfbuzz, sdl3"

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DSDLTTF_VENDORED=OFF
-DSDLTTF_PLUTOSVG=OFF
-DSDLTTF_SAMPLES=OFF
-DSDLTTF_HARFBUZZ=ON
-DSDLTTF_FREETYPE=ON
"
