TERMUX_PKG_HOMEPAGE=http://www.multiprecision.org/
TERMUX_PKG_DESCRIPTION="Library for the arithmetic of complex numbers with arbitrarily high precision"
TERMUX_PKG_LICENSE="LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.3.0
TERMUX_PKG_SRCURL=https://mirrors.kernel.org/gnu/mpc/mpc-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=0e3b12181d37207230f5a7a7ddcfc22abfc5fc9c05825e1a65401a489a432a2a
TERMUX_PKG_DEPENDS="libgmp, libmpfr"
TERMUX_PKG_BREAKS="libmpc-dev"
TERMUX_PKG_REPLACES="libmpc-dev"
