TERMUX_PKG_HOMEPAGE=https://www.multiprecision.org/
TERMUX_PKG_DESCRIPTION="Library for the arithmetic of complex numbers with arbitrarily high precision"
TERMUX_PKG_LICENSE="LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.4.1
TERMUX_PKG_SRCURL="https://mirrors.kernel.org/gnu/mpc/mpc-$TERMUX_PKG_VERSION.tar.xz"
TERMUX_PKG_SHA256=91204cd32f164bd3b7c992d4a6a8ce6519511aadab30f78b6982d0bf8d73e931
TERMUX_PKG_DEPENDS="libgmp, libmpfr"
TERMUX_PKG_BREAKS="libmpc-dev"
TERMUX_PKG_REPLACES="libmpc-dev"
