--- ../Makefile.orig	2019-07-21 08:51:17.175911022 +0000
+++ ./Makefile	2019-07-21 09:35:21.844941292 +0000
@@ -22,8 +22,8 @@
 	@rm -rf build
 
 install:
-	@mkdir -p /usr/local/share/bettercap/caplets
-	@cp bettercap /usr/local/bin/
+	@mkdir -p @TERMUX_PREFIX@/share/bettercap/caplets
+	@cp bettercap @TERMUX_PREFIX@/bin/
 
 docker:
 	@docker build -t bettercap:latest .
