TERMUX_PKG_HOMEPAGE="https://github.com/danvratil/qcoro"
TERMUX_PKG_DESCRIPTION="C++ Coroutines for Qt"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux-user"
TERMUX_PKG_VERSION="0.13.0"
TERMUX_PKG_SRCURL="https://github.com/danvratil/qcoro/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=4bff7513c5c8e301b66308df05795043b1792ed16381a484e5c990171b8ff19e
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtdeclarative, qt6-qtwebsockets"
TERMUX_PKG_BUILD_DEPENDS="cmake, git"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_SYSTEM_NAME=Linux
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
"
