TERMUX_PKG_HOMEPAGE="https://github.com/haskellari/these"
TERMUX_PKG_DESCRIPTION="An either-or-both data type."
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.1.1.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/these-${TERMUX_PKG_VERSION}/these-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="d798c9f56e17def441e8f51e54cc11afdb3e76c6a9d1e9ee154e9a78da0bf508"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-hashable, haskell-assoc"
