TERMUX_PKG_HOMEPAGE=https://mujs.com/
TERMUX_PKG_DESCRIPTION="A lightweight Javascript interpreter designed for embedding in other software"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.3.7
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://codeberg.org/ccxvii/mujs/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=5701ac8314d7cb9c792d620c066d93682a74c43f2a49a8966014de05afec5d6a
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="readline"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="HAVE_READLINE=yes"

termux_step_pre_configure() {
	CFLAGS+=" $CPPFLAGS"
}
