TERMUX_PKG_HOMEPAGE=https://www.zaphoyd.com/websocketpp/
TERMUX_PKG_DESCRIPTION="C++/Boost Asio based websocket client/server library"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.8.2
TERMUX_PKG_SRCURL=https://github.com/zaphoyd/websocketpp/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=6ce889d85ecdc2d8fa07408d6787e7352510750daa66b5ad44aacb47bea76755
TERMUX_PKG_DEPENDS="libasio, openssl, zlib"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DENABLE_CPP11=ON
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTS=OFF
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
