TERMUX_PKG_MAINTAINER="Muhammad Herdiansyah @konimex"
TERMUX_PKG_HOMEPAGE=https://github.com/dylanaraps/neofetch
TERMUX_PKG_DESCRIPTION="Simple system information script"
TERMUX_PKG_DEPENDS="bash"
TERMUX_PKG_VERSION=3.1.0
TERMUX_PKG_SRCURL=https://github.com/dylanaraps/neofetch/archive/${TERMUX_PKG_VERSION}/neofetch-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=db7afe24d859b9c8230c3491640d996701816ddc9cf66f98a5071775e8b4ffe5
TERMUX_PKG_BUILD_IN_SRC=yes
TERMUX_PKG_PLATFORM_INDEPENDENT=yes
