TERMUX_SUBPKG_DESCRIPTION="Rust std for target wasm32-wasi"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_BREAKS="rust (<< 1.74.1-1)"
TERMUX_SUBPKG_REPLACES="rust (<< 1.74.1-1)"
TERMUX_SUBPKG_INCLUDE="
lib/rustlib/wasm32-wasi
"
