TERMUX_PKG_HOMEPAGE=https://github.com/termux/termux-packages
TERMUX_PKG_DESCRIPTION="A metapackage representing base Termux environment"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.0
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_DEPENDS="bash, bzip2, command-not-found, coreutils, curl, dash, debianutils, diffutils, dos2unix, ed, findutils, gawk, grep, gzip, inetutils, less, lsof, nano, net-tools, patch, procps, psmisc, sed, tar, termux-exec, termux-keyring, termux-tools, unzip, util-linux, xz-utils"
TERMUX_PKG_ESSENTIAL=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_METAPACKAGE=true
