TERMUX_PKG_HOMEPAGE=https://github.com/LonnyGomes/hexcurse
TERMUX_PKG_DESCRIPTION="Console hexeditor"
TERMUX_PKG_VERSION=1.60.0
TERMUX_PKG_BUILD_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/LonnyGomes/hexcurse/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_FOLDERNAME=hexcurse-${TERMUX_PKG_VERSION}
TERMUX_PKG_DEPENDS="ncurses"
