TERMUX_PKG_HOMEPAGE=https://kde.org/plasma-desktop
TERMUX_PKG_DESCRIPTION="Plasma Specific Protocols for Wayland"
TERMUX_PKG_LICENSE="LGPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.16.0"
TERMUX_PKG_SRCURL="https://download.kde.org/stable/plasma-wayland-protocols/plasma-wayland-protocols-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=da3fbbe3fa5603f9dc9aabe948a6fc8c3b451edd1958138628e96c83649c1f16
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt6-qtbase"
