TERMUX_PKG_HOMEPAGE="https://github.com/haskellari/these"
TERMUX_PKG_DESCRIPTION="Align and Zip type-classes from the common Semialign ancestor."
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.2.0.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/semialign-${TERMUX_PKG_VERSION}/semialign-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="d900697041ae4b0cca3243273a2b3e80bcf74d937405d6a5ff34dc33ee952132"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-vector, haskell-semigroupoids, haskell-tagged, haskell-hashable, haskell-these, haskell-indexed-traversable-instances, haskell-indexed-traversable, haskell-unordered-containers"
