TERMUX_PKG_HOMEPAGE=https://directory.fsf.org/wiki/Plotutils
TERMUX_PKG_DESCRIPTION="Set of utilities and libraries for plotting."
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="Leonid Pliushch <leonid.pliushch@gmail.com>"
TERMUX_PKG_VERSION=2.6
TERMUX_PKG_REVISION=28
TERMUX_PKG_SRCURL=http://ftp.gnu.org/pub/gnu/plotutils/plotutils-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=4f4222820f97ca08c7ea707e4c53e5a3556af4d8f1ab51e0da6ff1627ff433ab
TERMUX_PKG_DEPENDS="libice, libpng, libsm, libx11, libxaw, libxext, libxmu, libxt, zlib"
