TERMUX_PKG_HOMEPAGE=https://github.com/lxqt/libdbusmenu-lxqt
TERMUX_PKG_DESCRIPTION="A library that provides a Qt implementation of the DBusMenu protocol"
TERMUX_PKG_LICENSE="LGPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.3.0"
TERMUX_PKG_SRCURL="https://github.com/lxqt/libdbusmenu-lxqt/releases/download/${TERMUX_PKG_VERSION}/libdbusmenu-lxqt-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=ada0d14d3a4d9fb0ba344bf078d351046dfd226da1096f866d78167a79243ff9
TERMUX_PKG_DEPENDS="libc++, qt6-qtbase"
TERMUX_PKG_AUTO_UPDATE=true
