TERMUX_PKG_HOMEPAGE=https://github.com/aperezdc/signify
TERMUX_PKG_DESCRIPTION="Lightweight cryptographic signing and verifying tool"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="32"
TERMUX_PKG_SRCURL=https://github.com/aperezdc/signify/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=48cfd7bfe55be01909b37e78045f240b950ea51c954bab205bcdcddc0492dca4
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libbsd"
TERMUX_PKG_BUILD_DEPENDS="libbsd"
TERMUX_PKG_BUILD_IN_SRC=true
