TERMUX_PKG_HOMEPAGE=https://www.gnu.org/software/zile/
TERMUX_PKG_DESCRIPTION="Lightweight clone of the Emacs text editor"
TERMUX_PKG_VERSION=2.4.11
TERMUX_PKG_SRCURL=https://ftp.gnu.org/gnu/zile/zile-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_DEPENDS="libgc, ncurses"

# Host build for man pages generated by help2man, see patch:
TERMUX_PKG_HOSTBUILD=yes
TERMUX_PKG_BUILD_IN_SRC=yes
termux_step_pre_configure () {
        # Required because patch modifies a Makefile.am.
        autoreconf
}
