#!@TERMUX_PREFIX@/bin/bash
set -e
PREFIX="@TERMUX_PREFIX@"

if [[ -d "${PREFIX}/share/fonts" ]]; then
    for dir in $(find "${PREFIX}/share/fonts" -mindepth 1 -type d -printf '%p/\n'); do
        [[ ! -d "${dir}" ]] && continue
        mkfontscale "${dir}"
        mkfontdir "${dir}"
        find "${dir}"fonts.{scale,dir} -maxdepth 0 -size -3c -delete
        rmdir --ignore-fail-on-non-empty "${dir}"
    done
fi

if [ "${1}" = "triggered" ]; then
    exit 0
fi
