TERMUX_PKG_HOMEPAGE=https://embree.github.io
TERMUX_PKG_DESCRIPTION="Collection of high-performance ray tracing kernels"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=4.0.0
TERMUX_PKG_SRCURL=https://github.com/embree/embree/archive/v${TERMUX_PKG_VERSION}/embree-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=bb967241f9516712a9f8e399ed7f756d7baeec3c85c223c0005ede8b95c9fa61
TERMUX_PKG_DEPENDS="libtbb, openimageio"
TERMUX_PKG_BUILD_DEPENDS="libxmu, freeglut, glfw"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DEMBREE_TUTORIALS=OFF
-DEMBREE_MAX_ISA=AVX512SKX
-DEMBREE_RAY_MASK=ON
-DEMBREE_FILTER_FUNCTION=ON
-DEMBREE_ISPC_SUPPORT=OFF
-DEMBREE_BACKFACE_CULLING=OFF
-DEMBREE_IGNORE_CMAKE_CXX_FLAGS=OFF
"
