TERMUX_PKG_HOMEPAGE=https://github.com/cgoldberg/xvfbwrapper
TERMUX_PKG_DESCRIPTION="Python wrapper for controlling Xvfb virtual displays"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="termux"
TERMUX_PKG_VERSION="0.2.34"
TERMUX_PKG_SRCURL=https://files.pythonhosted.org/packages/source/x/xvfbwrapper/xvfbwrapper-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=e7f195f30f0ab4e39c5a66e19e0d0bfee0ce5afb3f49e0ae4e5a491a8417db2a
TERMUX_PKG_DEPENDS="python, xorg-server-xvfb"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_SETUP_PYTHON=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
