TERMUX_SUBPKG_DESCRIPTION=".NET 10.0 Runtime Managed Debug Symbols"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_DEPENDS="dotnet-runtime-10.0"
TERMUX_SUBPKG_INCLUDE=$(cat "${TERMUX_PKG_TMPDIR}"/dotnet-runtime-dbg.txt)
