TERMUX_PKG_HOMEPAGE=https://www.gaia-gis.it/fossil/spatialite-tools
TERMUX_PKG_DESCRIPTION="Collection of tools supporting SpatiaLite"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="5.1.0a"
TERMUX_PKG_SRCURL=https://www.gaia-gis.it/gaia-sins/spatialite-tools-sources/spatialite-tools-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=119e34758e8088cdbb43ed81b4a6eaea88c764b0b7da19001a5514b2545501ce
TERMUX_PKG_DEPENDS="libexpat, libiconv, libspatialite, libsqlite, libxml2"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--disable-readosm --disable-minizip"
