TERMUX_PKG_HOMEPAGE=https://www.gaia-gis.it/fossil/spatialite-tools
TERMUX_PKG_DESCRIPTION="Collection of tools supporting SpatiaLite"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=5.1.0
TERMUX_PKG_SRCURL=https://www.gaia-gis.it/gaia-sins/spatialite-tools-sources/spatialite-tools-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=df3030367c089ca90fa6630897f3f1a280784da29e1ba634f340dba4b08583b5
TERMUX_PKG_DEPENDS="libexpat, libiconv, libspatialite, libsqlite, libxml2"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="--disable-readosm --disable-minizip"
