TERMUX_PKG_HOMEPAGE=http://rkeene.org/oss/freecolor/
TERMUX_PKG_DESCRIPTION="Freecolor is a replacement for Linux that displays free memory graphically"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="COPYING"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.9.3
TERMUX_PKG_REVISION=0
TERMUX_PKG_SRCURL=http://rkeene.org/files/oss/freecolor/freecolor-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=58cda97d444405918f1e15b698a5cb2a72dd152a1d93e3ac23e001634690d6cf
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_BUILD_DEPENDS="procps"
