TERMUX_PKG_HOMEPAGE=https://ssdb.io/
TERMUX_PKG_DESCRIPTION="A Redis compatible NoSQL database stored on disk"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.9.9
TERMUX_PKG_SRCURL=https://github.com/ideawu/ssdb/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=a32009950114984d6e468e10d964b0ef1e846077b69d7c7615715fdfa01aaf6e
TERMUX_PKG_DEPENDS="leveldb, libc++"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="PREFIX=$TERMUX_PREFIX/opt/ssdb"

termux_step_pre_configure() {
	export TARGET_OS=OS_ANDROID_CROSSCOMPILE
}
