TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/contravariant/"
TERMUX_PKG_DESCRIPTION="Contravariant functors"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.5.5"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/contravariant-${TERMUX_PKG_VERSION}/contravariant-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="062fd66580d7aad0b5ba93e644ffa7feee69276ef50f20d4ed9f1deb7642dffa"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-statevar"
