TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/splitmix"
TERMUX_PKG_DESCRIPTION="Fast Splittable PRNG"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.0.4"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/splitmix-${TERMUX_PKG_VERSION}/splitmix-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="6d065402394e7a9117093dbb4530a21342c9b1e2ec509516c8a8d0ffed98ecaa"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
