TERMUX_SUBPKG_DESCRIPTION="Vamp plugin for Rubber Band"
TERMUX_SUBPKG_INCLUDE="lib/vamp/"
TERMUX_SUBPKG_DEPENDS="vamp-plugin-sdk"
TERMUX_SUBPKG_BREAKS="rubberband (<< 3.1.2-1)"
TERMUX_SUBPKG_REPLACES="rubberband (<< 3.1.2-1)"
