TERMUX_SUBPKG_DESCRIPTION="Emscripten-compatible LLVM"
TERMUX_SUBPKG_DEPENDS="libc++"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=false
TERMUX_SUBPKG_INCLUDE="opt/emscripten-llvm"
