TERMUX_PKG_HOMEPAGE="https://github.com/haskell-compat/th-compat"
TERMUX_PKG_DESCRIPTION="Backward- (and forward-)compatible Quote and Code types"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=0.1.4
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/th-compat-${TERMUX_PKG_VERSION}/th-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=d8f97ac14ab47b6b8a7b0fdb4ff95426322ec56badd01652ac15da4a44d4bab8
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
