TERMUX_PKG_HOMEPAGE="https://github.com/haskell-compat/th-compat"
TERMUX_PKG_DESCRIPTION="Backward- (and forward-)compatible Quote and Code types"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.3"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/th-compat-${TERMUX_PKG_VERSION}/th-compat-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="6b5059caf6714f47da92953badf2f556119877e09708c14e206b3ae98b8681c6"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
