TERMUX_PKG_HOMEPAGE=https://github.com/google/cpu_features
TERMUX_PKG_DESCRIPTION="A cross-platform C library to retrieve CPU features (such as available instructions) at runtime"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.8.0"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/google/cpu_features/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=7021729f2db97aa34f218d12727314f23e8b11eaa2d5a907e8426bcb41d7eaac
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_NO_STATICSPLIT=true
