TERMUX_PKG_HOMEPAGE=https://manim.community
TERMUX_PKG_DESCRIPTION="A community-maintained Python framework for creating mathematical animations"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Nguyen Khanh @nguynkhn"
TERMUX_PKG_VERSION="0.19.1"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL="https://codeberg.org/ManimCommunity/manim/archive/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=86a9f226c0fb00f1b476b69fcd6efcb9ba959317e713b896bfe3492ff4bbd44f
TERMUX_PKG_DEPENDS="ffmpeg, libcairo, pango, xorgproto, python-numpy, python-pillow, python-pip, pycairo, python-scipy, python-skia-pathops"
TERMUX_PKG_SUGGESTS="texlive-installer"
TERMUX_PKG_PYTHON_COMMON_DEPS="poetry"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXCLUDED_ARCHES="arm, i686"
