#!/data/data/com.termux/files/usr/bin/sh
set -e

if [ -d "/data/data/com.termux/files/usr/share/applications" ]; then
    update-desktop-database -q
fi

if [ "${1}" = "triggered" ]; then
    exit 0
fi
