TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/resolv"
TERMUX_PKG_DESCRIPTION="Domain Name Service (DNS) lookup via the libresolv standard library routines"
TERMUX_PKG_LICENSE="GPL-2.0, GPL-3.0"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.2.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/resolv-${TERMUX_PKG_VERSION}/resolv-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="81a2bafad484db123cf8d17a02d98bb388a127fd0f822fa022589468a0e64671"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base16-bytestring"
