TERMUX_PKG_HOMEPAGE=https://libmdbx.dqdkfa.ru/
TERMUX_PKG_DESCRIPTION="An extremely fast, compact, powerful, embedded, transactional key-value database"
TERMUX_PKG_LICENSE="OpenLDAP"
TERMUX_PKG_LICENSE_FILE="COPYRIGHT, LICENSE"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.14.4"
TERMUX_PKG_SRCURL=https://github.com/Mithril-mine/libmdbx/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=fb53f23ae6d9ed219b09792b1687b2f48598b95cfd12afb437d9d5e953052c21
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
