TERMUX_PKG_HOMEPAGE="https://github.com/haskell-strict/strict"
TERMUX_PKG_DESCRIPTION="Strict data types and String IO."
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.4.0.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/strict-${TERMUX_PKG_VERSION}/strict-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="dff6abc08ad637e51891bb8b475778c40926c51219eda60fd64f0d9680226241"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-these, haskell-hashable, haskell-assoc"
