TERMUX_PKG_HOMEPAGE=https://github.com/fornwall/utfdecode
TERMUX_PKG_DESCRIPTION="Tool for decoding, encoding and debugging unicode"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.3.4
TERMUX_PKG_REVISION=4
TERMUX_PKG_SRCURL=https://github.com/fornwall/utfdecode/releases/download/v$TERMUX_PKG_VERSION/utfdecode-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=5fd1473f6cf6bdedeb33569c3b0f6823aceda366c714f6a475e2d28767f99b5a
TERMUX_PKG_DEPENDS="libc++"
