"aterm",
" aterm",
"bochs",
" bximage",
" bxhub",
" bochs",
"dbus-glib",
" dbus-binding-tool",
"dbus",
" dbus-monitor",
" dbus-test-tool",
" dbus-send",
" dbus-uuidgen",
" dbus-run-session",
" dbus-cleanup-sockets",
" dbus-daemon",
" dbus-update-activation-environment",
" dbus-launch",
"desktop-file-utils",
" update-desktop-database",
" desktop-file-validate",
" desktop-file-install",
" desktop-file-edit",
"dmenu",
" dmenu",
" dmenu_path",
" dmenu_run",
" stest",
"dosbox",
" dosbox",
"dwm",
" dwm",
"emacs-x",
" ebrowse",
" emacsclient",
" emacs-26.3",
" etags",
" emacs",
"exo",
" exo-preferred-applications",
" exo-desktop-item-edit",
" exo-csource",
" exo-open",
"feh",
" feh",
"feh",
" feh",
"florence",
" florence",
"fltk-editor",
" fltk-editor",
"fltk",
" fltk-config",
" fluid",
"fluxbox",
" fluxbox-generate_menu",
" fbsetbg",
" fluxbox",
" fbrun",
" fluxbox-update_configs",
" fbsetroot",
" fluxbox-remote",
" startfluxbox",
"galculator",
" galculator",
"geany",
" geany",
"gpg-crypter",
" gpg-crypter",
"gtk-update-icon-cache",
" gtk-update-icon-cache",
"gtk-update-icon-cache",
" gtk-update-icon-cache",
"gtk2",
" gtk-builder-convert",
" gtk-demo",
" gtk-query-immodules-2.0",
"gtk2",
" gtk-demo",
" gtk-query-immodules-2.0",
" gtk-builder-convert",
"gtk3",
" gtk3-demo",
" gtk3-widget-factory",
" gtk3-demo-application",
" gtk-query-immodules-3.0",
" gtk-encode-symbolic-svg",
" gtk-launch",
" gtk-builder-tool",
" gtk3-icon-browser",
" gtk-query-settings",
"gtk3",
" gtk3-demo",
" gtk3-widget-factory",
" gtk3-demo-application",
" gtk-query-immodules-3.0",
" gtk-encode-symbolic-svg",
" gtk-launch",
" gtk-builder-tool",
" gtk3-icon-browser",
" gtk-query-settings",
"hexchat",
" hexchat-text",
" hexchat",
"i3",
" i3-with-shmlog",
" i3-config-wizard",
" i3-sensible-terminal",
" i3bar",
" i3-input",
" i3-sensible-editor",
" i3-save-tree",
" i3-dump-log",
" i3-msg",
" i3-dmenu-desktop",
" i3-nagbar",
" i3-sensible-pager",
" i3-migrate-config-to-v4",
" i3",
"i3status",
" i3status",
"imagemagick-x",
" convert",
" composite",
" magick-script",
" import",
" conjure",
" stream",
" animate",
" compare",
" mogrify",
" magick",
" montage",
" display",
" identify",
"imlib2",
" imlib2_view",
" imlib2_colorspace",
" imlib2_show",
" imlib2_grab",
" imlib2_poly",
" imlib2_bumpmap",
" imlib2_test",
" imlib2-config",
" imlib2_conv",
"libart-lgpl",
" libart2-config",
"libcairo-x",
" cairo-trace",
"libfm",
" libfm-pref-apps",
" lxshortcut",
"libglade",
" libglade-convert",
"libnotify",
" notify-send",
"libwayland",
" wayland-scanner",
"libwnck",
" wnckprop",
" wnck-urgency-monitor",
"libxfce4ui",
" xfce4-about",
"libxfce4util",
" xfce4-kiosk-query",
"libxpm",
" cxpm",
" sxpm",
"loqui",
" loqui",
"matchbox-keyboard",
" matchbox-keyboard",
"mpv-x",
" mpv",
"mtpaint",
" mtpaint",
"obconf",
" obconf",
"openbox",
" openbox-session",
" openbox",
" obxprop",
"openttd",
" openttd",
"pango-x",
" pango-view",
" pango-list",
"pango-x",
" pango-view",
" pango-list",
"pango-x",
" pango-view",
" pango-list",
"pcmanfm",
" pcmanfm",
"pinentry-gtk",
" pinentry-curses",
" pinentry-gtk-2",
" pinentry",
"plotutils",
" plot",
" hersheydemo",
" spline",
" tek2plot",
" double",
" ode",
" graph",
" plotfont",
"polybar",
" polybar",
" polybar-msg",
"putty",
" pageant",
" psftp",
" plink",
" pterm",
" puttygen",
" putty",
" pscp",
" puttytel",
"pypanel",
" pypanel",
"qemu-common",
" qemu-pr-helper",
" qemu-edid",
" qemu-keymap",
" virtfs-proxy-helper",
"qemu-system-aarch64",
" qemu-system-aarch64",
"qemu-system-arm",
" qemu-system-arm",
"qemu-system-i386",
" qemu-system-i386",
"qemu-system-riscv32",
" qemu-system-riscv32",
"qemu-system-riscv64",
" qemu-system-riscv64",
"qemu-system-x86_64",
" qemu-system-x86_64",
"qemu-utils",
" qemu-nbd",
" qemu-io",
" qemu-img",
"qgit",
" qgit",
"qt5-base",
" qvkgen",
" moc",
" qlalr",
" uic",
" rcc",
" qmake",
"qt5-declarative-dev",
" qml",
" qmlmin",
" qmlcachegen",
" qmlscene",
" qmllint",
" qmlimportscanner",
" qmltestrunner",
"qt5-tools",
" qtplugininfo",
" qtpaths",
" qtdiag",
" lrelease",
" qtattributionsscanner",
" lupdate",
" lconvert",
"rofi",
" rofi",
" rofi-theme-selector",
" rofi-sensible-terminal",
"sdl2",
" sdl2-config",
"sdl",
" sdl-config",
"shared-mime-info",
" update-mime-database",
"st",
" st",
"termux-x11",
" termux-x11",
"the-powder-toy",
" powder",
" the-powder-toy",
"thunar",
" thunar",
" thunar-settings",
" Thunar",
"tigervnc-viewer",
" vncviewer",
"tigervnc",
" vncserver",
" Xvnc",
" vncpasswd",
" x0vncserver",
" vncconfig",
"transmission-gtk",
" transmission-remote",
" transmission-daemon",
" transmission-cli",
" transmission-gtk",
" transmission-create",
" transmission-show",
" transmission-edit",
"uget",
" uget",
" uget-gtk",
" uget-gtk-1to2",
"vim-gtk",
" gview",
" gvim",
" evim",
" gvimdiff",
" vimdiff",
" rgvim",
" xxd",
" vim",
" vimtutor",
" vi",
" ex",
" rgview",
" eview",
" gvimtutor",
" rvim",
" view",
" rview",
"wireshark-gtk",
" captype",
" mergecap",
" rawshark",
" editcap",
" capinfos",
" dumpcap",
" randpkt",
" idl2wrs",
" mmdbresolve",
" text2pcap",
" tshark",
" wireshark-gtk",
" sharkd",
" reordercap",
"wireshark-gtk",
" captype",
" tshark",
" rawshark",
" wireshark-gtk",
" randpkt",
" mmdbresolve",
" editcap",
" dumpcap",
" capinfos",
" mergecap",
" reordercap",
" text2pcap",
" sharkd",
" idl2wrs",
"x2x",
" x2x",
"xarchiver",
" xarchiver",
"xcompmgr",
" xcompmgr",
"xfce4-panel",
" xfce4-popup-directorymenu",
" xfce4-popup-applicationsmenu",
" xfce4-panel",
" xfce4-popup-windowmenu",
"xfce4-session",
" xfce4-session",
" xfce4-session-settings",
" startxfce4",
" xfce4-session-logout",
" xflock4",
"xfce4-session",
" xfce4-session",
" xfce4-session-settings",
" startxfce4",
" xfce4-session-logout",
" xflock4",
"xfce4-settings",
" xfce4-settings-editor",
" xfce4-mouse-settings",
" xfce4-appearance-settings",
" xfce4-find-cursor",
" xfce4-keyboard-settings",
" xfsettingsd",
" xfce4-mime-settings",
" xfce4-accessibility-settings",
" xfce4-settings-manager",
" xfce4-display-settings",
"xfconf",
" xfconf-query",
"xfdesktop",
" xfdesktop",
" xfdesktop-settings",
"xfwm4",
" xfwm4-workspace-settings",
" xfwm4",
" xfwm4-settings",
" xfwm4-tweaks-settings",
"xorg-font-util",
" ucs2any",
" bdftruncate",
"xorg-iceauth",
" iceauth",
"xorg-luit",
" luit",
"xorg-mkfontscale",
" mkfontdir",
" mkfontscale",
"xorg-server-xvfb",
" Xvfb",
"xorg-twm",
" twm",
"xorg-xauth",
" xauth",
"xorg-xcalc",
" xcalc",
"xorg-xclock",
" xclock",
"xorg-xdpyinfo",
" xdpyinfo",
"xorg-xev",
" xev",
"xorg-xkbcomp",
" xkbcomp",
"xorg-xlsfonts",
" xlsfonts",
"xorg-xmessage",
" xmessage",
"xorg-xrdb",
" xrdb",
"xorg-xsetroot",
" xsetroot",
"xournal",
" xournal",
"xrdp",
" xrdp-sesman",
" xrdp-chansrv",
" xrdp-sesadmin",
" xrdp",
" xrdp-dis",
" xrdp-genkeymap",
" xrdp-keygen",
" xrdp-sesrun",
"xsel",
" xsel",
"xterm",
" xterm",
"xwayland",
" Xwayland",
