TERMUX_PKG_HOMEPAGE=https://github.com/KeithDHedger/Xfce-Theme-Manager
TERMUX_PKG_DESCRIPTION="Integrated theme manager for xfce4"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
TERMUX_PKG_VERSION=3.8
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/KeithDHedger/Xfce-Theme-Manager/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=da4b6b0ea9b9acde30893358ce2c997f298ffc6fac32e84aab6fa141b7bf26eb
TERMUX_PKG_DEPENDS="libcairo, gdk-pixbuf, glib, gtk2, gtk3, libxfce4ui, libxfce4util, unzip"
TERMUX_PKG_BUILD_IN_SRC=true
