TERMUX_PKG_HOMEPAGE=https://dl.matroska.org/downloads/libmatroska/
TERMUX_PKG_DESCRIPTION="Matroska library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.6.3
TERMUX_PKG_SRCURL=https://github.com/Matroska-Org/libmatroska/archive/release-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=0c8c875ae26ac69a722f7fd0f4a4fecb4fdff681f2a165f09c06a40cbf1d0de6
TERMUX_PKG_DEPENDS=libebml
TERMUX_PKG_NO_STATICSPLIT=true
