TERMUX_PKG_HOMEPAGE=https://dl.matroska.org/downloads/libmatroska/
TERMUX_PKG_DESCRIPTION="Matroska library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.7.2"
TERMUX_PKG_SRCURL=https://github.com/Matroska-Org/libmatroska/archive/refs/tags/release-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=ef1104f1d77971ac95a33ae6184656fc5ddb51232ca542c31c31daaa493fe204
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_METHOD=repology
TERMUX_PKG_DEPENDS="libc++, libebml"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
