TERMUX_PKG_HOMEPAGE=http://www.olsr.org/
TERMUX_PKG_DESCRIPTION="An adhoc wireless mesh routing daemon"
TERMUX_PKG_VERSION=0.6.8
TERMUX_PKG_SHA256=692de2eb144f0be2e1dfc5dc5275b6c61b80af080e8f733e0b26b6a860442d27
TERMUX_PKG_DEPENDS="libreadline"
TERMUX_PKG_DEVPACKAGE_DEPENDS="libreadline-dev"
TERMUX_PKG_SRCURL=http://www.olsr.org/releases/0.6/olsrd-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_FOLDERNAME=olsrd-${TERMUX_PKG_VERSION}
TERMUX_PKG_BUILD_IN_SRC=yes
TERMUX_PKG_PLATFORM_INDEPENDENT=yes
TERMUX_NDK_COMPILER_VERSION=4.9
TERMUX_NDK_PLATFORM_LEVEL=21

termux_step_make () {
	make OS=android \
		NDK_BASE=$NDK \
		NDK_COMPILER_VERSION=$TERMUX_NDK_COMPILER_VERSION \
		NDK_PLATFORM_LEVEL=$TERMUX_NDK_PLATFORM_LEVEL \
		PREFIX=$TERMUX_PREFIX \
		build_all
}

termux_step_make_install () {
	make OS=android \
		NDK_BASE=$NDK \
		NDK_COMPILER_VERSION=$TERMUX_NDK_COMPILER_VERSION \
		NDK_PLATFORM_LEVEL=$TERMUX_NDK_PLATFORM_LEVEL \
		PREFIX=$TERMUX_PREFIX \
		install
}

