TERMUX_PKG_HOMEPAGE="https://github.com/jgm/cmark"
TERMUX_PKG_DESCRIPTION="CommonMark parsing and rendering library and program in C"
TERMUX_PKG_VERSION=0.27.1
TERMUX_PKG_SHA256=669b4c19355e8cb90139fdd03b02283b97130e92ea99a104552a2976751446b5
TERMUX_PKG_SRCURL=https://github.com/jgm/cmark/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_KEEP_SHARE_DOC=yes
TERMUX_PKG_FOLDERNAME=cmark-$TERMUX_PKG_VERSION

termux_step_configure () {
	mkdir build
	cd $TERMUX_PKG_BUILDDIR
	cmake -G "Unix Makefiles" $TERMUX_PKG_SRCDIR \
		-DCMAKE_AR=`which ${TERMUX_HOST_PLATFORM}-ar` \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_C_FLAGS="$CFLAGS $CPPFLAGS" \
		-DCMAKE_CROSSCOMPILING=True \
		-DCMAKE_CXX_FLAGS="$CXXFLAGS" \
		-DCMAKE_FIND_ROOT_PATH=$TERMUX_PREFIX \
		-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
		-DCMAKE_INSTALL_PREFIX=$TERMUX_PREFIX \
		-DCMAKE_MAKE_PROGRAM=`which make` \
		-DCMAKE_SKIP_RPATH=ON \
		-DCMAKE_SKIP_INSTALL_RPATH=ON \
		-DCMAKE_SYSTEM_NAME=Linux
}
