TERMUX_PKG_HOMEPAGE=https://mate-settings-daemon.mate-desktop.dev/
TERMUX_PKG_DESCRIPTION="mate-settings-daemon is a fork of gnome-settings-daemon"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_VERSION=1.24.2
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://github.com/mate-desktop/mate-settings-daemon/releases/download/v$TERMUX_PKG_VERSION/mate-settings-daemon-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=8c25b4f8aba69b9a0597e8759f9ef23f12ac0d3153f3f5b5a6d4afd0733f3914
TERMUX_PKG_DEPENDS="gtk3, dbus-glib, mate-desktop"
TERMUX_PKG_RM_AFTER_INSTALL="share/glib-2.0/schemas/gschemas.compiled"
