--- ../Makefile.orig	2020-03-10 20:58:52.384359092 +0100
+++ ./wpa_supplicant/Makefile	2020-03-10 21:19:03.627147971 +0100
@@ -17,9 +17,9 @@
 endif
 endif
 
-export LIBDIR ?= /usr/local/lib/
-export INCDIR ?= /usr/local/include/
-export BINDIR ?= /usr/local/sbin/
+export LIBDIR ?= $(PREFIX)/lib/
+export INCDIR ?= $(PREFIX)/include/
+export BINDIR ?= $(PREFIX)/bin/
 PKG_CONFIG ?= pkg-config
 
 CFLAGS += $(EXTRA_CFLAGS)
@@ -60,7 +60,6 @@
 ALL += libwpa_client.so
 endif
 
-
 all: verify_config $(ALL) dynamic_eap_methods
 
 verify_config:
@@ -155,16 +154,6 @@
 OBJS += ../src/utils/$(CONFIG_ELOOP).o
 OBJS_c += ../src/utils/$(CONFIG_ELOOP).o
 
-ifndef CONFIG_OSX
-ifeq ($(CONFIG_ELOOP), eloop)
-# Using glibc < 2.17 requires -lrt for clock_gettime()
-# OS X has an alternate implementation
-LIBS += -lrt
-LIBS_c += -lrt
-LIBS_p += -lrt
-endif
-endif
-
 ifdef CONFIG_ELOOP_POLL
 CFLAGS += -DCONFIG_ELOOP_POLL
 endif
