diff --git a/wpa_supplicant/Makefile b/wpa_supplicant/Makefile
index cb66def..e70d74b 100644
--- a/wpa_supplicant/Makefile
+++ b/wpa_supplicant/Makefile
@@ -30,9 +30,9 @@ LIBS_p := $(LIBS)
 endif
 endif
 
-export LIBDIR ?= /usr/local/lib
-export INCDIR ?= /usr/local/include
-export BINDIR ?= /usr/local/sbin
+export LIBDIR ?= $(PREFIX)/lib/
+export INCDIR ?= $(PREFIX)/include/
+export BINDIR ?= $(PREFIX)/bin/
 PKG_CONFIG ?= pkg-config
 
 CFLAGS += $(EXTRA_CFLAGS)
