TERMUX_PKG_HOMEPAGE=https://github.com/Matroska-Org/libebml
TERMUX_PKG_DESCRIPTION="Extensible Binary Meta Language library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.4.7"
TERMUX_PKG_SRCURL=https://github.com/Matroska-Org/libebml/archive/refs/tags/release-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=c55c5528e7510bc41b574dcac47bc6e3503fb3b9e78ad8c42541bf07d5ed71a9
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_METHOD=repology
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
