TERMUX_PKG_HOMEPAGE=https://github.com/carlobaldassi/liblqr
TERMUX_PKG_DESCRIPTION="Provides a C/C++ API for performing non-uniform resizing of images by the seam-carving technique"
TERMUX_PKG_LICENSE="GPL-3.0, LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.4.3"
TERMUX_PKG_SRCURL=https://github.com/carlobaldassi/liblqr/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=64b0c4ac76d39cca79501b3f53544af3fc5f72b536ac0f28d2928319bfab6def
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="glib"
