TERMUX_PKG_HOMEPAGE=https://docs.xfce.org/xfce/tumbler/start
TERMUX_PKG_DESCRIPTION="Tumbler is a D-Bus service for applications to request thumbnails for various URI schemes and MIME type"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
_MAJOR_VERSION=4.18
TERMUX_PKG_VERSION=${_MAJOR_VERSION}.0
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/xfce/tumbler/${_MAJOR_VERSION}/tumbler-$TERMUX_PKG_VERSION.tar.bz2
TERMUX_PKG_SHA256=4087f3af4ef31271d3f315421a2f1fe67e4fda7ad60bbab1f073627914dfcf00
TERMUX_PKG_DEPENDS="freetype, gdk-pixbuf, glib, libcurl, libjpeg-turbo, libpng, libxfce4util"
