TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/OneTuple"
TERMUX_PKG_DESCRIPTION="Singleton Tuple"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.3.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/OneTuple-${TERMUX_PKG_VERSION}/OneTuple-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="98853682d52fb4cc37a45cd186fbd77cf2565d3df5171acc4cf026427e103eef"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-base-orphans, haskell-hashable"
