TERMUX_PKG_HOMEPAGE="https://github.com/haskell-unordered-containers/hashable"
TERMUX_PKG_DESCRIPTION="A class for types that can be converted to a hash value"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=1.4.1.0
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/hashable-${TERMUX_PKG_VERSION}/hashable-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=e1b305c280e66ad827edeaedd6933b9fc4174f626882877eab2a08344e665e87
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
