TERMUX_PKG_HOMEPAGE="http://github.com/haskell-unordered-containers/hashable"
TERMUX_PKG_DESCRIPTION="A class for types that can be converted to a hash value"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.3.5.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/hashable-${TERMUX_PKG_VERSION}/hashable-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="baaad82cd4271b197016bdbe76f22d5c3d3913fe38534cec7d817db9bae19886"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
