TERMUX_PKG_HOMEPAGE=https://tls.mbed.org/
TERMUX_PKG_DESCRIPTION="Light-weight cryptographic and SSL/TLS library"
TERMUX_PKG_MAINTAINER="Andy Li @andyli"
TERMUX_PKG_VERSION=2.14.0
TERMUX_PKG_SHA256=3e733731eca47ffdc85330cde47774e075f5d1326e413555713dec8bf9c31eb3
TERMUX_PKG_SRCURL=https://github.com/ARMmbed/mbedtls/archive/mbedtls-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_STATIC_MBEDTLS_LIBRARY=OFF
-DUSE_SHARED_MBEDTLS_LIBRARY=ON
-DENABLE_TESTING=OFF
-DENABLE_PROGRAMS=OFF
"
