TERMUX_PKG_HOMEPAGE=https://tls.mbed.org/
TERMUX_PKG_DESCRIPTION="Light-weight cryptographic and SSL/TLS library"
TERMUX_PKG_VERSION=2.12.0
TERMUX_PKG_SHA256=a2bed048f41a19ec7b4dd2e96649145bbd68a6955c3b51aeb7ccbf8908c3ce97
TERMUX_PKG_SRCURL=https://tls.mbed.org/download/mbedtls-$TERMUX_PKG_VERSION-apache.tgz
TERMUX_PKG_MAINTAINER="Andy Li @andyli"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_STATIC_MBEDTLS_LIBRARY=OFF
-DUSE_SHARED_MBEDTLS_LIBRARY=ON
-DENABLE_TESTING=OFF
-DENABLE_PROGRAMS=OFF
"
