TERMUX_PKG_HOMEPAGE=https://tls.mbed.org/
TERMUX_PKG_DESCRIPTION="Light-weight cryptographic and SSL/TLS library"
TERMUX_PKG_MAINTAINER="Andy Li @andyli"
TERMUX_PKG_VERSION=2.14.1
TERMUX_PKG_SHA256=547943e7a4e79d3f71603087117d28cf4c03b2de6fc0c7cd79f92ad3188b3f80
TERMUX_PKG_SRCURL=https://github.com/ARMmbed/mbedtls/archive/mbedtls-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DUSE_STATIC_MBEDTLS_LIBRARY=OFF
-DUSE_SHARED_MBEDTLS_LIBRARY=ON
-DENABLE_TESTING=OFF
-DENABLE_PROGRAMS=OFF
"
