TERMUX_PKG_HOMEPAGE=https://github.com/radareorg/acr
TERMUX_PKG_DESCRIPTION="A fully compatible autoconf replacement"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.2.4"
TERMUX_PKG_SRCURL=https://github.com/radareorg/acr/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=1b2d30172e8fd2ceb9b2e9d5e9634cce53e24f9e79fb15e1695017bf653efb8b
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="dash"
TERMUX_PKG_BUILD_IN_SRC=true
