TERMUX_PKG_HOMEPAGE=https://www.freedesktop.org/wiki/Software/icon-theme/
TERMUX_PKG_DESCRIPTION="Freedesktop.org Hicolor icon theme"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.18
TERMUX_PKG_SRCURL=https://gitlab.freedesktop.org/xdg/default-icon-theme/-/archive/v${TERMUX_PKG_VERSION}/default-icon-theme-v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=9227ec70c6b59a715a18dcedbed590cb08edc9eadb73fb2b0a57034e15c18f36
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_AUTO_UPDATE=true
