TERMUX_PKG_HOMEPAGE=https://pugixml.org/
TERMUX_PKG_DESCRIPTION="Light-weight, simple and fast XML parser for C++ with XPath support"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.16"
TERMUX_PKG_SRCURL=https://github.com/zeux/pugixml/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=357bcab8877dc9943f355d3a72daba1b053238ba955f50fa81586afb65090219
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
