TERMUX_PKG_HOMEPAGE=https://github.com/termux/termux-exec
TERMUX_PKG_DESCRIPTION="A LD_PRELOAD shared library for proper functioning of the Termux execution environment"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1:2.0.0

# FIXME: Fix urls
TERMUX_PKG_SRCURL=git+https://github.com/termux/termux-exec
TERMUX_PKG_GIT_BRANCH="2.0.0-prerelease"

#TERMUX_PKG_SRCURL=git+https://github.com/termux-play-store/termux-exec
#TERMUX_PKG_GIT_BRANCH="master"

#TERMUX_PKG_SRCURL=file:///home/builder/termux-packages/sources/termux-exec
#TERMUX_PKG_SHA256=SKIP_CHECKSUM

#TERMUX_PKG_SRCURL=https://github.com/termux/termux-exec/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
#TERMUX_PKG_SHA256=xxx

TERMUX_PKG_ESSENTIAL=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_MAKE_ARGS="TERMUX_EXEC_PKG__VERSION=${TERMUX_PKG_VERSION} TERMUX_EXEC_PKG__ARCH=${TERMUX_ARCH} \
TERMUX__NAME=${TERMUX__NAME} TERMUX__LNAME=${TERMUX__LNAME} \
TERMUX_APP__PACKAGE_NAME=${TERMUX_APP__PACKAGE_NAME} TERMUX_APP__DATA_DIR=${TERMUX_APP__DATA_DIR} \
TERMUX__ROOTFS=${TERMUX__ROOTFS} TERMUX__PREFIX=${TERMUX__PREFIX} \
TERMUX_ENV__S_ROOT=${TERMUX_ENV__S_ROOT} \
TERMUX_ENV__SS_TERMUX=${TERMUX_ENV__SS_TERMUX} TERMUX_ENV__S_TERMUX=${TERMUX_ENV__S_TERMUX} \
TERMUX_ENV__SS_TERMUX_APP=${TERMUX_ENV__SS_TERMUX_APP} TERMUX_ENV__S_TERMUX_APP=${TERMUX_ENV__S_TERMUX_APP} \
TERMUX_ENV__SS_TERMUX_API_APP=${TERMUX_ENV__SS_TERMUX_API_APP} TERMUX_ENV__S_TERMUX_API_APP=${TERMUX_ENV__S_TERMUX_API_APP} \
TERMUX_ENV__SS_TERMUX_ROOTFS=${TERMUX_ENV__SS_TERMUX_ROOTFS} TERMUX_ENV__S_TERMUX_ROOTFS=${TERMUX_ENV__S_TERMUX_ROOTFS} \
TERMUX_ENV__SS_TERMUX_CORE=${TERMUX_ENV__SS_TERMUX_CORE} TERMUX_ENV__S_TERMUX_CORE=${TERMUX_ENV__S_TERMUX_CORE} \
TERMUX_ENV__SS_TERMUX_CORE__TESTS=${TERMUX_ENV__SS_TERMUX_CORE__TESTS} TERMUX_ENV__S_TERMUX_CORE__TESTS=${TERMUX_ENV__S_TERMUX_CORE__TESTS} \
TERMUX_ENV__SS_TERMUX_EXEC=${TERMUX_ENV__SS_TERMUX_EXEC} TERMUX_ENV__S_TERMUX_EXEC=${TERMUX_ENV__S_TERMUX_EXEC} \
TERMUX_ENV__SS_TERMUX_EXEC__TESTS=${TERMUX_ENV__SS_TERMUX_EXEC__TESTS} TERMUX_ENV__S_TERMUX_EXEC__TESTS=${TERMUX_ENV__S_TERMUX_EXEC__TESTS} \
TERMUX_APP__NAMESPACE=${TERMUX_APP__NAMESPACE} \
TERMUX_APP__SHELL_ACTIVITY__COMPONENT_NAME=${TERMUX_APP__SHELL_ACTIVITY__COMPONENT_NAME} TERMUX_APP__SHELL_SERVICE__COMPONENT_NAME=${TERMUX_APP__SHELL_SERVICE__COMPONENT_NAME}"

termux_step_post_massage() {
	# Hack to compile runtime-binary-tests for api level 28 if default (currently 24) is less than it.
	if [[ "$TERMUX_PKG_API_LEVEL" -lt 28 ]]; then
		export TERMUX_PKG_API_LEVEL=28
		termux_step_setup_toolchain

		local QUIET_BUILD=
		if [ "$TERMUX_QUIET_BUILD" = true ]; then
			QUIET_BUILD="-s"
		fi

		echo "Building termux-exec runtime-binary-tests for TERMUX_PKG_API_LEVEL '$TERMUX_PKG_API_LEVEL'"
		cd "$TERMUX_PKG_BUILDDIR"
		make -j $TERMUX_PKG_MAKE_PROCESSES $QUIET_BUILD $TERMUX_PKG_EXTRA_MAKE_ARGS TERMUX_EXEC__TESTS__API_LEVEL=28 build-runtime-binary-tests

		local TERMUX_EXEC__TESTS__TESTS_PATH="$TERMUX_PKG_MASSAGEDIR/$TERMUX_PREFIX/libexec/installed-tests/termux-exec"

		install -m700 build/usr/libexec/installed-tests/termux-exec/runtime-binary-tests-fsanitize28 "$TERMUX_EXEC__TESTS__TESTS_PATH/runtime-binary-tests-fsanitize28"
		$TERMUX_ELF_CLEANER --api-level 28 "$TERMUX_EXEC__TESTS__TESTS_PATH/runtime-binary-tests-fsanitize28"

		install -m700 build/usr/libexec/installed-tests/termux-exec/runtime-binary-tests-nofsanitize28 "$TERMUX_EXEC__TESTS__TESTS_PATH/runtime-binary-tests-nofsanitize28"
		$TERMUX_ELF_CLEANER --api-level 28 "$TERMUX_EXEC__TESTS__TESTS_PATH/runtime-binary-tests-nofsanitize28"
	fi
}
