TERMUX_PKG_HOMEPAGE="https://wiki.haskell.org/Regular_expressions"
TERMUX_PKG_DESCRIPTION="Pure Haskell Tagged DFA Backend for 'Text.Regex' (regex-base)"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <alok@termux.org>"
TERMUX_PKG_VERSION=1.3.2
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/regex-tdfa-${TERMUX_PKG_VERSION}/regex-tdfa-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=2660d7dc5f00718c39454c844d354dea26d605db9864f80951efad5f7284dfd1
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-regex-base"
