TERMUX_PKG_HOMEPAGE="https://wiki.haskell.org/Regular_expressions"
TERMUX_PKG_DESCRIPTION="Pure Haskell Tagged DFA Backend for 'Text.Regex' (regex-base)"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.3.1.2"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/regex-tdfa-${TERMUX_PKG_VERSION}/regex-tdfa-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="c47a78c9da532ba0883868a1e34427318cba3cccc8e42f995834c74eea286a62"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-regex-base"
