TERMUX_PKG_HOMEPAGE=https://github.com/LinusDierheimer/fastfetch
TERMUX_PKG_DESCRIPTION="A neofetch-like tool for fetching system information and displaying them in a pretty way"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.6.2"
TERMUX_PKG_SRCURL=https://github.com/LinusDierheimer/fastfetch/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=55e9bea01ec6d26fcf24287844c82f59f1dd938b3ea1b8b0b787101b44d7d4a0
TERMUX_PKG_AUTO_UPDATE=true

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DTARGET_DIR_ROOT=${TERMUX_PREFIX}
-DTARGET_DIR_USR=${TERMUX_PREFIX}
-DTARGET_DIR_HOME=${TERMUX_ANDROID_HOME}
-DCMAKE_INSTALL_SYSCONFDIR=${TERMUX_PREFIX}/etc
-DENABLE_LIBPCI=OFF
-DENABLE_VULKAN=OFF
-DENABLE_WAYLAND=OFF
-DENABLE_XCB_RANDR=OFF
-DENABLE_XCB=OFF
-DENABLE_XRANDR=OFF
-DENABLE_X11=OFF
-DENABLE_GIO=OFF
-DENABLE_DCONF=OFF
-DENABLE_DBUS=OFF
-DENABLE_XFCONF=OFF
-DENABLE_RPM=OFF
"
