TERMUX_PKG_HOMEPAGE=https://github.com/LinusDierheimer/fastfetch
TERMUX_PKG_DESCRIPTION="A neofetch-like tool for fetching system information and displaying them in a pretty way"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.5"
TERMUX_PKG_SRCURL=https://github.com/LinusDierheimer/fastfetch/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=bb631801e21e30d2181fc95dd20d4cb752c2a1334b8a90b40219c4e7cafdc3d9
TERMUX_PKG_AUTO_UPDATE=true

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DTARGET_DIR_ROOT=${TERMUX_PREFIX}
-DTARGET_DIR_HOME=${TERMUX_ANDROID_HOME}
-DENABLE_LIBPCI=OFF
-DENABLE_VULKAN=OFF
-DENABLE_WAYLAND=OFF
-DENABLE_XCB_RANDR=OFF
-DENABLE_XCB=OFF
-DENABLE_XRANDR=OFF
-DENABLE_X11=OFF
-DENABLE_GIO=OFF
-DENABLE_DCONF=OFF
-DENABLE_DBUS=OFF
-DENABLE_XFCONF=OFF
-DENABLE_RPM=OFF
"
