TERMUX_PKG_HOMEPAGE="https://github.com/RyanGlScott/echo"
TERMUX_PKG_DESCRIPTION="A cross-platform, cross-console way to handle echoing terminal input"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.4"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/echo-${TERMUX_PKG_VERSION}/echo-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="c9fe1bf2904825a65b667251ec644f197b71dc5c209d2d254be5de3d496b0e43"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
