TERMUX_PKG_HOMEPAGE='https://sinusoid.es/immer'
TERMUX_PKG_DESCRIPTION='Postmodern immutable and persistent data structures for C++'
TERMUX_PKG_LICENSE="BSL-1.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.8.1
TERMUX_PKG_SRCURL=https://github.com/arximboldi/immer/archive/v${TERMUX_PKG_VERSION}/immer-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=de8411c84830864604bb685dc8f2e3c0dbdc40b95b2f6726092f7dcc85e75209
TERMUX_PKG_DEPENDS="catch2, cmake"
TERMUX_PKG_BUILD_DEPENDS="catch2, cmake"
TERMUX_PKG_AUTO_UPDATE=true
