TERMUX_PKG_HOMEPAGE=https://github.com/wdas/ptex
TERMUX_PKG_DESCRIPTION="Per-Face Texture Mapping for Production Rendering"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.4.3"
TERMUX_PKG_SRCURL=https://github.com/wdas/ptex/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=435aa2ee1781ff24859bd282b7616bfaeb86ca10604b13d085ada8aa7602ad27
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="libc++, zlib"
