TERMUX_PKG_HOMEPAGE=https://github.com/wdas/ptex
TERMUX_PKG_DESCRIPTION="Per-Face Texture Mapping for Production Rendering"
TERMUX_PKG_LICENSE="BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.5.2"
TERMUX_PKG_SRCURL=https://github.com/wdas/ptex/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=dd95fbea4b50e9e68fd042f540fb83157a0ff25053066c3439d4527de3621d34
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="libc++, libdeflate"
TERMUX_PKG_BUILD_DEPENDS="libdeflate-static"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_CXX_STANDARD=17
"
