TERMUX_PKG_HOMEPAGE="https://gnupg.org/software/gpgme/index.html"
TERMUX_PKG_DESCRIPTION="Qt bindings for GPGME"
TERMUX_PKG_LICENSE="GPL-2.0-or-later"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.0.0"
TERMUX_PKG_SRCURL="https://github.com/gpg/gpgmeqt/archive/refs/tags/gpgmeqt-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="307572eaf3fe977a6ba28ff41d6573d97de6f008244e787038ffe5ca6b2222da"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP='^gpgmeqt-([0-9.]+)$'
TERMUX_PKG_DEPENDS="gpgmepp, libc++, qt6-qtbase"
