TERMUX_PKG_HOMEPAGE=https://lensfun.github.io/
TERMUX_PKG_DESCRIPTION="Lensfun"
TERMUX_PKG_LICENSE="GPL-3.0, LGPL-3.0"
TERMUX_PKG_MAINTAINER="Gouranga Das Samrat <gouranga.das.khulna@gmail.com>"
TERMUX_PKG_VERSION="0.3.4"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/lensfun/lensfun/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=dafb39c08ef24a0e2abd00d05d7341b1bf1f0c38bfcd5a4c69cf5f0ecb6db112
TERMUX_PKG_DEPENDS="glib, libpng, libxml2"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DBUILD_FOR_SSE=OFF
-DBUILD_FOR_SSE2=OFF
-DINSTALL_PYTHON_MODULE=OFF
"
