TERMUX_PKG_HOMEPAGE="https://github.com/basvandijk/scientific"
TERMUX_PKG_DESCRIPTION="Numbers represented using scientific notation"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.3.7.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/scientific-${TERMUX_PKG_VERSION}/scientific-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="a3a121c4b3d68fb8b9f8c709ab012e48f090ed553609247a805ad070d6b343a9"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-hashable, haskell-integer-logarithms, haskell-primitive"
