TERMUX_PKG_HOMEPAGE=http://www.nongnu.org/lzip/plzip.html
TERMUX_PKG_DESCRIPTION="A massively parallel lossless data compressor based on the lzlib compression library"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.9
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=http://download.savannah.gnu.org/releases/lzip/plzip/plzip-$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=14d8d1db8dde76bdd9060b59d50b2943417eb4c0fbd2b84736546b78fab5f1a7
TERMUX_PKG_DEPENDS="libc++, lzlib"
