TERMUX_PKG_HOMEPAGE=https://github.com/PapirusDevelopmentTeam/papirus-icon-theme
TERMUX_PKG_DESCRIPTION="Papirus is a free and open source icon theme, based on Paper Icon Set"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="20221101"
TERMUX_PKG_SRCURL=https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=071c0ba9e728c0f34e7ee5a434e1107cb252b8aabc81887def3716c7d2a59dec
TERMUX_PKG_DEPENDS="hicolor-icon-theme"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_NO_SHEBANG_FIX=true
TERMUX_PKG_AUTO_UPDATE=true
