diff -u -r ../apk-tools-2.10.1/Makefile ./Makefile
--- ../apk-tools-2.10.1/Makefile	2018-09-10 08:04:03.000000000 +0000
+++ ./Makefile	2018-09-10 21:58:19.631911343 +0000
@@ -10,11 +10,11 @@
 # Default directories
 
 DESTDIR		:=
-SBINDIR		:= /sbin
-LIBDIR		:= /lib
-CONFDIR		:= /etc/apk
-MANDIR		:= /usr/share/man
-DOCDIR		:= /usr/share/doc/apk
+SBINDIR		:= @TERMUX_PREFIX@/bin
+LIBDIR		:= @TERMUX_PREFIX@/lib
+CONFDIR		:= @TERMUX_PREFIX@/etc/apk
+MANDIR		:= @TERMUX_PREFIX@/share/man
+DOCDIR		:= @TERMUX_PREFIX@/share/doc/apk
 
 export DESTDIR SBINDIR LIBDIR CONFDIR MANDIR DOCDIR
 
