TERMUX_PKG_HOMEPAGE=https://www.rarlab.com/
TERMUX_PKG_DESCRIPTION="Tool for extracting files from .rar archives"
TERMUX_PKG_LICENSE="non-free"
TERMUX_PKG_LICENSE_FILE="license.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=6.1.2
TERMUX_PKG_SRCURL=https://www.rarlab.com/rar/unrarsrc-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=3e96421f568e438af6dcdaef717c48eb93b825d97058ebcb173b9bfc57807be3
TERMUX_PKG_DEPENDS="libandroid-support, libc++"
TERMUX_PKG_BUILD_IN_SRC=true
