TERMUX_PKG_HOMEPAGE=https://www.rarlab.com/
TERMUX_PKG_DESCRIPTION="Tool for extracting files from .rar archives"
TERMUX_PKG_LICENSE="non-free"
TERMUX_PKG_LICENSE_FILE="license.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=6.2.4
TERMUX_PKG_SRCURL=https://www.rarlab.com/rar/unrarsrc-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=22e0a37444c6beb194d4dfafdce480d1143547eb1102fd65430e1e9522a545ad
TERMUX_PKG_DEPENDS="libandroid-support, libc++"
TERMUX_PKG_BUILD_IN_SRC=true
