TERMUX_PKG_HOMEPAGE=https://github.com/dimkr/loksh
TERMUX_PKG_DESCRIPTION="A Linux port of OpenBSD's ksh"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com> @xeffyr"
TERMUX_PKG_VERSION=6.5
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/dimkr/loksh/archive/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=afa6dddfe914a3cb4c2f5c6b9da03d30fb549c8cfb4daeff0472fc103696f7a4
TERMUX_PKG_DEPENDS="ncurses"
TERMUX_PKG_BUILD_IN_SRC=true
