TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/text-short"
TERMUX_PKG_DESCRIPTION="Memory-efficient representation of Unicode text strings"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.5"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/text-short-${TERMUX_PKG_VERSION}/text-short-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="a35ec6cde2ada084c1a050dc5885be5ab01f851b93d744cf0facbc1c18002dda"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-hashable"
