TERMUX_PKG_HOMEPAGE=https://www.freedesktop.org/wiki/Software/uchardet/
TERMUX_PKG_DESCRIPTION="An encoding detector library"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="COPYING"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.0.8
TERMUX_PKG_SRCURL=https://www.freedesktop.org/software/uchardet/releases/uchardet-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0
TERMUX_PKG_DEPENDS="libc++"
