TERMUX_PKG_HOMEPAGE=https://fcitx-im.org/
TERMUX_PKG_DESCRIPTION="Fcitx Qt immodule & library"
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="5.1.11"
TERMUX_PKG_SRCURL=https://github.com/fcitx/fcitx5-qt/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=caca4f8e88edbdbad4235f65b532179b163f63b316df87b9e8074c2130fa4715
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="fcitx5, libc++, libwayland, libx11, libxcb, libxkbcommon, qt6-qtbase"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_INSTALL_QT6PLUGINDIR=lib/qt6/plugins
-DENABLE_TEST=OFF
-DENABLE_QT4=OFF
-DENABLE_QT5=OFF
-DENABLE_QT6=ON
-DENABLE_QT6_WAYLAND_WORKAROUND=ON
"
