TERMUX_PKG_HOMEPAGE=https://github.com/signalapp/libsignal-protocol-c
TERMUX_PKG_DESCRIPTION="Signal Protocol C Library"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_VERSION=2.3.3
TERMUX_PKG_MAINTAINER="Oliver Schmidhauser @Neo-Oli"
TERMUX_PKG_SRCURL=https://github.com/signalapp/libsignal-protocol-c/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=c22e7690546e24d46210ca92dd808f17c3102e1344cd2f9a370136a96d22319d
TERMUX_PKG_DEPENDS="openssl"

termux_step_pre_configure() {
    TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DBUILD_SHARED_LIBS=ON"
    TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DM_LIB=$TERMUX_STANDALONE_TOOLCHAIN/sysroot/usr/lib/$TERMUX_HOST_PLATFORM/$TERMUX_PKG_API_LEVEL/libm.so"
}
