#!/data/data/com.termux/files/usr/bin/bash

PACKAGES="autoconf"
PACKAGES+=" automake"
PACKAGES+=" bc"
PACKAGES+=" binutils-gold"
PACKAGES+=" bison"
PACKAGES+=" bzip2"
PACKAGES+=" clang"
PACKAGES+=" cmake"
PACKAGES+=" coreutils"
PACKAGES+=" curl"
PACKAGES+=" diffutils"
PACKAGES+=" ed"
PACKAGES+=" file"
PACKAGES+=" findutils"
PACKAGES+=" flex"
PACKAGES+=" gawk"
PACKAGES+=" gettext"
PACKAGES+=" git"
PACKAGES+=" golang"
PACKAGES+=" gperf"
PACKAGES+=" grep"
PACKAGES+=" gzip"
PACKAGES+=" libtool"
PACKAGES+=" lzip"
PACKAGES+=" lzop"
PACKAGES+=" m4"
PACKAGES+=" make"
PACKAGES+=" ninja"
PACKAGES+=" patch"
PACKAGES+=" perl"
PACKAGES+=" pkg-config"
PACKAGES+=" protobuf"
PACKAGES+=" python"
PACKAGES+=" python2"
PACKAGES+=" rust"
PACKAGES+=" sed"
PACKAGES+=" tar"
PACKAGES+=" texinfo"
PACKAGES+=" unzip"
PACKAGES+=" xz-utils"

apt update
apt dist-upgrade -y
apt install -y $PACKAGES
