TERMUX_PKG_HOMEPAGE=https://github.com/nielssp/csol
TERMUX_PKG_DESCRIPTION="A small collection of solitaire games implemented in C using ncurses"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.4.1
TERMUX_PKG_SRCURL=https://github.com/nielssp/csol/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=4117a9b7d6dbddb8549fa7bc8911e4bf8639f275629d428f160e7a824a29ba76
TERMUX_PKG_DEPENDS="libandroid-support, ncurses"
TERMUX_CMAKE_BUILD="Unix Makefiles"
