TERMUX_PKG_HOMEPAGE=http://www.openpgl.org/
TERMUX_PKG_DESCRIPTION="Intel(R) Open Path Guiding Library"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.7.1"
TERMUX_PKG_SRCURL="https://github.com/RenderKit/openpgl/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=d62d24241232a526491328f341df9add274fc84ae9818470d3edb5ae6141ac63
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, libtbb"
# OpenPGL does not support 32-bit
TERMUX_PKG_EXCLUDED_ARCHES="arm, i686"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DOPENPGL_BUILD_STATIC=OFF
"
