TERMUX_PKG_HOMEPAGE=https://git.sr.ht/~sircmpwn/scdoc
TERMUX_PKG_DESCRIPTION="Small man page generator"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Yaksh Bariya <thunder-coding@termux.dev>"
TERMUX_PKG_VERSION="1.11.3"
TERMUX_PKG_SRCURL=https://git.sr.ht/~sircmpwn/scdoc/archive/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=4c5c6136540384e5455b250f768e7ca11b03fdba1a8efc2341ee0f1111e57612
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="OUTDIR=$TERMUX_PKG_SRCDIR HOST_SCDOC=$TERMUX_PKG_HOSTBUILD_DIR/scdoc"
TERMUX_PKG_HOSTBUILD=true

termux_step_host_build() {
	cd $TERMUX_PKG_SRCDIR
	make OUTDIR=$TERMUX_PKG_HOSTBUILD_DIR
}
