TERMUX_PKG_HOMEPAGE="https://github.com/bgamari/attoparsec"
TERMUX_PKG_DESCRIPTION="Fast combinator parsing for bytestrings and text"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.14.4"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/attoparsec-${TERMUX_PKG_VERSION}/attoparsec-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="3f337fe58624565de12426f607c23e60c7b09c86b4e3adfc827ca188c9979e6c"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-scientific"
