TERMUX_PKG_HOMEPAGE=https://github.com/PJK/libcbor
TERMUX_PKG_DESCRIPTION="CBOR protocol implementation for C"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.13.0
TERMUX_PKG_SRCURL=https://github.com/PJK/libcbor/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=SKIP_CHECKSUM
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_BUILD_TYPE=Release
-DBUILD_SHARED_LIBS=ON
-DCBOR_BUILD_TESTS=OFF
-DCBOR_BUILD_DOCS=OFF
-DCBOR_CUSTOM_ALLOC=OFF
"
