TERMUX_PKG_HOMEPAGE=https://git.zx2c4.com/music-file-organizer/about/
TERMUX_PKG_DESCRIPTION="Organizer of audio files into directories based on metadata tags"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.0.4
TERMUX_PKG_REVISION=5
TERMUX_PKG_SRCURL=https://git.zx2c4.com/music-file-organizer/snapshot/music-file-organizer-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=9e3e2df24c5293e14c40d85fb480f5d52c0dc9afac845280a356c2fb6531e43e
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="libicu, taglib"
