TERMUX_PKG_HOMEPAGE="https://github.com/lxqt/qtxdg-tools"
TERMUX_PKG_DESCRIPTION="CLI tools for libqtxdg."
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.1.0"
TERMUX_PKG_SRCURL="https://github.com/lxqt/qtxdg-tools/releases/download/${TERMUX_PKG_VERSION}/qtxdg-tools-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=dbd59b7641091a226fb58222e11b4aeb36e6e65dc235280897d066e59fa966b6
TERMUX_PKG_DEPENDS="libc++, libqtxdg, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
