TERMUX_PKG_HOMEPAGE="https://github.com/lxqt/qtxdg-tools"
TERMUX_PKG_DESCRIPTION="CLI tools for libqtxdg."
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.0.0"
TERMUX_PKG_SRCURL="https://github.com/lxqt/qtxdg-tools/releases/download/${TERMUX_PKG_VERSION}/qtxdg-tools-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=4cd485e2780290d99d7242f605db9f0ffe5ed598cc672ed5e4acef871ce27b3a
TERMUX_PKG_DEPENDS="libc++, libqtxdg, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
