TERMUX_PKG_HOMEPAGE="https://github.com/lxqt/qtxdg-tools"
TERMUX_PKG_DESCRIPTION="CLI tools for libqtxdg."
TERMUX_PKG_LICENSE="LGPL-2.1"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="4.4.0"
TERMUX_PKG_SRCURL="https://github.com/lxqt/qtxdg-tools/releases/download/${TERMUX_PKG_VERSION}/qtxdg-tools-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=f21ba4308eac0effd417d910cc4916df7b6202aaeee777b51bb120f7abc6c5ac
TERMUX_PKG_DEPENDS="libc++, libqtxdg, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="lxqt-build-tools, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
