TERMUX_PKG_HOMEPAGE=https://goodies.xfce.org/
TERMUX_PKG_DESCRIPTION="this meta-package will install various utilities and programs for the XFCE desktop environment (incomplete!)"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@Yisus7u7"
TERMUX_PKG_VERSION=4.16.0
TERMUX_PKG_REVISION=2
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_DEPENDS="xfce4-terminal, xfce4-appfinder, xfce4-calculator-plugin, xfce4-clipman-plugin, xfce4-datetime-plugin, xfce4-dict, xfce4-eyes-plugin, xfce4-mailwatch-plugin, xfce4-netload-plugin, xfce4-notes-plugin, xfce4-notifyd, xfce4-panel-profiles, xfce4-screensaver, xfce4-taskmanager, xfce4-timer-plugin, xfce4-wavelan-plugin, xfce4-screenshooter, xfce4-whiskermenu-plugin, thunar-archive-plugin, parole, mousepad, file-roller, galculator, ristretto, gigolo"
TERMUX_PKG_METAPACKAGE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
