TERMUX_PKG_HOMEPAGE=https://github.com/hoedown/hoedown
TERMUX_PKG_DESCRIPTION="Hoedown is a revived fork of Sundown, the Markdown parser based on the original code of the Upskirt library"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_MAINTAINER="Leonid Plyushch <leonid.plyushch@gmail.com>"
TERMUX_PKG_VERSION=3.0.7
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/hoedown/hoedown/archive/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=01b6021b1ec329b70687c0d240b12edcaf09c4aa28423ddf344d2bd9056ba920
TERMUX_PKG_BUILD_IN_SRC=yes
