TERMUX_PKG_HOMEPAGE=https://www.cgal.org/
TERMUX_PKG_DESCRIPTION="Computational Geometry Algorithms Library"
TERMUX_PKG_LICENSE="GPL-3.0, LGPL-3.0, BSL-1.0, MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE, LICENSE.BSL, LICENSE.GPL, LICENSE.LGPL, LICENSE.RFL"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="6.1.1"
TERMUX_PKG_SRCURL=https://github.com/CGAL/cgal/releases/download/v${TERMUX_PKG_VERSION}/CGAL-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=52506935f70e247ed2777e3c65f20e86f79208c2a2d0e180ae7475daf11c96ef
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_GROUPS="science"

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DWITH_CGAL_Qt5=OFF
-DWITH_demos=OFF
-DWITH_examples=OFF
-DWITH_tests=OFF
"
