TERMUX_PKG_HOMEPAGE=https://www.cgal.org/
TERMUX_PKG_DESCRIPTION="Computational Geometry Algorithms Library"
TERMUX_PKG_LICENSE="GPL-3.0, LGPL-3.0, BSL-1.0, MIT"
TERMUX_PKG_LICENSE_FILE="LICENSE, LICENSE.BSL, LICENSE.GPL, LICENSE.LGPL, LICENSE.RFL"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=5.5.1
TERMUX_PKG_SRCURL=https://github.com/CGAL/cgal/releases/download/v${TERMUX_PKG_VERSION}/CGAL-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=091630def028facdcaf00eb5b68ad79eddac1b855cca6e87eef18a031566edfc
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_GROUPS="science"

TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DWITH_CGAL_Qt5=OFF
-DWITH_demos=OFF
-DWITH_examples=OFF
-DWITH_tests=OFF
"
