TERMUX_PKG_HOMEPAGE=https://github.com/google/oboe
TERMUX_PKG_DESCRIPTION="Google Oboe - C++ library for high-performance audio on Android"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.10.0"
TERMUX_PKG_SRCURL="https://github.com/google/oboe/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=0e4245f8860c4287040a5d76501c588490bcc9cb57614c486c0c201a5dde3e9f
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_NO_STATICSPLIT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"

termux_step_post_make_install() {
	# Upstream Oboe does not set CMake SOVERSION, so liboboe.so ships
	# with an unversioned SONAME (no .so.N suffix). Matches abseil-cpp.

	# Generate pkg-config file. Upstream Oboe ships no .pc or .pc.in
	# template, so it must be written by hand.
	mkdir -p "$TERMUX_PREFIX/lib/pkgconfig"
	cat <<EOF > "$TERMUX_PREFIX/lib/pkgconfig/oboe.pc"
prefix=$TERMUX_PREFIX
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include

Name: oboe
Description: $TERMUX_PKG_DESCRIPTION
Version: $TERMUX_PKG_VERSION
Libs: -L\${libdir} -loboe
Cflags: -I\${includedir}
EOF

	# Generate CMake package config files. Upstream Oboe's git-source
	# CMakeLists.txt has no install(EXPORT) target or
	# configure_package_config_file call. Upstream's own
	# docs/GettingStarted.md shows find_package(oboe REQUIRED CONFIG)
	# as the recommended path, which works via the prefab Maven package
	# (generated by Google's Maven publishing pipeline, not by the git
	# CMakeLists.txt). That path is Android-Studio-only. For a Termux
	# Linux-style consumer we write the config by hand below.
	local _cmakedir="$TERMUX_PREFIX/lib/cmake/oboe"
	mkdir -p "$_cmakedir"
	cat <<EOF > "$_cmakedir/oboeConfig.cmake"
if(NOT TARGET oboe::oboe)
add_library(oboe::oboe SHARED IMPORTED)
set_target_properties(oboe::oboe PROPERTIES
    IMPORTED_LOCATION "$TERMUX_PREFIX/lib/liboboe.so"
    INTERFACE_INCLUDE_DIRECTORIES "$TERMUX_PREFIX/include"
    INTERFACE_LINK_LIBRARIES ""
)
endif()
EOF

	cat <<EOF > "$_cmakedir/oboeConfigVersion.cmake"
set(PACKAGE_VERSION "$TERMUX_PKG_VERSION")
if("\${PACKAGE_VERSION}" VERSION_LESS "\${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if("\${PACKAGE_VERSION}" VERSION_EQUAL "\${PACKAGE_FIND_VERSION}")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
EOF
}
