TERMUX_PKG_HOMEPAGE=https://docs.xfce.org/panel-plugins/xfce4-netload-plugin/start
TERMUX_PKG_DESCRIPTION="network load monitor plugin for the Xfce4 panel"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Yisus7u7 <jesuspixel5@gmail.com>"
TERMUX_PKG_VERSION=1.4.0
TERMUX_PKG_REVISION=3
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/panel-plugins/xfce4-netload-plugin/1.4/xfce4-netload-plugin-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=6c76260e101790754dd93255ec979accd97d21a21da85d8edcd6c7b01ddcd70c
TERMUX_PKG_DEPENDS="gtk3, atk, libcairo, pango, gdk-pixbuf, glib, libxfce4util, libxfce4ui, xfce4-panel"
TERMUX_PKG_BUILD_IN_SRC=true
