TERMUX_PKG_HOMEPAGE=https://docs.xfce.org/panel-plugins/xfce4-netload-plugin/start
TERMUX_PKG_DESCRIPTION="network load monitor plugin for the Xfce4 panel"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
_MAJOR_VERSION=1.4
TERMUX_PKG_VERSION=${_MAJOR_VERSION}.0
TERMUX_PKG_REVISION=4
TERMUX_PKG_SRCURL=https://archive.xfce.org/src/panel-plugins/xfce4-netload-plugin/${_MAJOR_VERSION}/xfce4-netload-plugin-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=6c76260e101790754dd93255ec979accd97d21a21da85d8edcd6c7b01ddcd70c
TERMUX_PKG_DEPENDS="atk, gdk-pixbuf, glib, gtk3, harfbuzz, libcairo, libxfce4ui, libxfce4util, pango, xfce4-panel"
TERMUX_PKG_BUILD_IN_SRC=true
