TERMUX_PKG_HOMEPAGE=https://gitlab.gnome.org/GNOME/gtk-doc
TERMUX_PKG_DESCRIPTION="GTK+ DocBook Documentation Generator"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.37.0"
TERMUX_PKG_SRCURL=https://gitlab.gnome.org/GNOME/gtk-doc/-/archive/${TERMUX_PKG_VERSION}/gtk-doc-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=3059675f07bb5a6b1f92011add493494abd03b64c3e988cc0bc26a1cf44b51c9
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="glib"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-Dtests=false
"
