TERMUX_PKG_HOMEPAGE="https://github.com/tareksander/termux-gui-bash"
TERMUX_PKG_DESCRIPTION="A bash library for Termux:GUI"
TERMUX_PKG_LICENSE="MPL-2.0"
TERMUX_PKG_MAINTAINER="@tareksander"
TERMUX_PKG_VERSION="0.1.2"
TERMUX_PKG_SRCURL=https://github.com/tareksander/termux-gui-bash/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=e915af020b8c32b9f26ccdff839befb1d8eb7cc231363c6d96868606b71dc8b2
TERMUX_PKG_HAS_DEBUG=false
TERMUX_PKG_DEPENDS="jq"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
