TERMUX_PKG_HOMEPAGE="https://github.com/tareksander/termux-gui-bash"
TERMUX_PKG_DESCRIPTION="A bash library for Termux:GUI"
TERMUX_PKG_LICENSE="MPL-2.0"
TERMUX_PKG_MAINTAINER="@tareksander"
TERMUX_PKG_VERSION=0.1.0
TERMUX_PKG_SRCURL=https://github.com/tareksander/termux-gui-bash/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256="061b0185f627f83cb3b1f7d60a2ef9b545601254dda9dab3d22105e5cbedb72d"
TERMUX_PKG_HAS_DEBUG=false
TERMUX_PKG_DEPENDS="jq"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
