TERMUX_PKG_HOMEPAGE="https://herbstluftwm.org"
TERMUX_PKG_DESCRIPTION="Manual tiling window manager for X"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.9.5"
TERMUX_PKG_SRCURL="https://herbstluftwm.org/tarballs/herbstluftwm-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=b2d4600909e5bece5ad63818dfb30bb19fd2ac9f52847b1a7a74ad4040718105
TERMUX_PKG_DEPENDS="freetype, libx11, libxext, libxfixes, libxft, libxinerama, libxrandr"
TERMUX_PKG_RECOMMENDS="xorg-xsetroot"
TERMUX_PKG_BUILD_DEPENDS="xorgproto"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DCMAKE_INSTALL_SYSCONF_PREFIX=${TERMUX_PREFIX}/etc"
