TERMUX_PKG_HOMEPAGE=http://weechat.org/
TERMUX_PKG_DESCRIPTION="Fast, light and extensible IRC chat client"
TERMUX_PKG_VERSION=1.6
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=http://www.weechat.org/files/src/weechat-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=73eca5212fadb7056f5f72d9dfc96453dea0342c963d1f1ca36c84def5653c34
TERMUX_PKG_DEPENDS="ncurses, libgcrypt, libcurl, libgnutls, libandroid-support"
# weechat-curses is a symlink to weechat, so remove it:
TERMUX_PKG_RM_AFTER_INSTALL="bin/weechat-curses share/icons"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DZLIB_LIBRARY:FILEPATH=$TERMUX_STANDALONE_TOOLCHAIN/sysroot/usr/lib/libz.so"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DZLIB_INCLUDE_DIR:PATH=$TERMUX_STANDALONE_TOOLCHAIN/sysroot/usr/include"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DCA_FILE=$TERMUX_PREFIX/etc/tls/cert.pem -DENABLE_LUA=ON -DENABLE_MAN=ON"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" -DENABLE_PYTHON3=ON -DENABLE_PERL=ON -DENABLE_TCL=OFF"

