TERMUX_PKG_HOMEPAGE=https://github.com/termux/x11-packages
TERMUX_PKG_DESCRIPTION="Meta package for KDE Gear applications (incomplete!)"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=26.04
TERMUX_PKG_REVISION=15
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_DEPENDS="accessibility-inspector, alligator, ark, artikulate, audiotube, blinken, calligra, dolphin, elisa, filelight, gwenview, itinerary, kalzium, kanagram, kate, kbruch, kcalc, kcolorchooser, kdeconnect, kdegraphics-thumbnailers, kdenlive, kdialog, kfind, kgeography, kget, kgraphviewer, khangman, kig, kigo, kiriki, kiten, klettres, kmag, kmahjongg, kmines, kmousetool, kmouth, kmplot, knights, koko, kolourpaint, konsole, kontrast, konversation, kpat, krdc, krfb, kruler, ktouch, kturtle, kwalletmanager, kwave, kweather, kwordquiz, lskat, minuet, okular, palapeli, rocs, step, svgpart"
TERMUX_PKG_RECOMMENDS="akregator, angelfish, arianna, cantor, falkon, kaddressbook, kalarm, kalgebra, kimagemapeditor, kleopatra, kmail, konqueror, kontact, korganizer, ktorrent, marble, merkuro, neochat, parley, tokodon, zanshin"
TERMUX_PKG_METAPACKAGE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
