TERMUX_PKG_HOMEPAGE=https://github.com/termux/x11-packages
TERMUX_PKG_DESCRIPTION="Meta package for KDE Gear applications (incomplete!)"
TERMUX_PKG_LICENSE="Public Domain"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=26.04
TERMUX_PKG_REVISION=3
TERMUX_PKG_AUTO_UPDATE=false
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_DEPENDS="alligator, ark, audiotube, calligra, dolphin, elisa, filelight, gwenview, kate, kcalc, kcolorchooser, kdeconnect, kdegraphics-thumbnailers, kdenlive, kdialog, kget, kgraphviewer, kig, koko, kolourpaint, konsole, konversation, krdc, krfb, kruler, kwalletmanager, kwave, kweather, okular, svgpart"
TERMUX_PKG_RECOMMENDS="angelfish, arianna, falkon, kimagemapeditor, konqueror, ktorrent, neochat, tokodon"
TERMUX_PKG_METAPACKAGE=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
