TERMUX_PKG_HOMEPAGE=https://github.com/ada-url/ada
TERMUX_PKG_DESCRIPTION="WHATWG-compliant and fast URL parser written in modern C++"
TERMUX_PKG_LICENSE="Apache-2.0, MIT"
TERMUX_PKG_LICENSE_FILES="LICENSE-APACHE, LICENSE-MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.2.3"
TERMUX_PKG_SRCURL="https://github.com/ada-url/ada/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=8b9aa4dff92772d0029d8bc1f3f704afe34a899e23334bf04c7f0d019a5071c2
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_NO_STATICSPLIT=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=OFF
-DBUILD_STATIC_LIBS=ON
"
