TERMUX_PKG_HOMEPAGE=https://flameshot.org/
TERMUX_PKG_DESCRIPTION="Powerful yet simple to use screenshot software"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="13.0.1"
TERMUX_PKG_SRCURL=https://github.com/flameshot-org/flameshot/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=548867ae67a5cf0fbb8b2bb5dec2ac4e113c2980eda9abb7878041c374e5afa6
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++, qt6-qtbase, qt6-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt6-qttools"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DDISABLE_UPDATE_CHECKER=OFF
-DUSE_WAYLAND_CLIPBOARD=OFF
"
