TERMUX_PKG_HOMEPAGE=http://caca.zoy.org/wiki/toilet
TERMUX_PKG_DESCRIPTION="FIGlet-compatible display of large colourful characters in text mode"
TERMUX_PKG_LICENSE="WTFPL"
TERMUX_PKG_VERSION=0.3
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=http://fossies.org/linux/privat/toilet-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=89d4b530c394313cc3f3a4e07a7394fa82a6091f44df44dfcd0ebcb3300a81de
TERMUX_PKG_DEPENDS="libcaca"
TERMUX_PKG_BUILD_IN_SRC=yes
