TERMUX_PKG_HOMEPAGE=https://github.com/juzzlin/Heimer
TERMUX_PKG_DESCRIPTION="Heimer is a simple cross-platform mind map, diagram, and note-taking tool written in Qt."
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="Yisus7u7 <dev.yisus@hotmail.com>"
TERMUX_PKG_VERSION=3.6.3
TERMUX_PKG_SRCURL=https://github.com/juzzlin/Heimer/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=0bba6cd8f07ae51dcefdeae5ad5e6180d86d2cb720d274b68df9df49c8ff2113
TERMUX_PKG_DEPENDS="libc++, qt5-qtbase, qt5-qtsvg"
TERMUX_PKG_BUILD_DEPENDS="qt5-qtbase-cross-tools, qt5-qttools-cross-tools"
