TERMUX_PKG_HOMEPAGE="http://www.haskell.org/cabal/"
TERMUX_PKG_DESCRIPTION="A framework for packaging Haskell software"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="3.6.2.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/Cabal-${TERMUX_PKG_VERSION}/Cabal-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="9e903d06a7fb0893c6f303199e737a7d555fbb5e309be8bcc782b4eb2717bc42"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
