+++ ./Makefile
@@ -18,17 +18,17 @@
 
 # Variables you may well want to override.
 
-PREFIX        = /usr/local
+PREFIX        = @TERMUX_PREFIX@
 BINDIR        = $(PREFIX)/sbin
 MANDIR        = $(PREFIX)/share/man
 LOCALEDIR     = $(PREFIX)/share/locale
 BUILDDIR      = $(SRC)
 DESTDIR       = 
-CFLAGS        = -Wall -W -O2
-LDFLAGS       = 
+CFLAGS        ?= -Wall -W -O2
+LDFLAGS       ?= 
 COPTS         = 
 RPM_OPT_FLAGS = 
-LIBS          = 
+LIBS          = -llog
 LUA           = lua
 
 #################################################################
