--- ./Makefile.orig	2020-01-11 09:55:44.939872951 +0100
+++ ./Makefile	2020-01-11 09:56:29.246687538 +0100
@@ -18,17 +18,17 @@
 
 # Variables you may well want to override.
 
-PREFIX        = /usr/local
-BINDIR        = $(PREFIX)/sbin
+PREFIX        ?= /usr/local
+BINDIR        = $(PREFIX)/bin
 MANDIR        = $(PREFIX)/share/man
 LOCALEDIR     = $(PREFIX)/share/locale
 BUILDDIR      = $(SRC)
 DESTDIR       = 
-CFLAGS        = -Wall -W -O2
-LDFLAGS       = 
+CFLAGS        ?= -Wall -W -O2
+LDFLAGS       ?= 
 COPTS         = 
 RPM_OPT_FLAGS = 
-LIBS          = 
+LIBS          = -llog
 
 #################################################################
 
