--- ../Makefile.orig	2018-05-08 13:11:40.707974108 +0000
+++ ./Makefile	2018-05-08 13:17:01.037389651 +0000
@@ -18,14 +18,14 @@
 
 # Variables you may well want to override.
 
-PREFIX        = /usr/local
-BINDIR        = $(PREFIX)/sbin
+PREFIX        ?= /usr/local
+BINDIR        = $(PREFIX)/bin
 MANDIR        = $(PREFIX)/share/man
 LOCALEDIR     = $(PREFIX)/share/locale
 BUILDDIR      = $(SRC)
 DESTDIR       = 
-CFLAGS        = -Wall -W -O2
-LDFLAGS       = 
+CFLAGS        ?= -Wall -W -O2
+LDFLAGS       = -llog
 COPTS         = 
 RPM_OPT_FLAGS = 
 LIBS          = 
