TERMUX_PKG_HOMEPAGE=https://emersion.pages.freedesktop.org/libdisplay-info/
TERMUX_PKG_DESCRIPTION="EDID and DisplayID library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.4.0"
TERMUX_PKG_SRCURL=https://gitlab.freedesktop.org/emersion/libdisplay-info/-/releases/${TERMUX_PKG_VERSION}/downloads/libdisplay-info-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=43b180baa143e2035654759d84e2b2f5ee77d5fe817c423838c7fe59c0d68459
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="hwdata"
