TERMUX_PKG_HOMEPAGE="https://github.com/asciinema/agg"
TERMUX_PKG_DESCRIPTION="asciinema gif generator"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.0"
TERMUX_PKG_SRCURL="https://github.com/asciinema/agg/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=4bfbd0cc02f416ce868f0209b659a87e333de8f0b5edad19810e152ac6e7fc55
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_RECOMMENDS="asciinema"
TERMUX_PKG_BUILD_IN_SRC=true
