TERMUX_PKG_HOMEPAGE=https://github.com/mtrojnar/osslsigncode
TERMUX_PKG_DESCRIPTION="OpenSSL based Authenticode signing for PE/MSI/Java CAB files"
TERMUX_PKG_LICENSE="GPL-3.0-or-later"
TERMUX_PKG_LICENSE_FILE="COPYING.txt, LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.8"
TERMUX_PKG_SRCURL=https://github.com/mtrojnar/osslsigncode/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=d275d86bf0a8094e2c2ea451065299f965238be3cfaf3af6aff276302d759354
TERMUX_PKG_DEPENDS="libcurl, openssl, zlib"
TERMUX_PKG_AUTO_UPDATE=true
