TERMUX_PKG_HOMEPAGE=https://github.com/mtrojnar/osslsigncode
TERMUX_PKG_DESCRIPTION="OpenSSL based Authenticode signing for PE/MSI/Java CAB files"
TERMUX_PKG_LICENSE="GPL-3.0-or-later"
TERMUX_PKG_LICENSE_FILE="COPYING.txt, LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.13"
TERMUX_PKG_SRCURL=https://github.com/mtrojnar/osslsigncode/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ee95638b8bec0c019ddf28cb14988645abbd180dcd017536338b7d0d5eaaea96
TERMUX_PKG_DEPENDS="libcurl, openssl, zlib"
TERMUX_PKG_AUTO_UPDATE=true
