TERMUX_PKG_HOMEPAGE=http://savannah.nongnu.org/projects/acl
TERMUX_PKG_DESCRIPTION="Access control list shared library"
TERMUX_PKG_LICENSE="LGPL-2.1, GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.3.2"
TERMUX_PKG_SRCURL=https://download.savannah.gnu.org/releases/acl/acl-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=5f2bdbad629707aa7d85c623f994aa8a1d2dec55a73de5205bac0bf6058a2f7c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="attr"
