TERMUX_PKG_HOMEPAGE=https://github.com/axel-download-accelerator/axel
TERMUX_PKG_DESCRIPTION="light command line download accelerator"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="2.17.13"
TERMUX_PKG_SRCURL=https://github.com/axel-download-accelerator/axel/releases/download/v${TERMUX_PKG_VERSION}/axel-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=604ce7fbdb37500c462295d6c03fa59eb4dffb780fdf2fc3c41ffa75c8f6ec38
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="openssl"
