TERMUX_PKG_HOMEPAGE="https://github.com/sirwart/ripsecrets"
TERMUX_PKG_DESCRIPTION="A command-line tool to prevent committing secret keys into your source code"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.1.10"
TERMUX_PKG_SRCURL="https://github.com/sirwart/ripsecrets/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=379c189e7834e9a9db4e8cf1a7f09765356ca617ef1b70f6d8371d288bdd5ac7
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
