TERMUX_PKG_HOMEPAGE="https://github.com/sirwart/ripsecrets"
TERMUX_PKG_DESCRIPTION="A command-line tool to prevent committing secret keys into your source code"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.1.7"
TERMUX_PKG_SRCURL="https://github.com/sirwart/ripsecrets/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=12e1dfcd217bba34f74fd639d1a8de7dcf93ff2ae69398e093dfd794811db3ca
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
