TERMUX_PKG_HOMEPAGE="https://github.com/tbeu/matio"
TERMUX_PKG_DESCRIPTION="A C library for reading and writing Matlab MAT files"
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.5.25"
TERMUX_PKG_SRCURL="https://github.com/tbeu/matio/archive/refs/tags/v$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=119a60a1e96ddd0079b1f6a7747cc5ec69edd8d4346e5b72b386ce9c0ce8b4f5
TERMUX_PKG_DEPENDS="zlib"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DMATIO_WITH_HDF5:BOOL=OFF
-DMATIO_MAT73:BOOL=OFF
-DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF
-DMATIO_SHARED:BOOL=ON
"
