TERMUX_PKG_HOMEPAGE="https://hpjansson.org/chafa/"
TERMUX_PKG_DESCRIPTION="Image-to-text converter supporting a wide range of symbols, etc."
TERMUX_PKG_LICENSE="LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.18.3"
TERMUX_PKG_SRCURL="https://github.com/hpjansson/chafa/releases/download/${TERMUX_PKG_VERSION}/chafa-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=fb995ef21dce6c73dd0dd454ba3e0f7fac08e053ea16060a2e5ce69a3746ee27
TERMUX_PKG_DEPENDS="freetype, glib, libavif, libcairo, libheif, libjpeg-turbo, libjxl, librsvg, libtiff, libwebp"
TERMUX_PKG_AUTO_UPDATE=true
