TERMUX_PKG_HOMEPAGE="https://hpjansson.org/chafa/"
TERMUX_PKG_DESCRIPTION="Image-to-text converter supporting a wide range of symbols, etc."
TERMUX_PKG_LICENSE="LGPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.16.0"
TERMUX_PKG_SRCURL="https://github.com/hpjansson/chafa/releases/download/${TERMUX_PKG_VERSION}/chafa-${TERMUX_PKG_VERSION}.tar.xz"
TERMUX_PKG_SHA256=bf863e57b6200b696bde1742aa95d7feb8cd23b9df1e91e91859b2b1e54fd290
TERMUX_PKG_DEPENDS="freetype, glib, libcairo, libjpeg-turbo, libjxl, librsvg, libtiff, libwebp"
TERMUX_PKG_AUTO_UPDATE=true
