TERMUX_PKG_HOMEPAGE=https://yuriy-chumak.github.io/ol/
TERMUX_PKG_DESCRIPTION="Purely functional dialect of Lisp"
TERMUX_PKG_LICENSE="LGPL-3.0, MIT"
TERMUX_PKG_LICENSE_FILE="COPYING.LESSER, LICENSE"
TERMUX_PKG_MAINTAINER="Yuriy Chumak <yuriy.chumak@mail.com>"
TERMUX_PKG_VERSION="2.6"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/yuriy-chumak/ol/archive/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=c5506de4005a63039dc96962322ae94bf6c33eeaf63dcc03b07b1e8cc3a4d8f3
TERMUX_PKG_AUTO_UPDATE=true
# needs xxd
TERMUX_PKG_BUILD_DEPENDS="vim"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="PREFIX=$TERMUX_PREFIX"
