TERMUX_PKG_HOMEPAGE=https://yuriy-chumak.github.io/ol/
TERMUX_PKG_DESCRIPTION="Purely functional dialect of Lisp"
TERMUX_PKG_LICENSE="LGPL-3.0, MIT"
TERMUX_PKG_MAINTAINER="Yuriy Chumak <yuriy.chumak@mail.com>"
TERMUX_PKG_VERSION="2.7"
TERMUX_PKG_SRCURL=https://github.com/yuriy-chumak/ol/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=32dec0d527d456cce3273b907ffface6386a61288edf33f8724e2dd1bfb22319
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_DEPENDS="xxd"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="PREFIX=$TERMUX_PREFIX"
