TERMUX_SUBPKG_INCLUDE="
bin/llc
bin/lli
bin/sancov
bin/sanstats
bin/llvm*
bin/obj2yaml
bin/opt
bin/verify-uselistorder
bin/yaml2obj
share/opt-viewer
bin/bugpoint
bin/clang-check
bin/scan-build
bin/scan-view
share/man/man1/llc.1
share/man/man1/lli.1
share/man/man1/llvm*
share/man/man1/opt.1
share/man/man1/bugpoint.1
share/man/man1/tblgen.1
"
TERMUX_SUBPKG_DESCRIPTION="C language frontend for LLVM"
