TERMUX_SUBPKG_DESCRIPTION="Tools to create and/or extract ISO-9660 filesystems, verify their integrity, and write them to disc"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_DEPENDS="lame, libandroid-execinfo, libandroid-shmem, libacl, libcap, libiconv, pulseaudio, vorbis-tools"
TERMUX_SUBPKG_PROVIDES="cdrkit"
TERMUX_SUBPKG_INCLUDE="
bin/cdda2mp3
bin/cdda2ogg
bin/cdda2wav
bin/cdrecord
bin/devdump
bin/genisoimage
bin/icedax
bin/isodebug
bin/isodump
bin/isoinfo
bin/isovfy
bin/mkhybrid
bin/mkisofs
bin/mountcd
bin/pxupgrade
bin/readcd
bin/readom
bin/scgcheck
bin/scgskeleton
bin/wodim
share/doc/cdda2wav
share/doc/cdrecord
share/doc/mkisofs
share/man/man1/cdda2mp3.1.gz
share/man/man1/cdda2ogg.1.gz
share/man/man1/cdda2wav.1.gz
share/man/man1/cdrecord.1.gz
share/man/man1/mountcd.1.gz
share/man/man1/pxupgrade.1.gz
share/man/man1/readcd.1.gz
share/man/man1/scgcheck.1.gz
share/man/man1/scgskeleton.1.gz
share/man/man8/devdump.8.gz
share/man/man8/isodebug.8.gz
share/man/man8/isodump.8.gz
share/man/man8/isoinfo.8.gz
share/man/man8/isovfy.8.gz
share/man/man8/mkhybrid.8.gz
share/man/man8/mkisofs.8.gz
"
