TERMUX_SUBPKG_DESCRIPTION="SCCS is an implementation of the POSIX standard Source Code Control System"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_DEPENDS="libacl"
TERMUX_SUBPKG_INCLUDE="
bin/sccs
opt/schily/ccs
opt/schily/xpg4/bin/get
opt/schily/xpg4/bin/sccs
share/man/man1/admin.1.gz
share/man/man1/bdiff.1.gz
share/man/man1/cdc.1.gz
share/man/man1/comb.1.gz
share/man/man1/delta.1.gz
share/man/man1/get.1.gz
share/man/man1/help.1.gz
share/man/man1/prs.1.gz
share/man/man1/prt.1.gz
share/man/man1/rcs2sccs.1.gz
share/man/man1/rmdel.1.gz
share/man/man1/sact.1.gz
share/man/man1/sccs*
share/man/man1/sssdiff.1.gz
share/man/man1/unget.1.gz
share/man/man1/val.1.gz
share/man/man1/vc.1.gz
share/man/man1/what.1.gz
share/man/man5/changeset.5.gz
share/man/man5/sccs*
"
