TERMUX_SUBPKG_DESCRIPTION="Unique standard tape archiver with many enhancements"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_DEPENDS="libacl, libcap, libiconv"
TERMUX_SUBPKG_INCLUDE="
bin/gnutar
bin/scpio
bin/smt
bin/spax
bin/srmt
bin/star
bin/star_sym
bin/strar
bin/suntar
bin/ustar
etc/default/srmt
etc/default/star
include/schily/strar.h
share/doc/srmt/default-srmt.sample
share/doc/star/README
share/doc/star/README.ACL
share/doc/star/README.crash
share/doc/star/README.largefiles
share/doc/star/README.mtio
share/doc/star/README.otherbugs
share/doc/star/README.pattern
share/doc/star/README.posix-2001
share/doc/star/STARvsGNUTAR
share/man/man1/gnutar.1.gz
share/man/man1/scpio.1.gz
share/man/man1/smt.1.gz
share/man/man1/spax.1.gz
share/man/man1/srmt.1.gz
share/man/man1/star_sym.1.gz
share/man/man1/star.1.gz
share/man/man1/strar.1.gz
share/man/man1/suntar.1.gz
share/man/man1/ustar.1.gz
share/man/man5/star.5.gz
share/man/man5/streamarchive.5.gz
"
