TERMUX_PKG_HOMEPAGE=http://www.libsdl.org/projects/SDL_mixer
TERMUX_PKG_DESCRIPTION="A simple multi-channel audio mixer"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_LICENSE_FILE="COPYING.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=2.0.4
TERMUX_PKG_REVISION=17
TERMUX_PKG_SRCURL=https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=b4cf5a382c061cd75081cf246c2aa2f9df8db04bdda8dcdc6b6cca55bede2419
TERMUX_PKG_DEPENDS="libflac, libvorbis, opusfile, sdl2"
