TERMUX_PKG_HOMEPAGE="http://github.com/ekmett/semigroupoids"
TERMUX_PKG_DESCRIPTION="Semigroupoids: Category sans id"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="5.3.7"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/semigroupoids-${TERMUX_PKG_VERSION}/semigroupoids-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="6d45cdb6c58c75ca588859b80b2c92b6f48590a03e065c24ce5d767a6a963799"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-distributive, haskell-tagged, haskell-hashable, haskell-contravariant, haskell-transformers-compat, haskell-bifunctors, haskell-base-orphans, haskell-comonad, haskell-unordered-containers"
