/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__CONF_H__)
#define __CONF_H__


/* the default :-separated search path */
#if !defined(DEFAULTCALCPATH)
#define DEFAULTCALCPATH ".:./cal:~/.cal:/data/data/com.termux/files/usr/share/calc:/data/data/com.termux/files/usr/share/calc/custom"
#endif /* DEFAULTCALCPATH */

/* the default :-separated startup file list */
#if !defined(DEFAULTCALCRC)
#define DEFAULTCALCRC "/data/data/com.termux/files/usr/share/calc/startup:~/.calcrc:./.calcinit"
#endif /* DEFAULTCALCRC */

/* the location of the help directory */
#if !defined(HELPDIR)
#define HELPDIR "/data/data/com.termux/files/usr/share/calc/help"
#endif /* HELPDIR */

/* the location of the custom help directory */
#if !defined(CUSTOMHELPDIR)
#define CUSTOMHELPDIR "/data/data/com.termux/files/usr/share/calc/custhelp"
#endif /* CUSTOMHELPDIR */

/* the default pager to use */
#if !defined(DEFAULTCALCPAGER)
#define DEFAULTCALCPAGER "less"
#endif /* DEFAULTCALCPAGER */


#endif /* !__CONF_H__ */
