/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__FPOSVAL_H__)
#define __FPOSVAL_H__


/* what are our file position & size types? */
#undef FILEPOS_BITS
#define FILEPOS_BITS 64
#undef FILEPOS_LEN
#define FILEPOS_LEN 8
#define SWAP_HALF_IN_FILEPOS(dest, src) memcpy((void *)(dest), (void *)(src), 16)

#undef OFF_T_BITS
#define OFF_T_BITS 64
#undef OFF_T_LEN
#define OFF_T_LEN 8
#define SWAP_HALF_IN_OFF_T(dest, src)		(*(dest) = *(src))

#undef DEV_BITS
#define DEV_BITS 64
#undef DEV_LEN
#define DEV_LEN 8
#define SWAP_HALF_IN_DEV(dest, src)	memcpy((void *)(dest), (void *)(src), 8)

#undef INODE_BITS
#define INODE_BITS 64
#undef INODE_LEN
#define INODE_LEN 8
#define SWAP_HALF_IN_INODE(dest, src)	memcpy((void *)(dest), (void *)(src), 8)


#endif /* !__FPOSVAL_H__ */
