/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETPRID_H)
#define CALC_HAVE_GETPRID_H


/* do we have or want getprid()? */
#undef HAVE_GETPRID /* no */


#endif /* !CALC_HAVE_GETPRID_H */
