/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_POSSCL_H)
#define CALC_HAVE_POSSCL_H


#undef HAVE_FILEPOS_SCALAR
#define HAVE_FILEPOS_SCALAR /* FILEPOS is a simple value */


#endif /* !CALC_HAVE_POSSCL_H */
