/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_STDLIB_H)
#define CALC_HAVE_STDLIB_H


/* do we have <stdlib.h>? */
#define HAVE_STDLIB_H	 /* yes */


#endif /* !CALC_HAVE_STDLIB_H */
