/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UNISTD_H)
#define CALC_HAVE_UNISTD_H


/* do we have <unistd.h>? */
#define HAVE_UNISTD_H	 /* yes */


#endif /* !CALC_HAVE_UNISTD_H */
