/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETTIME_H)
#define CALC_HAVE_GETTIME_H


/* do we have or want clock_gettime()? */
#define HAVE_GETTIME /* yes - w/CLOCK_SGI_CYCLE */


#endif /* !CALC_HAVE_GETTIME_H */
