/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_URANDOM_H)
#define CALC_HAVE_URANDOM_H


/* do we have /dev/urandom? */
#define HAVE_URANDOM_H  /* yes */


#endif /* !CALC_HAVE_URANDOM_H */
