/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_FPOS_H)
#define CALC_HAVE_FPOS_H


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS
#define HAVE_FPOS 1  /* yes */

typedef fpos_t FILEPOS;


#endif /* !CALC_HAVE_FPOS_H */
