/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UID_T_H)
#define CALC_HAVE_UID_T_H


/* do we have or want uid_t? */
#define HAVE_UID_T /* yes */


#endif /* !CALC_HAVE_UID_T_H */
