/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_CONST_H)
#define CALC_HAVE_CONST_H


/* do we have or want const? */
#define HAVE_CONST /* yes */
#undef CONST
#define CONST const /* yes */


#endif /* !CALC_HAVE_CONST_H */
