/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_STRDUP_H)
#define CALC_HAVE_STRDUP_H


/* do we have or want getstrdup()? */
#define HAVE_STRDUP /* yes */


#endif /* !CALC_HAVE_STRDUP_H */
