/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UNUSED_H)
#define CALC_HAVE_UNUSED_H


/* do we have/want the unused attribute? */
#define HAVE_UNUSED /* yes */
#undef UNUSED
#define UNUSED __attribute__((unused)) /* yes */


#endif /* !CALC_HAVE_UNUSED_H */
