/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_FPOS_POS_H)
#define CALC_HAVE_FPOS_POS_H


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS_POS	/* no */
#undef FPOS_POS_BITS
#undef FPOS_POS_LEN


#endif /* !CALC_HAVE_FPOS_POS_H */
