/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_OFFSCL_H)
#define CALC_HAVE_OFFSCL_H


#undef HAVE_OFF_T_SCALAR
#define HAVE_OFF_T_SCALAR /* off_t is a simple value */


#endif /* !CALC_HAVE_OFFSCL_H */
