/*
 * DO NOT EDIT -- generated by the Makefile
 */

#if !defined(CALC_HAVE_USTAT_H)
#define CALC_HAVE_USTAT_H


/* do we have or want ustat()? */
#undef HAVE_USTAT /* no */


#endif /* !CALC_HAVE_USTAT_H */
