/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_STRING_H)
#define CALC_HAVE_STRING_H


/* do we have <string.h>? */
#define HAVE_STRING_H	 /* yes */


#endif /* !CALC_HAVE_STRING_H */
