/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_MEMMV_H)
#define CALC_HAVE_MEMMV_H


/* do we have or want memmove()? */
#define HAVE_MEMMOVE /* yes */


#endif /* !CALC_HAVE_MEMMV_H */
