/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_TIMES_H)
#define CALC_HAVE_TIMES_H


/* do we have <times.h>? */
#undef HAVE_TIMES_H  /* no */
#define HAVE_SYS_TIMES_H  /* yes */
#define HAVE_TIME_H  /* yes */
#define HAVE_SYS_TIME_H  /* yes */


#endif /* !CALC_HAVE_TIMES_H */
