/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_NEWSTR_H)
#define CALC_HAVE_NEWSTR_H


/* do we have or want memcpy(), memset() & strchr()? */
#define HAVE_NEWSTR /* yes */


#endif /* !CALC_HAVE_NEWSTR_H */
