/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETSID_H)
#define CALC_HAVE_GETSID_H


/* do we have or want getsid()? */
#define HAVE_GETSID /* yes */


#endif /* !CALC_HAVE_GETSID_H */
