/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(__FPOSVAL_H__)
#define __FPOSVAL_H__


/* what are our file position & size types? */
#undef FILEPOS_BITS
#define FILEPOS_BITS 64
#undef FILEPOS_LEN
#define FILEPOS_LEN 8
#define SWAP_HALF_IN_FILEPOS(dest, src)		(*(dest) = *(src))

#undef OFF_T_BITS
#define OFF_T_BITS 64
#undef OFF_T_LEN
#define OFF_T_LEN 8
#define SWAP_HALF_IN_OFF_T(dest, src)		(*(dest) = *(src))

#undef DEV_BITS
#define DEV_BITS 64
#undef DEV_LEN
#define DEV_LEN 8
#define SWAP_HALF_IN_DEV(dest, src)	memcpy((void *)(dest), (void *)(src), 8)

#undef INODE_BITS
#define INODE_BITS 64
#undef INODE_LEN
#define INODE_LEN 8
#define SWAP_HALF_IN_INODE(dest, src)	memcpy((void *)(dest), (void *)(src), 8)


#endif /* !__FPOSVAL_H__ */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_CONST_H)
#define CALC_HAVE_CONST_H


/* do we have or want const? */
#define HAVE_CONST /* yes */
#undef CONST
#define CONST const /* yes */


#endif /* !CALC_HAVE_CONST_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_FPOS_H)
#define CALC_HAVE_FPOS_H


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS
#define HAVE_FPOS 1  /* yes */

typedef fpos_t FILEPOS;


#endif /* !CALC_HAVE_FPOS_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_FPOS_POS_H)
#define CALC_HAVE_FPOS_POS_H


/* do we have fgetpos & fsetpos functions? */
#undef HAVE_FPOS_POS	/* no */
#undef FPOS_POS_BITS
#undef FPOS_POS_LEN


#endif /* !CALC_HAVE_FPOS_POS_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETPGID_H)
#define CALC_HAVE_GETPGID_H


/* do we have or want getpgid()? */
#define HAVE_GETPGID /* yes */


#endif /* !CALC_HAVE_GETPGID_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETPRID_H)
#define CALC_HAVE_GETPRID_H


/* do we have or want getprid()? */
#undef HAVE_GETPRID /* no */


#endif /* !CALC_HAVE_GETPRID_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETSID_H)
#define CALC_HAVE_GETSID_H


/* do we have or want getsid()? */
#define HAVE_GETSID /* yes */


#endif /* !CALC_HAVE_GETSID_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_GETTIME_H)
#define CALC_HAVE_GETTIME_H


/* do we have or want clock_gettime()? */
#define HAVE_GETTIME /* yes - w/CLOCK_SGI_CYCLE */


#endif /* !CALC_HAVE_GETTIME_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_MEMMV_H)
#define CALC_HAVE_MEMMV_H


/* do we have or want memmove()? */
#define HAVE_MEMMOVE /* yes */


#endif /* !CALC_HAVE_MEMMV_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_NEWSTR_H)
#define CALC_HAVE_NEWSTR_H


/* do we have or want memcpy(), memset() & strchr()? */
#define HAVE_NEWSTR /* yes */


#endif /* !CALC_HAVE_NEWSTR_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_OFFSCL_H)
#define CALC_HAVE_OFFSCL_H


#undef HAVE_OFF_T_SCALAR
#define HAVE_OFF_T_SCALAR /* off_t is a simple value */


#endif /* !CALC_HAVE_OFFSCL_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_POSSCL_H)
#define CALC_HAVE_POSSCL_H


#undef HAVE_FILEPOS_SCALAR
#define HAVE_FILEPOS_SCALAR /* FILEPOS is a simple value */


#endif /* !CALC_HAVE_POSSCL_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_RUSAGE_H)
#define CALC_HAVE_RUSAGE_H


/* do we have or want getrusage()? */
#define HAVE_GETRUSAGE /* yes */


#endif /* !CALC_HAVE_RUSAGE_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_STDLIB_H)
#define CALC_HAVE_STDLIB_H


/* do we have <stdlib.h>? */
#define HAVE_STDLIB_H	 /* yes */


#endif /* !CALC_HAVE_STDLIB_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_STRDUP_H)
#define CALC_HAVE_STRDUP_H


/* do we have or want getstrdup()? */
#define HAVE_STRDUP /* yes */


#endif /* !CALC_HAVE_STRDUP_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_STRING_H)
#define CALC_HAVE_STRING_H


/* do we have <string.h>? */
#define HAVE_STRING_H	 /* yes */


#endif /* !CALC_HAVE_STRING_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_TIMES_H)
#define CALC_HAVE_TIMES_H


/* do we have <times.h>? */
#undef HAVE_TIMES_H  /* no */
#define HAVE_SYS_TIMES_H  /* yes */
#define HAVE_TIME_H  /* yes */
#define HAVE_SYS_TIME_H  /* yes */


#endif /* !CALC_HAVE_TIMES_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UID_T_H)
#define CALC_HAVE_UID_T_H


/* do we have or want uid_t? */
#define HAVE_UID_T /* yes */


#endif /* !CALC_HAVE_UID_T_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UNISTD_H)
#define CALC_HAVE_UNISTD_H


/* do we have <unistd.h>? */
#define HAVE_UNISTD_H	 /* yes */


#endif /* !CALC_HAVE_UNISTD_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_UNUSED_H)
#define CALC_HAVE_UNUSED_H


/* do we have/want the unused attribute? */
#define HAVE_UNUSED /* yes */
#undef UNUSED
#define UNUSED __attribute__((unused)) /* yes */


#endif /* !CALC_HAVE_UNUSED_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_URANDOM_H)
#define CALC_HAVE_URANDOM_H


/* do we have /dev/urandom? */
#define HAVE_URANDOM_H  /* yes */


#endif /* !CALC_HAVE_URANDOM_H */
/*
 * DO NOT EDIT -- generated by the Makefile
 */


#if !defined(CALC_HAVE_USTAT_H)
#define CALC_HAVE_USTAT_H


/* do we have or want ustat()? */
#undef HAVE_USTAT /* no */


#endif /* !CALC_HAVE_USTAT_H */
