TERMUX_PKG_HOMEPAGE="https://www.gecode.dev/"
TERMUX_PKG_DESCRIPTION="Generic Constraint Development Environment"
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="6.4.0"
TERMUX_PKG_SRCURL="https://github.com/Gecode/gecode/archive/refs/tags/release-$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=4cc0e4f440f821a643e637801094cd42ccb5946caf5248c905f29f5f3a16f260
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_FORCE_CMAKE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DENABLE_GIST=OFF
-DENABLE_CPPROFILER=OFF
-DBUILD_EXAMPLES=OFF
"
