TERMUX_PKG_HOMEPAGE="https://www.gecode.dev/"
TERMUX_PKG_DESCRIPTION="Generic Constraint Development Environment"
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="6.3.0"
TERMUX_PKG_SRCURL="https://github.com/Gecode/gecode/archive/refs/tags/release-$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=3edd6b13a6b9543614f7377c53a71c565ff315898d4788b651d01285bf91100a
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_FORCE_CMAKE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
-DENABLE_GIST=OFF
-DENABLE_CPPROFILER=OFF
-DBUILD_EXAMPLES=OFF
"
