TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/indexed-traversable"
TERMUX_PKG_DESCRIPTION="FunctorWithIndex, FoldableWithIndex, TraversableWithIndex"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.1.2"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/indexed-traversable-${TERMUX_PKG_VERSION}/indexed-traversable-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="516858ee7198b1fed1b93c665157f9855fd947379db7f115d48c1b0d670e698d"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
