TERMUX_PKG_HOMEPAGE=https://github.com/json-c/json-c/wiki
TERMUX_PKG_DESCRIPTION="A JSON implementation in C"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.19"
TERMUX_PKG_SRCURL=https://s3.amazonaws.com/json-c_releases/releases/json-c-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=37ad0249902e301bd9052bf712e511fcc6acff4ecaad4b5900aad9ce564e26de
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BREAKS="json-c-dev"
TERMUX_PKG_REPLACES="json-c-dev"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DDISABLE_WERROR=ON
-DHAVE_LOCALE_H=OFF
-DHAVE_XLOCALE_H=OFF
-DCMAKE_POLICY_VERSION_MINIMUM=3.5
"
