TERMUX_PKG_HOMEPAGE=https://github.com/json-c/json-c/wiki
TERMUX_PKG_DESCRIPTION="A JSON implementation in C"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.17"
TERMUX_PKG_SRCURL=https://s3.amazonaws.com/json-c_releases/releases/json-c-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=7550914d58fb63b2c3546f3ccfbe11f1c094147bd31a69dcd23714d7956159e6
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BREAKS="json-c-dev"
TERMUX_PKG_REPLACES="json-c-dev"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DDISABLE_WERROR=ON
"
