TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="X.Org authorization settings program"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.1.3"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/app/xauth-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=e7075498bae332f917f01d660f9b940c0752b2556a8da61ccb62a44d0ffe9d33
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libx11, libxau, libxext, libxmu"
TERMUX_PKG_BUILD_DEPENDS="xorg-util-macros"
