TERMUX_PKG_HOMEPAGE="https://github.com/baskerville/sxhkd"
TERMUX_PKG_DESCRIPTION="Simple X hotkey daemon"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@leapofazzam123"
TERMUX_PKG_VERSION=0.6.2
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL="https://github.com/baskerville/sxhkd/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256="1edc8b1a8b3631c10ba9cb9df1181830dacbbdf77adb558e31d5dd2029637386"
TERMUX_PKG_DEPENDS="libx11, libxcb, libxkbcommon, xcb-util, xcb-util-keysyms"
TERMUX_PKG_BUILD_IN_SRC=true
