TERMUX_PKG_HOMEPAGE=https://github.com/venam/2bwm
TERMUX_PKG_DESCRIPTION="A fast floating WM"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_LICENSE_FILE="LICENSE.2bwm, LICENSE.hidden"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.4"
TERMUX_PKG_SRCURL=https://github.com/venam/2bwm/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=74f30e049dc43ed1bcd2667b75dcc9c9b6544a7851f29537d1fb58d04300da8e
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_DEPENDS="libxcb, xcb-util-keysyms, xcb-util-wm, xcb-util-xrm"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="
PREFIX=$TERMUX_PREFIX
X11_INCLUDE=$TERMUX_PREFIX/include
"

termux_step_post_get_source() {
	cp $TERMUX_PKG_BUILDER_DIR/LICENSE.{2bwm,hidden} ./
}
