TERMUX_PKG_HOMEPAGE=https://github.com/facebookincubator/fastmod
TERMUX_PKG_DESCRIPTION="Regex-based code refactoring utility"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.4.4"
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://github.com/facebookincubator/fastmod/archive/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=b438cc7564ef34d01f27cdd3cd50ee66a9915b9c50939ca021c6bee2e9c1f069
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
