TERMUX_PKG_HOMEPAGE=https://github.com/facebookincubator/fastmod
TERMUX_PKG_DESCRIPTION="Regex-based code refactoring utility"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.4.2
TERMUX_PKG_SRCURL=https://github.com/facebookincubator/fastmod/archive/v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=5afb4c449aa7d1efe34e0540507fc1d1f40f7eba0861b2bb10409080faeffc4a
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
