TERMUX_PKG_HOMEPAGE=https://osmcode.org/osmium-tool/
TERMUX_PKG_DESCRIPTION="A multipurpose command line tool based on the Osmium Library"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_LICENSE_FILE="LICENSE.txt"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.14.0
TERMUX_PKG_REVISION=0
TERMUX_PKG_SRCURL=https://github.com/osmcode/osmium-tool/archive/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=67765fe6b612e791aab276af601dd12410b70486946e983753f6b0442f915233
TERMUX_PKG_DEPENDS="libosmium, libprotozero, boost, libbz2, zlib, liblz4, libexpat"
TERMUX_PKG_BUILD_DEPENDS="boost-headers"
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_AUTO_UPDATE=true
