TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="X.org Bitmap files"
# License: HPND
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="COPYING"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.1.3
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/data/xbitmaps-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=ad6cad54887832a17d86c2ccfc5e52a1dfab090f8307b152c78b0e1529cd0f7a
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_NO_DEVELSPLIT=true
