TERMUX_PKG_HOMEPAGE=http://www.catb.org/~esr/ascii/
TERMUX_PKG_DESCRIPTION="List ASCII idiomatic names and octal/decimal code-point forms"
TERMUX_PKG_LICENSE="BSD 2-Clause"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.30
TERMUX_PKG_SRCURL="http://www.catb.org/~esr/ascii/ascii-$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=ed2fdc973e1b87da2af83050e560e731b0f3bf5f6b4fd9babc9f60bb2b992443
TERMUX_PKG_LICENSE_FILE=COPYING
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="DESTDIR=$TERMUX_PREFIX PREFIX="
