TERMUX_PKG_HOMEPAGE=http://www.catb.org/~esr/ascii/
TERMUX_PKG_DESCRIPTION="List ASCII idiomatic names and octal/decimal code-point forms"
TERMUX_PKG_LICENSE=BSD-2-Clause
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=3.30
TERMUX_PKG_SRCURL="http://www.catb.org/~esr/ascii/ascii-$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=8753ddf7ef4f477af50f69208fab09e5dad85033e04611de94b6b679ce59b001
TERMUX_PKG_LICENSE_FILE=COPYING
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_MAKE_ARGS="DESTDIR=$TERMUX_PREFIX PREFIX="
