TERMUX_PKG_HOMEPAGE='https://krita.org'
TERMUX_PKG_DESCRIPTION='An embeddable expression evaluation engine (Krita fork)'
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="6.0.0.0"
TERMUX_PKG_SRCURL="https://invent.kde.org/graphics/kseexpr/-/archive/v${TERMUX_PKG_VERSION}/kseexpr-v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=60f84d26f922b65951a81cfb37323040927c5f01101a60f9563573016e0a52b8
TERMUX_PKG_DEPENDS="kf6-ki18n, libc++, qt6-qtbase"
TERMUX_PKG_BUILD_DEPENDS="extra-cmake-modules, qt6-qttools"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DENABLE_QT6=ON
-DBUILD_DEMOS=OFF
-DBUILD_TESTS=OFF
"
