TERMUX_PKG_HOMEPAGE="https://github.com/ros/urdfdom_headers"
TERMUX_PKG_DESCRIPTION="Headers for URDF parsers"
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Pooya Moradi <pvonmoradi@gmail.com>"
TERMUX_PKG_VERSION="2.1.0"
TERMUX_PKG_SRCURL="https://github.com/ros/urdfdom_headers/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=aa5509d1931d31acb070d34cee9f46a08e1d62b1f89d50a1392405cdf4f02966
TERMUX_PKG_UPDATE_TAG_TYPE="newest-tag"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_FORCE_CMAKE=true
