TERMUX_PKG_HOMEPAGE="https://github.com/ros/urdfdom_headers"
TERMUX_PKG_DESCRIPTION="Headers for URDF parsers"
TERMUX_PKG_GROUPS="science"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Pooya Moradi <pvonmoradi@gmail.com>"
TERMUX_PKG_VERSION=1.1.0
TERMUX_PKG_SRCURL="https://github.com/ros/urdfdom_headers/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=01b91c2f7cb42b0033cbdf559684a60001f9927e5d0a5a3682a344cc354f1d39
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_FORCE_CMAKE=true
