TERMUX_PKG_HOMEPAGE="https://github.com/glguy/th-abstraction"
TERMUX_PKG_DESCRIPTION="Nicer interface for reified information about data types"
TERMUX_PKG_LICENSE="ISC"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.4.3.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/th-abstraction-${TERMUX_PKG_VERSION}/th-abstraction-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="c8bb13e31d1d22a99168536a35c66e1091a6e4274b9841a023eac52c2bd3de06"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
