TERMUX_PKG_HOMEPAGE="https://github.com/spell-music/data-fix"
TERMUX_PKG_DESCRIPTION="Fixpoint data types"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.3.2"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/data-fix-${TERMUX_PKG_VERSION}/data-fix-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="3a172d3bc0639c327345e965f9d9023e099425814b28dcdb7b60ff66d66219cc"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs, haskell-hashable"
