TERMUX_PKG_HOMEPAGE="https://hackage.haskell.org/package/tar"
TERMUX_PKG_DESCRIPTION="Reading, writing and manipulating '.tar' archive files."
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="0.5.1.1"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/tar-${TERMUX_PKG_VERSION}/tar-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="b384449f62b2b0aa3e6d2cb1004b8060b01f21ec93e7b63e7af6d8fad8a9f1de"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
