TERMUX_SUBPKG_INCLUDE="lib/mono/"
TERMUX_SUBPKG_DESCRIPTION="Platform-independent libraries for mono"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_BREAKS="mono (<< 6.12.0.122-2)"
TERMUX_SUBPKG_REPLACES="mono (<< 6.12.0.122-2)"
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
