TERMUX_PKG_HOMEPAGE=https://git.vuxu.org/lr/about/
TERMUX_PKG_DESCRIPTION="list files, recursively, includes the best features of ls, find, stat and du"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.6"
TERMUX_PKG_SRCURL=https://git.vuxu.org/lr/snapshot/lr-$TERMUX_PKG_VERSION.tar.xz
TERMUX_PKG_SHA256=8d98a75cdff289e86b4e40bc7c750cc9b40a1f3d229214937fe601e087a2f61c
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
