--- ../Makefile.orig	2018-12-10 13:16:30.152694737 +0100
+++ ./Makefile	2018-12-10 13:17:15.086091432 +0100
@@ -4,7 +4,7 @@
 TAG = $(NAME)-$(VERSION)
 RPMBUILD=$(shell `which rpmbuild >&/dev/null` && echo "rpmbuild" || echo "rpm")
 
-prefix=/usr
+prefix ?= /usr
 includedir=$(prefix)/include
 libdir=$(prefix)/lib
 
