TERMUX_PKG_HOMEPAGE="https://github.com/haskell/base64-bytestring"
TERMUX_PKG_DESCRIPTION="Fast base64 encoding and decoding for ByteStrings"
TERMUX_PKG_LICENSE="BSD 3-Clause"
TERMUX_PKG_MAINTAINER="Aditya Alok <dev.aditya.alok@gmail.com>"
TERMUX_PKG_VERSION="1.2.1.0"
TERMUX_PKG_SRCURL="https://hackage.haskell.org/package/base64-bytestring-${TERMUX_PKG_VERSION}/base64-bytestring-${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256="fbf8ed30edde271eb605352021431d8f1b055f95a56af31fe2eacf6bdfdc49c9"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="ghc-libs"
