TERMUX_PKG_HOMEPAGE=https://quickjs-ng.github.io/quickjs/
TERMUX_PKG_DESCRIPTION="Embeddable JavaScript engine in C (NG fork)"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="0.16.2"
TERMUX_PKG_SRCURL="https://github.com/quickjs-ng/quickjs/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=97c80625b26775a4c7ca618c004d4ea24cf99cbf867e4eba78bd927a8b23d106
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_CONFLICTS="quickjs"
TERMUX_PKG_PROVIDES="quickjs"
TERMUX_PKG_REPLACES="quickjs"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_SHARED_LIBS=ON
"
