root = "$PREFIX/var/lib/containerd"
state = "$PREFIX/var/run/containerd"
imports = ["$PREFIX/etc/containerd/runtime_*.toml", "./debug.toml"]

[grpc]
  address = "$PREFIX/var/run/containerd/containerd.sock"

[debug]
  address = "$PREFIX/var/run/containerd/debug.sock"
