TERMUX_PKG_HOMEPAGE=https://xorg.freedesktop.org/
TERMUX_PKG_DESCRIPTION="X.org font alias files"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Leonid Pliushch <leonid.pliushch@gmail.com>"
TERMUX_PKG_VERSION=1.0.4
TERMUX_PKG_REVISION=2
TERMUX_PKG_SRCURL=https://xorg.freedesktop.org/releases/individual/font/font-alias-${TERMUX_PKG_VERSION}.tar.bz2
TERMUX_PKG_SHA256=f3111ae8bf2e980f5f56af400e8eefe5fc9f4207f4a412ea79637fd66c945276
TERMUX_PKG_PLATFORM_INDEPENDENT=true
