name: Clean source mirror

on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:

permissions: {} # none

concurrency:
  group: .github/workflows/packages.yml
  cancel-in-progress: false

jobs:
  clean:
    permissions:
      contents: write
    if: github.repository == 'termux/termux-packages'
    runs-on: ubuntu-slim
    steps:
      - name: Git clone
        uses: actions/checkout@v7
      - name: Clean source mirror
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/bin/source-mirror clean
